(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item28 roome)
              (at item27 roome)
              (at item26 roome)
              (at item25 roome)
              (at item24 roomd)
              (at item23 roomd)
              (at item22 roomd)
              (at item21 roomd)
              (at item20 roomc)
              (at item19 roomc)
              (at item18 roomc)
              (at item17 roomc)
              (at item16 rooma)
              (at item15 rooma)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (at-bot bot3 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (free left3)
              (free right3)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (mount left3 bot3)
              (mount right3 bot3)
              (door rooma roomb)
              (door roomb roomc)
              (door roomc roomd)
              (door roomd roome)
              (door roome rooma)
              (load_limit--bot1_1)
              (load_limit--bot1_2)
              (load_limit--bot2_1)
              (load_limit--bot2_2)
              (load_limit--bot3_1)
              (load_limit--bot3_2)
              (weight--item28_1)
              (weight--item27_1)
              (weight--item26_1)
              (weight--item25_1)
              (weight--item24_0)
              (weight--item23_0)
              (weight--item22_0)
              (weight--item21_0)
              (weight--item20_0)
              (weight--item19_0)
              (weight--item18_0)
              (weight--item17_0)
              (weight--item16_0)
              (weight--item15_0)
              (weight--item14_0)
              (v0_2)
              (weight--item13_0)
              (v1_2)
              (weight--item12_0)
              (weight--item11_0)
              (v2_2)
              (weight--item10_0)
              (weight--item9_0)
              (v3_0)
              (v3_2)
              (weight--item8_0)
              (weight--item7_0)
              (v4_0)
              (v4_2)
              (weight--item6_0)
              (v5_0)
              (v5_2)
              (weight--item5_0)
              (weight--item4_1)
              (weight--item3_1)
              (weight--item2_1)
              (weight--item1_1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item28 roomb)
           (at item27 roomb)
           (at item26 roomb)
           (at item25 roomb)
           (at item24 roomb)
           (at item23 roomb)
           (at item22 roomc)
           (at item21 roomc)
           (at item20 roomc)
           (at item19 roomc)
           (at item18 roomd)
           (at item17 roomd)
           (at item16 roomd)
           (at item15 roomd)
           (at item14 roome)
           (at item13 roome)
           (at item12 roome)
           (at item11 roome)
           (at item10 roome)
           (at item9 roome)
           (at item8 roome)
           (at item7 roome)
           (at item6 roome)
           (at item5 roome)
           (at item4 roome)
           (at item3 roome)
           (at item2 roome)
           (at item1 roome)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
