(define (domain compiledproblem-domain)
 (:requirements :strips :typing :negative-preconditions :disjunctive-preconditions :conditional-effects :action-costs)
 (:types room item bot arm)
 (:constants
   bot2 bot1 - bot
   roomc rooma roomb - room
   item2 item3 item4 item1 - item
   left1 right1 right2 left2 - arm
 )
 (:predicates 
             (c_0_-1)
             (c_0_0)
             (c_0_1)
             (c_0_2)
             (c_0_3)
             (c_0_4)
             (c_0_5)
             (z_0_0)
             (z_0_1)
             (z_0_2)
             (z_0_3)
             (z_0_4)
             (z_0_5)
             (c_1_-1)
             (c_1_0)
             (c_1_1)
             (c_1_2)
             (c_1_3)
             (c_1_4)
             (c_1_5)
             (z_1_0)
             (z_1_1)
             (z_1_2)
             (z_1_3)
             (z_1_4)
             (z_1_5)
             (c_2_-1)
             (c_2_0)
             (c_2_1)
             (c_2_2)
             (c_2_3)
             (c_2_4)
             (c_2_5)
             (z_2_0)
             (z_2_1)
             (z_2_2)
             (z_2_3)
             (z_2_4)
             (z_2_5)
             (c_3_-1)
             (c_3_0)
             (c_3_1)
             (c_3_2)
             (c_3_3)
             (c_3_4)
             (c_3_5)
             (z_3_0)
             (z_3_1)
             (z_3_2)
             (z_3_3)
             (z_3_4)
             (z_3_5)
             (false)
             (weight--item4_0)
             (weight--item4_1)
             (weight--item4_2)
             (weight--item4_3)
             (weight--item4_4)
             (weight--item4_5)
             (weight--item3_0)
             (weight--item3_1)
             (weight--item3_2)
             (weight--item3_3)
             (weight--item3_4)
             (weight--item3_5)
             (current_load--bot1_0)
             (current_load--bot1_1)
             (current_load--bot1_2)
             (current_load--bot1_3)
             (current_load--bot1_4)
             (current_load--bot1_5)
             (weight--item2_0)
             (weight--item2_1)
             (weight--item2_2)
             (weight--item2_3)
             (weight--item2_4)
             (weight--item2_5)
             (load_limit--bot1_0)
             (load_limit--bot1_1)
             (load_limit--bot1_2)
             (load_limit--bot1_3)
             (load_limit--bot1_4)
             (load_limit--bot1_5)
             (weight--item1_0)
             (weight--item1_1)
             (weight--item1_2)
             (weight--item1_3)
             (weight--item1_4)
             (weight--item1_5)
             (current_load--bot2_0)
             (current_load--bot2_1)
             (current_load--bot2_2)
             (current_load--bot2_3)
             (current_load--bot2_4)
             (current_load--bot2_5)
             (load_limit--bot2_0)
             (load_limit--bot2_1)
             (load_limit--bot2_2)
             (load_limit--bot2_3)
             (load_limit--bot2_4)
             (load_limit--bot2_5)
             (v0_0)
             (v0_1)
             (v0_2)
             (v0_3)
             (v0_4)
             (v0_5)
             (v1_0)
             (v1_1)
             (v1_2)
             (v1_3)
             (v1_4)
             (v1_5)
             (at-bot ?b - bot ?x - room)
             (at ?i - item ?x - room)
             (door ?x - room ?y - room)
             (free ?a - arm)
             (in-arm ?i - item ?a - arm)
             (in-tray ?i - item ?b - bot)
             (mount ?a - arm ?b - bot)
             (of)
 )
 (:functions 
             (total-cost)
 )
 (:derived (c_0_-1) (false))
(:derived (c_0_0) (or (v0_0) (and (c_0_-1) (not (v0_0)))))
(:derived (c_0_1) (and (c_0_0) (v0_1)))
(:derived (c_0_2) (and (c_0_1) (v0_2)))
(:derived (c_0_3) (and (c_0_2) (v0_3)))
(:derived (c_0_4) (and (c_0_3) (v0_4)))
(:derived (c_0_5) (and (c_0_4) (v0_5)))
(:derived (z_0_0) (or (and (not (v0_0)) (not (c_0_-1))) (and (c_0_-1) (v0_0))))
(:derived (z_0_1) (or (and (v0_1) (not (c_0_0))) (and (c_0_0) (not (v0_1)))))
(:derived (z_0_2) (or (and (v0_2) (not (c_0_1))) (and (c_0_1) (not (v0_2)))))
(:derived (z_0_3) (or (and (v0_3) (not (c_0_2))) (and (c_0_2) (not (v0_3)))))
(:derived (z_0_4) (or (and (v0_4) (not (c_0_3))) (and (c_0_3) (not (v0_4)))))
(:derived (z_0_5) (or (and (v0_5) (not (c_0_4))) (and (c_0_4) (not (v0_5)))))
(:derived (c_1_-1) (false))
(:derived (c_1_0) (or (v0_0) (and (c_1_-1) (not (v0_0)))))
(:derived (c_1_1) (or (v0_1) (and (c_1_0) (not (v0_1)))))
(:derived (c_1_2) (or (v0_2) (and (c_1_1) (not (v0_2)))))
(:derived (c_1_3) (or (v0_3) (and (c_1_2) (not (v0_3)))))
(:derived (c_1_4) (or (v0_4) (and (c_1_3) (not (v0_4)))))
(:derived (c_1_5) (or (v0_5) (and (c_1_4) (not (v0_5)))))
(:derived (z_1_0) (or (and (not (v0_0)) (not (c_1_-1))) (and (c_1_-1) (v0_0))))
(:derived (z_1_1) (or (and (not (v0_1)) (not (c_1_0))) (and (c_1_0) (v0_1))))
(:derived (z_1_2) (or (and (not (v0_2)) (not (c_1_1))) (and (c_1_1) (v0_2))))
(:derived (z_1_3) (or (and (not (v0_3)) (not (c_1_2))) (and (c_1_2) (v0_3))))
(:derived (z_1_4) (or (and (not (v0_4)) (not (c_1_3))) (and (c_1_3) (v0_4))))
(:derived (z_1_5) (or (and (not (v0_5)) (not (c_1_4))) (and (c_1_4) (v0_5))))
(:derived (c_2_-1) (false))
(:derived (c_2_0) (or (v1_0) (and (c_2_-1) (not (v1_0)))))
(:derived (c_2_1) (and (c_2_0) (v1_1)))
(:derived (c_2_2) (and (c_2_1) (v1_2)))
(:derived (c_2_3) (and (c_2_2) (v1_3)))
(:derived (c_2_4) (and (c_2_3) (v1_4)))
(:derived (c_2_5) (and (c_2_4) (v1_5)))
(:derived (z_2_0) (or (and (not (v1_0)) (not (c_2_-1))) (and (c_2_-1) (v1_0))))
(:derived (z_2_1) (or (and (v1_1) (not (c_2_0))) (and (c_2_0) (not (v1_1)))))
(:derived (z_2_2) (or (and (v1_2) (not (c_2_1))) (and (c_2_1) (not (v1_2)))))
(:derived (z_2_3) (or (and (v1_3) (not (c_2_2))) (and (c_2_2) (not (v1_3)))))
(:derived (z_2_4) (or (and (v1_4) (not (c_2_3))) (and (c_2_3) (not (v1_4)))))
(:derived (z_2_5) (or (and (v1_5) (not (c_2_4))) (and (c_2_4) (not (v1_5)))))
(:derived (c_3_-1) (false))
(:derived (c_3_0) (or (v1_0) (and (c_3_-1) (not (v1_0)))))
(:derived (c_3_1) (or (v1_1) (and (c_3_0) (not (v1_1)))))
(:derived (c_3_2) (or (v1_2) (and (c_3_1) (not (v1_2)))))
(:derived (c_3_3) (or (v1_3) (and (c_3_2) (not (v1_3)))))
(:derived (c_3_4) (or (v1_4) (and (c_3_3) (not (v1_4)))))
(:derived (c_3_5) (or (v1_5) (and (c_3_4) (not (v1_5)))))
(:derived (z_3_0) (or (and (not (v1_0)) (not (c_3_-1))) (and (c_3_-1) (v1_0))))
(:derived (z_3_1) (or (and (not (v1_1)) (not (c_3_0))) (and (c_3_0) (v1_1))))
(:derived (z_3_2) (or (and (not (v1_2)) (not (c_3_1))) (and (c_3_1) (v1_2))))
(:derived (z_3_3) (or (and (not (v1_3)) (not (c_3_2))) (and (c_3_2) (v1_3))))
(:derived (z_3_4) (or (and (not (v1_4)) (not (c_3_3))) (and (c_3_3) (v1_4))))
(:derived (z_3_5) (or (and (not (v1_5)) (not (c_3_4))) (and (c_3_4) (v1_5))))
(:action move_bot1_rooma_roomb
  :parameters ()
  :precondition (and (at-bot bot1 rooma) (not (of)))
  :effect (and (not (at-bot bot1 rooma)) (at-bot bot1 roomb) (increase (total-cost) 3)))
 (:action move_bot1_rooma_roomc
  :parameters ()
  :precondition (and (at-bot bot1 rooma) (not (of)))
  :effect (and (at-bot bot1 roomc) (not (at-bot bot1 rooma)) (increase (total-cost) 3)))
 (:action move_bot1_roomb_rooma
  :parameters ()
  :precondition (and (at-bot bot1 roomb) (not (of)))
  :effect (and (at-bot bot1 rooma) (not (at-bot bot1 roomb)) (increase (total-cost) 3)))
 (:action move_bot1_roomc_rooma
  :parameters ()
  :precondition (and (at-bot bot1 roomc) (not (of)))
  :effect (and (not (at-bot bot1 roomc)) (at-bot bot1 rooma) (increase (total-cost) 3)))
 (:action move_bot2_rooma_roomb
  :parameters ()
  :precondition (and (at-bot bot2 rooma) (not (of)))
  :effect (and (at-bot bot2 roomb) (not (at-bot bot2 rooma)) (increase (total-cost) 3)))
 (:action move_bot2_rooma_roomc
  :parameters ()
  :precondition (and (at-bot bot2 rooma) (not (of)))
  :effect (and (at-bot bot2 roomc) (not (at-bot bot2 rooma)) (increase (total-cost) 3)))
 (:action move_bot2_roomb_rooma
  :parameters ()
  :precondition (and (at-bot bot2 roomb) (not (of)))
  :effect (and (not (at-bot bot2 roomb)) (at-bot bot2 rooma) (increase (total-cost) 3)))
 (:action move_bot2_roomc_rooma
  :parameters ()
  :precondition (and (at-bot bot2 roomc) (not (of)))
  :effect (and (not (at-bot bot2 roomc)) (at-bot bot2 rooma) (increase (total-cost) 3)))
 (:action pick_item4_rooma_left1_bot1
  :parameters ()
  :precondition (and (at item4 rooma) (at-bot bot1 rooma) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (at item4 rooma)) (in-arm item4 left1) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item4_rooma_right1_bot1
  :parameters ()
  :precondition (and (at item4 rooma) (at-bot bot1 rooma) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (not (at item4 rooma)) (in-arm item4 right1) (increase (total-cost) 2)))
 (:action pick_item4_rooma_left2_bot2
  :parameters ()
  :precondition (and (at item4 rooma) (at-bot bot2 rooma) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (at item4 rooma)) (not (free left2)) (in-arm item4 left2) (increase (total-cost) 2)))
 (:action pick_item4_rooma_right2_bot2
  :parameters ()
  :precondition (and (at item4 rooma) (at-bot bot2 rooma) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item4 right2) (not (free right2)) (not (at item4 rooma)) (increase (total-cost) 2)))
 (:action pick_item4_roomb_left1_bot1
  :parameters ()
  :precondition (and (at item4 roomb) (at-bot bot1 roomb) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (at item4 roomb)) (in-arm item4 left1) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item4_roomb_right1_bot1
  :parameters ()
  :precondition (and (at item4 roomb) (at-bot bot1 roomb) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (in-arm item4 right1) (not (at item4 roomb)) (increase (total-cost) 2)))
 (:action pick_item4_roomb_left2_bot2
  :parameters ()
  :precondition (and (at item4 roomb) (at-bot bot2 roomb) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (not (at item4 roomb)) (in-arm item4 left2) (increase (total-cost) 2)))
 (:action pick_item4_roomb_right2_bot2
  :parameters ()
  :precondition (and (at item4 roomb) (at-bot bot2 roomb) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item4 right2) (not (free right2)) (not (at item4 roomb)) (increase (total-cost) 2)))
 (:action pick_item4_roomc_left1_bot1
  :parameters ()
  :precondition (and (at item4 roomc) (at-bot bot1 roomc) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (at item4 roomc)) (in-arm item4 left1) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item4_roomc_right1_bot1
  :parameters ()
  :precondition (and (at item4 roomc) (at-bot bot1 roomc) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (not (at item4 roomc)) (in-arm item4 right1) (increase (total-cost) 2)))
 (:action pick_item4_roomc_left2_bot2
  :parameters ()
  :precondition (and (at item4 roomc) (at-bot bot2 roomc) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (in-arm item4 left2) (not (at item4 roomc)) (increase (total-cost) 2)))
 (:action pick_item4_roomc_right2_bot2
  :parameters ()
  :precondition (and (at item4 roomc) (at-bot bot2 roomc) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item4 right2) (not (at item4 roomc)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item3_rooma_left1_bot1
  :parameters ()
  :precondition (and (at item3 rooma) (at-bot bot1 rooma) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (at item3 rooma)) (not (free left1)) (in-arm item3 left1) (increase (total-cost) 2)))
 (:action pick_item3_rooma_right1_bot1
  :parameters ()
  :precondition (and (at item3 rooma) (at-bot bot1 rooma) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (in-arm item3 right1) (not (at item3 rooma)) (increase (total-cost) 2)))
 (:action pick_item3_rooma_left2_bot2
  :parameters ()
  :precondition (and (at item3 rooma) (at-bot bot2 rooma) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (at item3 rooma)) (not (free left2)) (in-arm item3 left2) (increase (total-cost) 2)))
 (:action pick_item3_rooma_right2_bot2
  :parameters ()
  :precondition (and (at item3 rooma) (at-bot bot2 rooma) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item3 right2) (not (at item3 rooma)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item3_roomb_left1_bot1
  :parameters ()
  :precondition (and (at item3 roomb) (at-bot bot1 roomb) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item3 left1) (not (at item3 roomb)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item3_roomb_right1_bot1
  :parameters ()
  :precondition (and (at item3 roomb) (at-bot bot1 roomb) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (in-arm item3 right1) (not (at item3 roomb)) (increase (total-cost) 2)))
 (:action pick_item3_roomb_left2_bot2
  :parameters ()
  :precondition (and (at item3 roomb) (at-bot bot2 roomb) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (not (at item3 roomb)) (in-arm item3 left2) (increase (total-cost) 2)))
 (:action pick_item3_roomb_right2_bot2
  :parameters ()
  :precondition (and (at item3 roomb) (at-bot bot2 roomb) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item3 right2) (not (at item3 roomb)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item3_roomc_left1_bot1
  :parameters ()
  :precondition (and (at item3 roomc) (at-bot bot1 roomc) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (at item3 roomc)) (in-arm item3 left1) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item3_roomc_right1_bot1
  :parameters ()
  :precondition (and (at item3 roomc) (at-bot bot1 roomc) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (not (free right1)) (in-arm item3 right1) (not (at item3 roomc)) (increase (total-cost) 2)))
 (:action pick_item3_roomc_left2_bot2
  :parameters ()
  :precondition (and (at item3 roomc) (at-bot bot2 roomc) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (at item3 roomc)) (not (free left2)) (in-arm item3 left2) (increase (total-cost) 2)))
 (:action pick_item3_roomc_right2_bot2
  :parameters ()
  :precondition (and (at item3 roomc) (at-bot bot2 roomc) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item3 right2) (not (at item3 roomc)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item2_rooma_left1_bot1
  :parameters ()
  :precondition (and (at item2 rooma) (at-bot bot1 rooma) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 left1) (not (at item2 rooma)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item2_rooma_right1_bot1
  :parameters ()
  :precondition (and (at item2 rooma) (at-bot bot1 rooma) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 right1) (not (at item2 rooma)) (not (free right1)) (increase (total-cost) 2)))
 (:action pick_item2_rooma_left2_bot2
  :parameters ()
  :precondition (and (at item2 rooma) (at-bot bot2 rooma) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (not (at item2 rooma)) (in-arm item2 left2) (increase (total-cost) 2)))
 (:action pick_item2_rooma_right2_bot2
  :parameters ()
  :precondition (and (at item2 rooma) (at-bot bot2 rooma) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item2 right2) (not (at item2 rooma)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item2_roomb_left1_bot1
  :parameters ()
  :precondition (and (at item2 roomb) (at-bot bot1 roomb) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 left1) (not (at item2 roomb)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item2_roomb_right1_bot1
  :parameters ()
  :precondition (and (at item2 roomb) (at-bot bot1 roomb) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 right1) (not (at item2 roomb)) (not (free right1)) (increase (total-cost) 2)))
 (:action pick_item2_roomb_left2_bot2
  :parameters ()
  :precondition (and (at item2 roomb) (at-bot bot2 roomb) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item2 left2) (not (free left2)) (not (at item2 roomb)) (increase (total-cost) 2)))
 (:action pick_item2_roomb_right2_bot2
  :parameters ()
  :precondition (and (at item2 roomb) (at-bot bot2 roomb) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item2 right2) (not (at item2 roomb)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item2_roomc_left1_bot1
  :parameters ()
  :precondition (and (at item2 roomc) (at-bot bot1 roomc) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 left1) (not (at item2 roomc)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item2_roomc_right1_bot1
  :parameters ()
  :precondition (and (at item2 roomc) (at-bot bot1 roomc) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item2 right1) (not (at item2 roomc)) (not (free right1)) (increase (total-cost) 2)))
 (:action pick_item2_roomc_left2_bot2
  :parameters ()
  :precondition (and (at item2 roomc) (at-bot bot2 roomc) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (not (at item2 roomc)) (in-arm item2 left2) (increase (total-cost) 2)))
 (:action pick_item2_roomc_right2_bot2
  :parameters ()
  :precondition (and (at item2 roomc) (at-bot bot2 roomc) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item2 right2) (not (at item2 roomc)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item1_rooma_left1_bot1
  :parameters ()
  :precondition (and (at item1 rooma) (at-bot bot1 rooma) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 left1) (not (at item1 rooma)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item1_rooma_right1_bot1
  :parameters ()
  :precondition (and (at item1 rooma) (at-bot bot1 rooma) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 right1) (not (free right1)) (not (at item1 rooma)) (increase (total-cost) 2)))
 (:action pick_item1_rooma_left2_bot2
  :parameters ()
  :precondition (and (at item1 rooma) (at-bot bot2 rooma) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (in-arm item1 left2) (not (at item1 rooma)) (increase (total-cost) 2)))
 (:action pick_item1_rooma_right2_bot2
  :parameters ()
  :precondition (and (at item1 rooma) (at-bot bot2 rooma) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item1 right2) (not (at item1 rooma)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item1_roomb_left1_bot1
  :parameters ()
  :precondition (and (at item1 roomb) (at-bot bot1 roomb) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 left1) (not (at item1 roomb)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item1_roomb_right1_bot1
  :parameters ()
  :precondition (and (at item1 roomb) (at-bot bot1 roomb) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 right1) (not (free right1)) (not (at item1 roomb)) (increase (total-cost) 2)))
 (:action pick_item1_roomb_left2_bot2
  :parameters ()
  :precondition (and (at item1 roomb) (at-bot bot2 roomb) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (free left2)) (not (at item1 roomb)) (in-arm item1 left2) (increase (total-cost) 2)))
 (:action pick_item1_roomb_right2_bot2
  :parameters ()
  :precondition (and (at item1 roomb) (at-bot bot2 roomb) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item1 right2) (not (at item1 roomb)) (not (free right2)) (increase (total-cost) 2)))
 (:action pick_item1_roomc_left1_bot1
  :parameters ()
  :precondition (and (at item1 roomc) (at-bot bot1 roomc) (free left1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 left1) (not (at item1 roomc)) (not (free left1)) (increase (total-cost) 2)))
 (:action pick_item1_roomc_right1_bot1
  :parameters ()
  :precondition (and (at item1 roomc) (at-bot bot1 roomc) (free right1) (not (v0_5)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (z_1_5) (v0_5)) (when (not (z_1_5)) (not (v0_5))) (when (and (v0_5) (not (z_1_5))) (of)) (in-arm item1 right1) (not (free right1)) (not (at item1 roomc)) (increase (total-cost) 2)))
 (:action pick_item1_roomc_left2_bot2
  :parameters ()
  :precondition (and (at item1 roomc) (at-bot bot2 roomc) (free left2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (not (at item1 roomc)) (not (free left2)) (in-arm item1 left2) (increase (total-cost) 2)))
 (:action pick_item1_roomc_right2_bot2
  :parameters ()
  :precondition (and (at item1 roomc) (at-bot bot2 roomc) (free right2) (not (v1_5)) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (z_3_5) (v1_5)) (when (not (z_3_5)) (not (v1_5))) (when (and (v1_5) (not (z_3_5))) (of)) (in-arm item1 right2) (not (at item1 roomc)) (not (free right2)) (increase (total-cost) 2)))
 (:action drop_item4_rooma_left1_bot1
  :parameters ()
  :precondition (and (in-arm item4 left1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item4 rooma) (free left1) (not (in-arm item4 left1)) (increase (total-cost) 2)))
 (:action drop_item4_rooma_right1_bot1
  :parameters ()
  :precondition (and (in-arm item4 right1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item4 rooma) (not (in-arm item4 right1)) (increase (total-cost) 2)))
 (:action drop_item4_rooma_left2_bot2
  :parameters ()
  :precondition (and (in-arm item4 left2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item4 rooma) (free left2) (not (in-arm item4 left2)) (increase (total-cost) 2)))
 (:action drop_item4_rooma_right2_bot2
  :parameters ()
  :precondition (and (in-arm item4 right2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item4 rooma) (not (in-arm item4 right2)) (free right2) (increase (total-cost) 2)))
 (:action drop_item4_roomb_left1_bot1
  :parameters ()
  :precondition (and (in-arm item4 left1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item4 roomb) (free left1) (not (in-arm item4 left1)) (increase (total-cost) 2)))
 (:action drop_item4_roomb_right1_bot1
  :parameters ()
  :precondition (and (in-arm item4 right1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item4 roomb) (not (in-arm item4 right1)) (increase (total-cost) 2)))
 (:action drop_item4_roomb_left2_bot2
  :parameters ()
  :precondition (and (in-arm item4 left2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item4 roomb) (free left2) (not (in-arm item4 left2)) (increase (total-cost) 2)))
 (:action drop_item4_roomb_right2_bot2
  :parameters ()
  :precondition (and (in-arm item4 right2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free right2) (not (in-arm item4 right2)) (at item4 roomb) (increase (total-cost) 2)))
 (:action drop_item4_roomc_left1_bot1
  :parameters ()
  :precondition (and (in-arm item4 left1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item4 roomc) (free left1) (not (in-arm item4 left1)) (increase (total-cost) 2)))
 (:action drop_item4_roomc_right1_bot1
  :parameters ()
  :precondition (and (in-arm item4 right1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item4 roomc) (not (in-arm item4 right1)) (increase (total-cost) 2)))
 (:action drop_item4_roomc_left2_bot2
  :parameters ()
  :precondition (and (in-arm item4 left2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (not (in-arm item4 left2)) (at item4 roomc) (increase (total-cost) 2)))
 (:action drop_item4_roomc_right2_bot2
  :parameters ()
  :precondition (and (in-arm item4 right2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item4 roomc) (not (in-arm item4 right2)) (free right2) (increase (total-cost) 2)))
 (:action drop_item3_rooma_left1_bot1
  :parameters ()
  :precondition (and (in-arm item3 left1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item3 rooma) (not (in-arm item3 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item3_rooma_right1_bot1
  :parameters ()
  :precondition (and (in-arm item3 right1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item3 rooma) (not (in-arm item3 right1)) (increase (total-cost) 2)))
 (:action drop_item3_rooma_left2_bot2
  :parameters ()
  :precondition (and (in-arm item3 left2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item3 rooma) (not (in-arm item3 left2)) (increase (total-cost) 2)))
 (:action drop_item3_rooma_right2_bot2
  :parameters ()
  :precondition (and (in-arm item3 right2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item3 rooma) (not (in-arm item3 right2)) (free right2) (increase (total-cost) 2)))
 (:action drop_item3_roomb_left1_bot1
  :parameters ()
  :precondition (and (in-arm item3 left1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item3 roomb) (not (in-arm item3 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item3_roomb_right1_bot1
  :parameters ()
  :precondition (and (in-arm item3 right1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item3 roomb) (not (in-arm item3 right1)) (increase (total-cost) 2)))
 (:action drop_item3_roomb_left2_bot2
  :parameters ()
  :precondition (and (in-arm item3 left2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item3 roomb) (not (in-arm item3 left2)) (increase (total-cost) 2)))
 (:action drop_item3_roomb_right2_bot2
  :parameters ()
  :precondition (and (in-arm item3 right2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free right2) (not (in-arm item3 right2)) (at item3 roomb) (increase (total-cost) 2)))
 (:action drop_item3_roomc_left1_bot1
  :parameters ()
  :precondition (and (in-arm item3 left1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item3 roomc) (not (in-arm item3 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item3_roomc_right1_bot1
  :parameters ()
  :precondition (and (in-arm item3 right1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item3 roomc) (not (in-arm item3 right1)) (increase (total-cost) 2)))
 (:action drop_item3_roomc_left2_bot2
  :parameters ()
  :precondition (and (in-arm item3 left2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item3 roomc) (free left2) (not (in-arm item3 left2)) (increase (total-cost) 2)))
 (:action drop_item3_roomc_right2_bot2
  :parameters ()
  :precondition (and (in-arm item3 right2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item3 roomc) (not (in-arm item3 right2)) (free right2) (increase (total-cost) 2)))
 (:action drop_item2_rooma_left1_bot1
  :parameters ()
  :precondition (and (in-arm item2 left1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item2 rooma) (not (in-arm item2 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item2_rooma_right1_bot1
  :parameters ()
  :precondition (and (in-arm item2 right1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (not (in-arm item2 right1)) (at item2 rooma) (increase (total-cost) 2)))
 (:action drop_item2_rooma_left2_bot2
  :parameters ()
  :precondition (and (in-arm item2 left2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item2 rooma) (not (in-arm item2 left2)) (increase (total-cost) 2)))
 (:action drop_item2_rooma_right2_bot2
  :parameters ()
  :precondition (and (in-arm item2 right2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (not (in-arm item2 right2)) (at item2 rooma) (free right2) (increase (total-cost) 2)))
 (:action drop_item2_roomb_left1_bot1
  :parameters ()
  :precondition (and (in-arm item2 left1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (not (in-arm item2 left1)) (at item2 roomb) (free left1) (increase (total-cost) 2)))
 (:action drop_item2_roomb_right1_bot1
  :parameters ()
  :precondition (and (in-arm item2 right1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (not (in-arm item2 right1)) (at item2 roomb) (increase (total-cost) 2)))
 (:action drop_item2_roomb_left2_bot2
  :parameters ()
  :precondition (and (in-arm item2 left2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item2 roomb) (not (in-arm item2 left2)) (increase (total-cost) 2)))
 (:action drop_item2_roomb_right2_bot2
  :parameters ()
  :precondition (and (in-arm item2 right2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (not (in-arm item2 right2)) (free right2) (at item2 roomb) (increase (total-cost) 2)))
 (:action drop_item2_roomc_left1_bot1
  :parameters ()
  :precondition (and (in-arm item2 left1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item2 roomc) (not (in-arm item2 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item2_roomc_right1_bot1
  :parameters ()
  :precondition (and (in-arm item2 right1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item2 roomc) (not (in-arm item2 right1)) (increase (total-cost) 2)))
 (:action drop_item2_roomc_left2_bot2
  :parameters ()
  :precondition (and (in-arm item2 left2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (not (in-arm item2 left2)) (at item2 roomc) (increase (total-cost) 2)))
 (:action drop_item2_roomc_right2_bot2
  :parameters ()
  :precondition (and (in-arm item2 right2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item2 roomc) (free right2) (not (in-arm item2 right2)) (increase (total-cost) 2)))
 (:action drop_item1_rooma_left1_bot1
  :parameters ()
  :precondition (and (in-arm item1 left1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (not (in-arm item1 left1)) (at item1 rooma) (free left1) (increase (total-cost) 2)))
 (:action drop_item1_rooma_right1_bot1
  :parameters ()
  :precondition (and (in-arm item1 right1) (at-bot bot1 rooma) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (not (in-arm item1 right1)) (at item1 rooma) (increase (total-cost) 2)))
 (:action drop_item1_rooma_left2_bot2
  :parameters ()
  :precondition (and (in-arm item1 left2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item1 rooma) (not (in-arm item1 left2)) (increase (total-cost) 2)))
 (:action drop_item1_rooma_right2_bot2
  :parameters ()
  :precondition (and (in-arm item1 right2) (at-bot bot2 rooma) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free right2) (not (in-arm item1 right2)) (at item1 rooma) (increase (total-cost) 2)))
 (:action drop_item1_roomb_left1_bot1
  :parameters ()
  :precondition (and (in-arm item1 left1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (not (in-arm item1 left1)) (at item1 roomb) (free left1) (increase (total-cost) 2)))
 (:action drop_item1_roomb_right1_bot1
  :parameters ()
  :precondition (and (in-arm item1 right1) (at-bot bot1 roomb) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (not (in-arm item1 right1)) (at item1 roomb) (increase (total-cost) 2)))
 (:action drop_item1_roomb_left2_bot2
  :parameters ()
  :precondition (and (in-arm item1 left2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (free left2) (at item1 roomb) (not (in-arm item1 left2)) (increase (total-cost) 2)))
 (:action drop_item1_roomb_right2_bot2
  :parameters ()
  :precondition (and (in-arm item1 right2) (at-bot bot2 roomb) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (not (in-arm item1 right2)) (at item1 roomb) (free right2) (increase (total-cost) 2)))
 (:action drop_item1_roomc_left1_bot1
  :parameters ()
  :precondition (and (in-arm item1 left1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (at item1 roomc) (not (in-arm item1 left1)) (free left1) (increase (total-cost) 2)))
 (:action drop_item1_roomc_right1_bot1
  :parameters ()
  :precondition (and (in-arm item1 right1) (at-bot bot1 roomc) (not (of)))
  :effect (and (when (z_0_0) (v0_0)) (when (not (z_0_0)) (not (v0_0))) (when (z_0_1) (v0_1)) (when (not (z_0_1)) (not (v0_1))) (when (z_0_2) (v0_2)) (when (not (z_0_2)) (not (v0_2))) (when (z_0_3) (v0_3)) (when (not (z_0_3)) (not (v0_3))) (when (z_0_4) (v0_4)) (when (not (z_0_4)) (not (v0_4))) (when (z_0_5) (v0_5)) (when (not (z_0_5)) (not (v0_5))) (when (and (not (v0_5)) (z_0_5)) (of)) (free right1) (at item1 roomc) (not (in-arm item1 right1)) (increase (total-cost) 2)))
 (:action drop_item1_roomc_left2_bot2
  :parameters ()
  :precondition (and (in-arm item1 left2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item1 roomc) (free left2) (not (in-arm item1 left2)) (increase (total-cost) 2)))
 (:action drop_item1_roomc_right2_bot2
  :parameters ()
  :precondition (and (in-arm item1 right2) (at-bot bot2 roomc) (not (of)))
  :effect (and (when (z_2_0) (v1_0)) (when (not (z_2_0)) (not (v1_0))) (when (z_2_1) (v1_1)) (when (not (z_2_1)) (not (v1_1))) (when (z_2_2) (v1_2)) (when (not (z_2_2)) (not (v1_2))) (when (z_2_3) (v1_3)) (when (not (z_2_3)) (not (v1_3))) (when (z_2_4) (v1_4)) (when (not (z_2_4)) (not (v1_4))) (when (z_2_5) (v1_5)) (when (not (z_2_5)) (not (v1_5))) (when (and (not (v1_5)) (z_2_5)) (of)) (at item1 roomc) (free right2) (not (in-arm item1 right2)) (increase (total-cost) 2)))
 (:action totray_item4_left1_bot1
  :parameters ()
  :precondition (and (in-arm item4 left1) (not (of)))
  :effect (and (free left1) (in-tray item4 bot1) (not (in-arm item4 left1)) (increase (total-cost) 1)))
 (:action totray_item4_right1_bot1
  :parameters ()
  :precondition (and (in-arm item4 right1) (not (of)))
  :effect (and (free right1) (not (in-arm item4 right1)) (in-tray item4 bot1) (increase (total-cost) 1)))
 (:action totray_item4_left2_bot2
  :parameters ()
  :precondition (and (in-arm item4 left2) (not (of)))
  :effect (and (in-tray item4 bot2) (free left2) (not (in-arm item4 left2)) (increase (total-cost) 1)))
 (:action totray_item4_right2_bot2
  :parameters ()
  :precondition (and (in-arm item4 right2) (not (of)))
  :effect (and (in-tray item4 bot2) (not (in-arm item4 right2)) (free right2) (increase (total-cost) 1)))
 (:action totray_item3_left1_bot1
  :parameters ()
  :precondition (and (in-arm item3 left1) (not (of)))
  :effect (and (in-tray item3 bot1) (not (in-arm item3 left1)) (free left1) (increase (total-cost) 1)))
 (:action totray_item3_right1_bot1
  :parameters ()
  :precondition (and (in-arm item3 right1) (not (of)))
  :effect (and (free right1) (in-tray item3 bot1) (not (in-arm item3 right1)) (increase (total-cost) 1)))
 (:action totray_item3_left2_bot2
  :parameters ()
  :precondition (and (in-arm item3 left2) (not (of)))
  :effect (and (free left2) (in-tray item3 bot2) (not (in-arm item3 left2)) (increase (total-cost) 1)))
 (:action totray_item3_right2_bot2
  :parameters ()
  :precondition (and (in-arm item3 right2) (not (of)))
  :effect (and (in-tray item3 bot2) (not (in-arm item3 right2)) (free right2) (increase (total-cost) 1)))
 (:action totray_item2_left1_bot1
  :parameters ()
  :precondition (and (in-arm item2 left1) (not (of)))
  :effect (and (in-tray item2 bot1) (not (in-arm item2 left1)) (free left1) (increase (total-cost) 1)))
 (:action totray_item2_right1_bot1
  :parameters ()
  :precondition (and (in-arm item2 right1) (not (of)))
  :effect (and (free right1) (not (in-arm item2 right1)) (in-tray item2 bot1) (increase (total-cost) 1)))
 (:action totray_item2_left2_bot2
  :parameters ()
  :precondition (and (in-arm item2 left2) (not (of)))
  :effect (and (free left2) (in-tray item2 bot2) (not (in-arm item2 left2)) (increase (total-cost) 1)))
 (:action totray_item2_right2_bot2
  :parameters ()
  :precondition (and (in-arm item2 right2) (not (of)))
  :effect (and (not (in-arm item2 right2)) (free right2) (in-tray item2 bot2) (increase (total-cost) 1)))
 (:action totray_item1_left1_bot1
  :parameters ()
  :precondition (and (in-arm item1 left1) (not (of)))
  :effect (and (not (in-arm item1 left1)) (in-tray item1 bot1) (free left1) (increase (total-cost) 1)))
 (:action totray_item1_right1_bot1
  :parameters ()
  :precondition (and (in-arm item1 right1) (not (of)))
  :effect (and (free right1) (not (in-arm item1 right1)) (in-tray item1 bot1) (increase (total-cost) 1)))
 (:action totray_item1_left2_bot2
  :parameters ()
  :precondition (and (in-arm item1 left2) (not (of)))
  :effect (and (free left2) (not (in-arm item1 left2)) (in-tray item1 bot2) (increase (total-cost) 1)))
 (:action totray_item1_right2_bot2
  :parameters ()
  :precondition (and (in-arm item1 right2) (not (of)))
  :effect (and (not (in-arm item1 right2)) (free right2) (in-tray item1 bot2) (increase (total-cost) 1)))
 (:action fromtray_item4_left1_bot1
  :parameters ()
  :precondition (and (in-tray item4 bot1) (free left1) (not (of)))
  :effect (and (not (free left1)) (in-arm item4 left1) (not (in-tray item4 bot1)) (increase (total-cost) 1)))
 (:action fromtray_item4_right1_bot1
  :parameters ()
  :precondition (and (in-tray item4 bot1) (free right1) (not (of)))
  :effect (and (not (free right1)) (in-arm item4 right1) (not (in-tray item4 bot1)) (increase (total-cost) 1)))
 (:action fromtray_item4_left2_bot2
  :parameters ()
  :precondition (and (in-tray item4 bot2) (free left2) (not (of)))
  :effect (and (not (in-tray item4 bot2)) (not (free left2)) (in-arm item4 left2) (increase (total-cost) 1)))
 (:action fromtray_item4_right2_bot2
  :parameters ()
  :precondition (and (in-tray item4 bot2) (free right2) (not (of)))
  :effect (and (not (in-tray item4 bot2)) (in-arm item4 right2) (not (free right2)) (increase (total-cost) 1)))
 (:action fromtray_item3_left1_bot1
  :parameters ()
  :precondition (and (in-tray item3 bot1) (free left1) (not (of)))
  :effect (and (not (in-tray item3 bot1)) (in-arm item3 left1) (not (free left1)) (increase (total-cost) 1)))
 (:action fromtray_item3_right1_bot1
  :parameters ()
  :precondition (and (in-tray item3 bot1) (free right1) (not (of)))
  :effect (and (not (free right1)) (in-arm item3 right1) (not (in-tray item3 bot1)) (increase (total-cost) 1)))
 (:action fromtray_item3_left2_bot2
  :parameters ()
  :precondition (and (in-tray item3 bot2) (free left2) (not (of)))
  :effect (and (not (free left2)) (not (in-tray item3 bot2)) (in-arm item3 left2) (increase (total-cost) 1)))
 (:action fromtray_item3_right2_bot2
  :parameters ()
  :precondition (and (in-tray item3 bot2) (free right2) (not (of)))
  :effect (and (in-arm item3 right2) (not (in-tray item3 bot2)) (not (free right2)) (increase (total-cost) 1)))
 (:action fromtray_item2_left1_bot1
  :parameters ()
  :precondition (and (in-tray item2 bot1) (free left1) (not (of)))
  :effect (and (in-arm item2 left1) (not (in-tray item2 bot1)) (not (free left1)) (increase (total-cost) 1)))
 (:action fromtray_item2_right1_bot1
  :parameters ()
  :precondition (and (in-tray item2 bot1) (free right1) (not (of)))
  :effect (and (not (free right1)) (not (in-tray item2 bot1)) (in-arm item2 right1) (increase (total-cost) 1)))
 (:action fromtray_item2_left2_bot2
  :parameters ()
  :precondition (and (in-tray item2 bot2) (free left2) (not (of)))
  :effect (and (in-arm item2 left2) (not (free left2)) (not (in-tray item2 bot2)) (increase (total-cost) 1)))
 (:action fromtray_item2_right2_bot2
  :parameters ()
  :precondition (and (in-tray item2 bot2) (free right2) (not (of)))
  :effect (and (in-arm item2 right2) (not (free right2)) (not (in-tray item2 bot2)) (increase (total-cost) 1)))
 (:action fromtray_item1_left1_bot1
  :parameters ()
  :precondition (and (in-tray item1 bot1) (free left1) (not (of)))
  :effect (and (in-arm item1 left1) (not (in-tray item1 bot1)) (not (free left1)) (increase (total-cost) 1)))
 (:action fromtray_item1_right1_bot1
  :parameters ()
  :precondition (and (in-tray item1 bot1) (free right1) (not (of)))
  :effect (and (in-arm item1 right1) (not (free right1)) (not (in-tray item1 bot1)) (increase (total-cost) 1)))
 (:action fromtray_item1_left2_bot2
  :parameters ()
  :precondition (and (in-tray item1 bot2) (free left2) (not (of)))
  :effect (and (not (free left2)) (in-arm item1 left2) (not (in-tray item1 bot2)) (increase (total-cost) 1)))
 (:action fromtray_item1_right2_bot2
  :parameters ()
  :precondition (and (in-tray item1 bot2) (free right2) (not (of)))
  :effect (and (in-arm item1 right2) (not (free right2)) (not (in-tray item1 bot2)) (increase (total-cost) 1)))
)
