(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item42 rooma)
              (at item41 rooma)
              (at item40 rooma)
              (at item39 rooma)
              (at item38 roomb)
              (at item37 roomb)
              (at item36 rooma)
              (at item35 rooma)
              (at item34 roomb)
              (at item33 roomb)
              (at item32 roomb)
              (at item31 roomb)
              (at item30 roomb)
              (at item29 rooma)
              (at item28 rooma)
              (at item27 rooma)
              (at item26 rooma)
              (at item25 rooma)
              (at item24 rooma)
              (at item23 rooma)
              (at item22 rooma)
              (at item21 rooma)
              (at item20 roomc)
              (at item19 roomc)
              (at item18 roomc)
              (at item17 roomc)
              (at item16 roomc)
              (at item15 roomc)
              (at item14 roomc)
              (at item13 roomc)
              (at item12 roomc)
              (at item11 roomc)
              (at item10 roomc)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (at-bot bot3 rooma)
              (free left1)
              (free mid1)
              (free right1)
              (free left2)
              (free mid2)
              (free right2)
              (free left3)
              (free mid3)
              (free right3)
              (mount left1 bot1)
              (mount mid1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount mid2 bot2)
              (mount right2 bot2)
              (mount left3 bot3)
              (mount mid3 bot3)
              (mount right3 bot3)
              (door rooma roomb)
              (door roomb roomc)
              (door roomc roomd)
              (door roomd roome)
              (door roome rooma)
              (door rooma roomf)
              (door roomf roomd)
              (weight--item42_2)
              (weight--item41_2)
              (weight--item40_2)
              (weight--item39_2)
              (weight--item38_1)
              (weight--item37_1)
              (weight--item36_1)
              (weight--item35_1)
              (weight--item34_1)
              (weight--item33_1)
              (weight--item32_1)
              (weight--item31_1)
              (weight--item30_1)
              (v0_0)
              (v0_2)
              (weight--item29_1)
              (weight--item28_1)
              (v1_0)
              (v1_2)
              (weight--item27_1)
              (v2_0)
              (v2_2)
              (weight--item26_0)
              (weight--item25_0)
              (weight--item24_0)
              (v3_0)
              (v3_1)
              (v3_2)
              (weight--item23_0)
              (v4_0)
              (v4_1)
              (v4_2)
              (weight--item22_0)
              (v5_0)
              (v5_1)
              (v5_2)
              (weight--item21_0)
              (weight--item20_0)
              (load_limit--bot1_0)
              (load_limit--bot1_3)
              (weight--item19_0)
              (weight--item18_0)
              (load_limit--bot2_0)
              (load_limit--bot2_3)
              (weight--item17_0)
              (weight--item16_0)
              (load_limit--bot3_0)
              (load_limit--bot3_3)
              (weight--item15_0)
              (v6_3)
              (weight--item14_0)
              (v7_3)
              (weight--item13_0)
              (v8_3)
              (weight--item12_0)
              (v9_1)
              (v9_2)
              (weight--item11_0)
              (v10_1)
              (v10_2)
              (weight--item10_0)
              (v11_1)
              (v11_2)
              (weight--item9_0)
              (weight--item9_1)
              (weight--item8_0)
              (weight--item8_1)
              (weight--item7_0)
              (weight--item7_1)
              (weight--item6_0)
              (weight--item6_1)
              (weight--item5_0)
              (weight--item5_1)
              (weight--item4_0)
              (weight--item4_1)
              (weight--item3_0)
              (weight--item3_1)
              (weight--item2_0)
              (weight--item2_1)
              (weight--item1_0)
              (weight--item1_1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item42 roomb)
           (at item41 roomb)
           (at item40 roomb)
           (at item39 roomb)
           (at item38 roomc)
           (at item37 roomc)
           (at item36 roomc)
           (at item35 roomc)
           (at item34 roome)
           (at item33 roome)
           (at item32 roome)
           (at item31 roome)
           (at item30 roome)
           (at item29 roome)
           (at item28 roome)
           (at item27 roome)
           (at item26 roome)
           (at item25 roome)
           (at item24 roomd)
           (at item23 roomd)
           (at item22 roomd)
           (at item21 roomd)
           (at item20 roomd)
           (at item19 roomd)
           (at item18 roomd)
           (at item17 roomd)
           (at item16 roomf)
           (at item15 roomf)
           (at item14 roomf)
           (at item13 roomf)
           (at item12 roomf)
           (at item11 roomf)
           (at item10 roomf)
           (at item9 roomf)
           (at item8 roomb)
           (at item7 roomb)
           (at item6 roomb)
           (at item5 roomb)
           (at item4 roomb)
           (at item3 roomb)
           (at item2 roomb)
           (at item1 roomb)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
