(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door rooma roomc)
              (door roomc rooma)
              (weight--item6_0)
              (weight--item5_0)
              (weight--item4_0)
              (weight--item3_0)
              (weight--item2_0)
              (weight--item1_0)
              (load_limit--bot1_2)
              (load_limit--bot2_2)
              (v0_0)
              (v0_1)
              (v1_0)
              (v1_1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item6 roomb)
           (at item5 roomb)
           (at item4 roomb)
           (at item3 roomb)
           (at item2 roomc)
           (at item1 roomc)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
