(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item32 rooma)
              (at item31 rooma)
              (at item30 rooma)
              (at item29 rooma)
              (at item28 rooma)
              (at item27 rooma)
              (at item26 rooma)
              (at item25 rooma)
              (at item24 rooma)
              (at item23 rooma)
              (at item22 rooma)
              (at item21 rooma)
              (at item20 rooma)
              (at item19 rooma)
              (at item18 rooma)
              (at item17 rooma)
              (at item16 rooma)
              (at item15 rooma)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (at-bot bot3 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (free left3)
              (free right3)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (mount left3 bot3)
              (mount right3 bot3)
              (door rooma roomb)
              (door roomb roomc)
              (door roomc roomd)
              (door roomd roome)
              (door roome rooma)
              (door rooma roomf)
              (door roomf roomd)
              (weight--item32_2)
              (weight--item31_2)
              (weight--item30_2)
              (weight--item29_2)
              (load_limit--bot1_2)
              (load_limit--bot1_4)
              (weight--item28_2)
              (weight--item27_2)
              (load_limit--bot2_2)
              (load_limit--bot2_4)
              (weight--item26_2)
              (weight--item25_2)
              (load_limit--bot3_2)
              (load_limit--bot3_4)
              (weight--item24_0)
              (weight--item24_1)
              (weight--item23_0)
              (weight--item23_1)
              (weight--item22_0)
              (weight--item22_1)
              (weight--item21_0)
              (weight--item21_1)
              (weight--item20_0)
              (weight--item20_1)
              (v0_4)
              (weight--item19_0)
              (weight--item19_1)
              (weight--item18_0)
              (weight--item18_1)
              (v1_4)
              (weight--item17_0)
              (weight--item17_1)
              (v2_4)
              (weight--item16_1)
              (weight--item15_1)
              (weight--item14_1)
              (v3_0)
              (v3_4)
              (weight--item13_1)
              (v4_0)
              (v4_4)
              (weight--item12_1)
              (weight--item11_1)
              (v5_0)
              (v5_4)
              (weight--item10_1)
              (weight--item9_1)
              (v6_1)
              (v6_4)
              (weight--item8_0)
              (weight--item7_0)
              (v7_1)
              (v7_4)
              (weight--item6_0)
              (v8_1)
              (v8_4)
              (weight--item5_0)
              (weight--item4_0)
              (weight--item3_0)
              (v9_0)
              (v9_1)
              (v9_4)
              (weight--item2_0)
              (v10_0)
              (v10_1)
              (v10_4)
              (weight--item1_0)
              (v11_0)
              (v11_1)
              (v11_4)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item32 roome)
           (at item31 roome)
           (at item30 roome)
           (at item29 roome)
           (at item28 roome)
           (at item27 roome)
           (at item26 roome)
           (at item25 roome)
           (at item24 roome)
           (at item23 roome)
           (at item22 roome)
           (at item21 roome)
           (at item20 roome)
           (at item19 roome)
           (at item18 roome)
           (at item17 roome)
           (at item16 roome)
           (at item15 roome)
           (at item14 roome)
           (at item13 roome)
           (at item12 roome)
           (at item11 roome)
           (at item10 roome)
           (at item9 roome)
           (at item8 roome)
           (at item7 roome)
           (at item6 roome)
           (at item5 roome)
           (at item4 roome)
           (at item3 roome)
           (at item2 roome)
           (at item1 roome)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
