(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint1)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint2)
              (visible waypoint3 waypoint0)
              (visible waypoint0 waypoint3)
              (visible waypoint3 waypoint1)
              (visible waypoint1 waypoint3)
              (visible waypoint3 waypoint2)
              (visible waypoint2 waypoint3)
              (at_soil_sample waypoint0)
              (in_sun waypoint0)
              (at_rock_sample waypoint1)
              (at_soil_sample waypoint2)
              (at_rock_sample waypoint2)
              (at_soil_sample waypoint3)
              (at_rock_sample waypoint3)
              (at_lander general waypoint0)
              (channel_free general)
              (in rover0 waypoint3)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_rock_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint3 waypoint0)
              (can_traverse rover0 waypoint0 waypoint3)
              (can_traverse rover0 waypoint3 waypoint1)
              (can_traverse rover0 waypoint1 waypoint3)
              (can_traverse rover0 waypoint1 waypoint2)
              (can_traverse rover0 waypoint2 waypoint1)
              (on_board camera0 rover0)
              (calibration_target camera0 objective1)
              (supports camera0 colour)
              (supports camera0 highres)
              (visible_from objective0 waypoint0)
              (visible_from objective0 waypoint1)
              (visible_from objective0 waypoint2)
              (visible_from objective0 waypoint3)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective1 waypoint2)
              (visible_from objective1 waypoint3)
              (level_v5__49)
              (geq_v5)
              (level_v0__42)
              (geq_v0)
              (level_v6__46)
              (geq_v6)
              (level_v1__30)
              (geq_v1)
              (level_v7__44)
              (geq_v7)
              (level_v2__47)
              (geq_v2)
              (level_energy--rover0__50)
              (geq_energy--rover0)
              (level_v3__45)
              (geq_v3)
              (level_v4__48)
              (geq_v4)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint2)
           (communicated_rock_data waypoint3)
           (communicated_image_data objective1 highres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
