(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint1)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint3)
              (visible waypoint3 waypoint2)
              (visible waypoint3 waypoint1)
              (visible waypoint1 waypoint3)
              (at_rock_sample waypoint1)
              (in_sun waypoint1)
              (at_soil_sample waypoint2)
              (in_sun waypoint2)
              (at_soil_sample waypoint3)
              (at_rock_sample waypoint3)
              (at_lander general waypoint2)
              (channel_free general)
              (in rover0 waypoint3)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint3 waypoint1)
              (can_traverse rover0 waypoint1 waypoint3)
              (in rover1 waypoint2)
              (available rover1)
              (store_of rover1store rover1)
              (empty rover1store)
              (equipped_for_soil_analysis rover1)
              (equipped_for_rock_analysis rover1)
              (equipped_for_imaging rover1)
              (can_traverse rover1 waypoint2 waypoint1)
              (can_traverse rover1 waypoint1 waypoint2)
              (can_traverse rover1 waypoint2 waypoint3)
              (can_traverse rover1 waypoint3 waypoint2)
              (can_traverse rover1 waypoint1 waypoint0)
              (can_traverse rover1 waypoint0 waypoint1)
              (on_board camera0 rover1)
              (calibration_target camera0 objective0)
              (supports camera0 colour)
              (supports camera0 highres)
              (on_board camera1 rover0)
              (calibration_target camera1 objective0)
              (supports camera1 colour)
              (supports camera1 lowres)
              (on_board camera2 rover0)
              (calibration_target camera2 objective1)
              (supports camera2 lowres)
              (visible_from objective0 waypoint0)
              (visible_from objective0 waypoint1)
              (visible_from objective0 waypoint2)
              (visible_from objective0 waypoint3)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective2 waypoint0)
              (visible_from objective2 waypoint1)
              (visible_from objective2 waypoint2)
              (level_v7__48)
              (geq_v7)
              (level_v0__42)
              (geq_v0)
              (level_v14__44)
              (geq_v14)
              (level_v8__48)
              (geq_v8)
              (level_v1__42)
              (geq_v1)
              (level_v9__49)
              (geq_v9)
              (level_v2__30)
              (geq_v2)
              (level_energy--rover0__50)
              (geq_energy--rover0)
              (level_v3__30)
              (geq_v3)
              (level_v10__49)
              (geq_v10)
              (level_v4__47)
              (geq_v4)
              (level_v11__46)
              (geq_v11)
              (level_v5__47)
              (geq_v5)
              (level_v12__46)
              (geq_v12)
              (level_energy--rover1__50)
              (geq_energy--rover1)
              (level_v6__45)
              (geq_v6)
              (level_v13__44)
              (geq_v13)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint3)
           (communicated_rock_data waypoint1)
           (communicated_image_data objective0 highres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
