(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint0 waypoint1)
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint12)
              (visible waypoint12 waypoint0)
              (visible waypoint0 waypoint13)
              (visible waypoint13 waypoint0)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint6)
              (visible waypoint6 waypoint1)
              (visible waypoint1 waypoint11)
              (visible waypoint11 waypoint1)
              (visible waypoint1 waypoint15)
              (visible waypoint15 waypoint1)
              (visible waypoint2 waypoint6)
              (visible waypoint6 waypoint2)
              (visible waypoint2 waypoint9)
              (visible waypoint9 waypoint2)
              (visible waypoint2 waypoint14)
              (visible waypoint14 waypoint2)
              (visible waypoint2 waypoint16)
              (visible waypoint16 waypoint2)
              (visible waypoint2 waypoint18)
              (visible waypoint18 waypoint2)
              (visible waypoint3 waypoint7)
              (visible waypoint7 waypoint3)
              (visible waypoint3 waypoint11)
              (visible waypoint11 waypoint3)
              (visible waypoint3 waypoint13)
              (visible waypoint13 waypoint3)
              (visible waypoint3 waypoint15)
              (visible waypoint15 waypoint3)
              (visible waypoint4 waypoint5)
              (visible waypoint5 waypoint4)
              (visible waypoint4 waypoint9)
              (visible waypoint9 waypoint4)
              (visible waypoint4 waypoint12)
              (visible waypoint12 waypoint4)
              (visible waypoint4 waypoint18)
              (visible waypoint18 waypoint4)
              (visible waypoint5 waypoint6)
              (visible waypoint6 waypoint5)
              (visible waypoint5 waypoint10)
              (visible waypoint10 waypoint5)
              (visible waypoint5 waypoint12)
              (visible waypoint12 waypoint5)
              (visible waypoint5 waypoint14)
              (visible waypoint14 waypoint5)
              (visible waypoint6 waypoint3)
              (visible waypoint3 waypoint6)
              (visible waypoint6 waypoint12)
              (visible waypoint12 waypoint6)
              (visible waypoint6 waypoint13)
              (visible waypoint13 waypoint6)
              (visible waypoint6 waypoint14)
              (visible waypoint14 waypoint6)
              (visible waypoint6 waypoint19)
              (visible waypoint19 waypoint6)
              (visible waypoint7 waypoint1)
              (visible waypoint1 waypoint7)
              (visible waypoint7 waypoint2)
              (visible waypoint2 waypoint7)
              (visible waypoint7 waypoint5)
              (visible waypoint5 waypoint7)
              (visible waypoint7 waypoint9)
              (visible waypoint9 waypoint7)
              (visible waypoint8 waypoint14)
              (visible waypoint14 waypoint8)
              (visible waypoint9 waypoint0)
              (visible waypoint0 waypoint9)
              (visible waypoint9 waypoint3)
              (visible waypoint3 waypoint9)
              (visible waypoint9 waypoint5)
              (visible waypoint5 waypoint9)
              (visible waypoint9 waypoint6)
              (visible waypoint6 waypoint9)
              (visible waypoint9 waypoint8)
              (visible waypoint8 waypoint9)
              (visible waypoint9 waypoint12)
              (visible waypoint12 waypoint9)
              (visible waypoint10 waypoint3)
              (visible waypoint3 waypoint10)
              (visible waypoint10 waypoint7)
              (visible waypoint7 waypoint10)
              (visible waypoint10 waypoint8)
              (visible waypoint8 waypoint10)
              (visible waypoint10 waypoint9)
              (visible waypoint9 waypoint10)
              (visible waypoint10 waypoint16)
              (visible waypoint16 waypoint10)
              (visible waypoint11 waypoint4)
              (visible waypoint4 waypoint11)
              (visible waypoint11 waypoint5)
              (visible waypoint5 waypoint11)
              (visible waypoint11 waypoint7)
              (visible waypoint7 waypoint11)
              (visible waypoint11 waypoint12)
              (visible waypoint12 waypoint11)
              (visible waypoint11 waypoint16)
              (visible waypoint16 waypoint11)
              (visible waypoint12 waypoint1)
              (visible waypoint1 waypoint12)
              (visible waypoint12 waypoint8)
              (visible waypoint8 waypoint12)
              (visible waypoint12 waypoint14)
              (visible waypoint14 waypoint12)
              (visible waypoint12 waypoint19)
              (visible waypoint19 waypoint12)
              (visible waypoint13 waypoint4)
              (visible waypoint4 waypoint13)
              (visible waypoint13 waypoint19)
              (visible waypoint19 waypoint13)
              (visible waypoint14 waypoint9)
              (visible waypoint9 waypoint14)
              (visible waypoint14 waypoint15)
              (visible waypoint15 waypoint14)
              (visible waypoint15 waypoint6)
              (visible waypoint6 waypoint15)
              (visible waypoint16 waypoint0)
              (visible waypoint0 waypoint16)
              (visible waypoint16 waypoint12)
              (visible waypoint12 waypoint16)
              (visible waypoint16 waypoint13)
              (visible waypoint13 waypoint16)
              (visible waypoint17 waypoint0)
              (visible waypoint0 waypoint17)
              (visible waypoint17 waypoint11)
              (visible waypoint11 waypoint17)
              (visible waypoint18 waypoint0)
              (visible waypoint0 waypoint18)
              (visible waypoint18 waypoint9)
              (visible waypoint9 waypoint18)
              (visible waypoint18 waypoint11)
              (visible waypoint11 waypoint18)
              (visible waypoint19 waypoint9)
              (visible waypoint9 waypoint19)
              (visible waypoint19 waypoint14)
              (visible waypoint14 waypoint19)
              (visible waypoint19 waypoint15)
              (visible waypoint15 waypoint19)
              (visible waypoint19 waypoint16)
              (visible waypoint16 waypoint19)
              (visible waypoint19 waypoint17)
              (visible waypoint17 waypoint19)
              (at_soil_sample waypoint0)
              (at_rock_sample waypoint1)
              (at_rock_sample waypoint2)
              (at_soil_sample waypoint3)
              (in_sun waypoint3)
              (at_rock_sample waypoint4)
              (in_sun waypoint4)
              (at_rock_sample waypoint5)
              (at_rock_sample waypoint6)
              (at_rock_sample waypoint7)
              (at_soil_sample waypoint8)
              (at_soil_sample waypoint9)
              (at_rock_sample waypoint9)
              (in_sun waypoint9)
              (at_soil_sample waypoint10)
              (in_sun waypoint10)
              (at_soil_sample waypoint11)
              (at_soil_sample waypoint12)
              (at_rock_sample waypoint12)
              (at_soil_sample waypoint13)
              (at_rock_sample waypoint13)
              (at_soil_sample waypoint14)
              (at_soil_sample waypoint15)
              (in_sun waypoint16)
              (at_soil_sample waypoint17)
              (at_rock_sample waypoint17)
              (at_soil_sample waypoint18)
              (at_rock_sample waypoint18)
              (in_sun waypoint18)
              (at_soil_sample waypoint19)
              (at_lander general waypoint17)
              (channel_free general)
              (in rover0 waypoint2)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_rock_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint2 waypoint0)
              (can_traverse rover0 waypoint0 waypoint2)
              (can_traverse rover0 waypoint2 waypoint6)
              (can_traverse rover0 waypoint6 waypoint2)
              (can_traverse rover0 waypoint2 waypoint7)
              (can_traverse rover0 waypoint7 waypoint2)
              (can_traverse rover0 waypoint2 waypoint9)
              (can_traverse rover0 waypoint9 waypoint2)
              (can_traverse rover0 waypoint2 waypoint14)
              (can_traverse rover0 waypoint14 waypoint2)
              (can_traverse rover0 waypoint2 waypoint18)
              (can_traverse rover0 waypoint18 waypoint2)
              (can_traverse rover0 waypoint0 waypoint12)
              (can_traverse rover0 waypoint12 waypoint0)
              (can_traverse rover0 waypoint0 waypoint13)
              (can_traverse rover0 waypoint13 waypoint0)
              (can_traverse rover0 waypoint6 waypoint1)
              (can_traverse rover0 waypoint1 waypoint6)
              (can_traverse rover0 waypoint6 waypoint15)
              (can_traverse rover0 waypoint15 waypoint6)
              (can_traverse rover0 waypoint6 waypoint19)
              (can_traverse rover0 waypoint19 waypoint6)
              (can_traverse rover0 waypoint7 waypoint3)
              (can_traverse rover0 waypoint3 waypoint7)
              (can_traverse rover0 waypoint7 waypoint11)
              (can_traverse rover0 waypoint11 waypoint7)
              (can_traverse rover0 waypoint9 waypoint4)
              (can_traverse rover0 waypoint4 waypoint9)
              (can_traverse rover0 waypoint9 waypoint5)
              (can_traverse rover0 waypoint5 waypoint9)
              (can_traverse rover0 waypoint9 waypoint8)
              (can_traverse rover0 waypoint8 waypoint9)
              (can_traverse rover0 waypoint13 waypoint16)
              (can_traverse rover0 waypoint16 waypoint13)
              (can_traverse rover0 waypoint5 waypoint10)
              (can_traverse rover0 waypoint10 waypoint5)
              (in rover1 waypoint9)
              (available rover1)
              (store_of rover1store rover1)
              (empty rover1store)
              (equipped_for_rock_analysis rover1)
              (equipped_for_imaging rover1)
              (can_traverse rover1 waypoint9 waypoint0)
              (can_traverse rover1 waypoint0 waypoint9)
              (can_traverse rover1 waypoint9 waypoint3)
              (can_traverse rover1 waypoint3 waypoint9)
              (can_traverse rover1 waypoint9 waypoint4)
              (can_traverse rover1 waypoint4 waypoint9)
              (can_traverse rover1 waypoint9 waypoint7)
              (can_traverse rover1 waypoint7 waypoint9)
              (can_traverse rover1 waypoint9 waypoint10)
              (can_traverse rover1 waypoint10 waypoint9)
              (can_traverse rover1 waypoint9 waypoint12)
              (can_traverse rover1 waypoint12 waypoint9)
              (can_traverse rover1 waypoint9 waypoint14)
              (can_traverse rover1 waypoint14 waypoint9)
              (can_traverse rover1 waypoint9 waypoint18)
              (can_traverse rover1 waypoint18 waypoint9)
              (can_traverse rover1 waypoint9 waypoint19)
              (can_traverse rover1 waypoint19 waypoint9)
              (can_traverse rover1 waypoint0 waypoint2)
              (can_traverse rover1 waypoint2 waypoint0)
              (can_traverse rover1 waypoint0 waypoint13)
              (can_traverse rover1 waypoint13 waypoint0)
              (can_traverse rover1 waypoint0 waypoint16)
              (can_traverse rover1 waypoint16 waypoint0)
              (can_traverse rover1 waypoint3 waypoint6)
              (can_traverse rover1 waypoint6 waypoint3)
              (can_traverse rover1 waypoint4 waypoint11)
              (can_traverse rover1 waypoint11 waypoint4)
              (can_traverse rover1 waypoint7 waypoint5)
              (can_traverse rover1 waypoint5 waypoint7)
              (can_traverse rover1 waypoint10 waypoint8)
              (can_traverse rover1 waypoint8 waypoint10)
              (can_traverse rover1 waypoint12 waypoint1)
              (can_traverse rover1 waypoint1 waypoint12)
              (can_traverse rover1 waypoint14 waypoint15)
              (can_traverse rover1 waypoint15 waypoint14)
              (can_traverse rover1 waypoint19 waypoint17)
              (can_traverse rover1 waypoint17 waypoint19)
              (in rover2 waypoint0)
              (available rover2)
              (store_of rover2store rover2)
              (empty rover2store)
              (equipped_for_soil_analysis rover2)
              (equipped_for_imaging rover2)
              (can_traverse rover2 waypoint0 waypoint1)
              (can_traverse rover2 waypoint1 waypoint0)
              (can_traverse rover2 waypoint0 waypoint9)
              (can_traverse rover2 waypoint9 waypoint0)
              (can_traverse rover2 waypoint0 waypoint13)
              (can_traverse rover2 waypoint13 waypoint0)
              (can_traverse rover2 waypoint0 waypoint16)
              (can_traverse rover2 waypoint16 waypoint0)
              (can_traverse rover2 waypoint0 waypoint17)
              (can_traverse rover2 waypoint17 waypoint0)
              (can_traverse rover2 waypoint0 waypoint18)
              (can_traverse rover2 waypoint18 waypoint0)
              (can_traverse rover2 waypoint1 waypoint2)
              (can_traverse rover2 waypoint2 waypoint1)
              (can_traverse rover2 waypoint1 waypoint6)
              (can_traverse rover2 waypoint6 waypoint1)
              (can_traverse rover2 waypoint1 waypoint11)
              (can_traverse rover2 waypoint11 waypoint1)
              (can_traverse rover2 waypoint1 waypoint12)
              (can_traverse rover2 waypoint12 waypoint1)
              (can_traverse rover2 waypoint1 waypoint15)
              (can_traverse rover2 waypoint15 waypoint1)
              (can_traverse rover2 waypoint9 waypoint3)
              (can_traverse rover2 waypoint3 waypoint9)
              (can_traverse rover2 waypoint9 waypoint4)
              (can_traverse rover2 waypoint4 waypoint9)
              (can_traverse rover2 waypoint9 waypoint5)
              (can_traverse rover2 waypoint5 waypoint9)
              (can_traverse rover2 waypoint9 waypoint7)
              (can_traverse rover2 waypoint7 waypoint9)
              (can_traverse rover2 waypoint9 waypoint10)
              (can_traverse rover2 waypoint10 waypoint9)
              (can_traverse rover2 waypoint9 waypoint14)
              (can_traverse rover2 waypoint14 waypoint9)
              (can_traverse rover2 waypoint9 waypoint19)
              (can_traverse rover2 waypoint19 waypoint9)
              (in rover3 waypoint18)
              (available rover3)
              (store_of rover3store rover3)
              (empty rover3store)
              (equipped_for_rock_analysis rover3)
              (equipped_for_imaging rover3)
              (can_traverse rover3 waypoint18 waypoint0)
              (can_traverse rover3 waypoint0 waypoint18)
              (can_traverse rover3 waypoint18 waypoint4)
              (can_traverse rover3 waypoint4 waypoint18)
              (can_traverse rover3 waypoint18 waypoint11)
              (can_traverse rover3 waypoint11 waypoint18)
              (can_traverse rover3 waypoint0 waypoint1)
              (can_traverse rover3 waypoint1 waypoint0)
              (can_traverse rover3 waypoint0 waypoint2)
              (can_traverse rover3 waypoint2 waypoint0)
              (can_traverse rover3 waypoint0 waypoint9)
              (can_traverse rover3 waypoint9 waypoint0)
              (can_traverse rover3 waypoint0 waypoint12)
              (can_traverse rover3 waypoint12 waypoint0)
              (can_traverse rover3 waypoint0 waypoint17)
              (can_traverse rover3 waypoint17 waypoint0)
              (can_traverse rover3 waypoint11 waypoint16)
              (can_traverse rover3 waypoint16 waypoint11)
              (can_traverse rover3 waypoint1 waypoint6)
              (can_traverse rover3 waypoint6 waypoint1)
              (can_traverse rover3 waypoint1 waypoint7)
              (can_traverse rover3 waypoint7 waypoint1)
              (can_traverse rover3 waypoint1 waypoint15)
              (can_traverse rover3 waypoint15 waypoint1)
              (can_traverse rover3 waypoint2 waypoint14)
              (can_traverse rover3 waypoint14 waypoint2)
              (can_traverse rover3 waypoint9 waypoint3)
              (can_traverse rover3 waypoint3 waypoint9)
              (can_traverse rover3 waypoint9 waypoint5)
              (can_traverse rover3 waypoint5 waypoint9)
              (can_traverse rover3 waypoint9 waypoint8)
              (can_traverse rover3 waypoint8 waypoint9)
              (can_traverse rover3 waypoint12 waypoint19)
              (can_traverse rover3 waypoint19 waypoint12)
              (can_traverse rover3 waypoint16 waypoint13)
              (can_traverse rover3 waypoint13 waypoint16)
              (can_traverse rover3 waypoint7 waypoint10)
              (can_traverse rover3 waypoint10 waypoint7)
              (in rover4 waypoint3)
              (available rover4)
              (store_of rover4store rover4)
              (empty rover4store)
              (equipped_for_soil_analysis rover4)
              (equipped_for_imaging rover4)
              (can_traverse rover4 waypoint3 waypoint6)
              (can_traverse rover4 waypoint6 waypoint3)
              (can_traverse rover4 waypoint3 waypoint7)
              (can_traverse rover4 waypoint7 waypoint3)
              (can_traverse rover4 waypoint3 waypoint9)
              (can_traverse rover4 waypoint9 waypoint3)
              (can_traverse rover4 waypoint3 waypoint10)
              (can_traverse rover4 waypoint10 waypoint3)
              (can_traverse rover4 waypoint3 waypoint11)
              (can_traverse rover4 waypoint11 waypoint3)
              (can_traverse rover4 waypoint3 waypoint13)
              (can_traverse rover4 waypoint13 waypoint3)
              (can_traverse rover4 waypoint3 waypoint15)
              (can_traverse rover4 waypoint15 waypoint3)
              (can_traverse rover4 waypoint6 waypoint5)
              (can_traverse rover4 waypoint5 waypoint6)
              (can_traverse rover4 waypoint6 waypoint12)
              (can_traverse rover4 waypoint12 waypoint6)
              (can_traverse rover4 waypoint6 waypoint14)
              (can_traverse rover4 waypoint14 waypoint6)
              (can_traverse rover4 waypoint9 waypoint0)
              (can_traverse rover4 waypoint0 waypoint9)
              (can_traverse rover4 waypoint9 waypoint4)
              (can_traverse rover4 waypoint4 waypoint9)
              (can_traverse rover4 waypoint9 waypoint8)
              (can_traverse rover4 waypoint8 waypoint9)
              (can_traverse rover4 waypoint9 waypoint19)
              (can_traverse rover4 waypoint19 waypoint9)
              (can_traverse rover4 waypoint10 waypoint16)
              (can_traverse rover4 waypoint16 waypoint10)
              (can_traverse rover4 waypoint11 waypoint17)
              (can_traverse rover4 waypoint17 waypoint11)
              (can_traverse rover4 waypoint11 waypoint18)
              (can_traverse rover4 waypoint18 waypoint11)
              (can_traverse rover4 waypoint15 waypoint1)
              (can_traverse rover4 waypoint1 waypoint15)
              (can_traverse rover4 waypoint14 waypoint2)
              (can_traverse rover4 waypoint2 waypoint14)
              (in rover5 waypoint0)
              (available rover5)
              (store_of rover5store rover5)
              (empty rover5store)
              (equipped_for_rock_analysis rover5)
              (equipped_for_imaging rover5)
              (can_traverse rover5 waypoint0 waypoint1)
              (can_traverse rover5 waypoint1 waypoint0)
              (can_traverse rover5 waypoint0 waypoint12)
              (can_traverse rover5 waypoint12 waypoint0)
              (can_traverse rover5 waypoint0 waypoint13)
              (can_traverse rover5 waypoint13 waypoint0)
              (can_traverse rover5 waypoint0 waypoint17)
              (can_traverse rover5 waypoint17 waypoint0)
              (can_traverse rover5 waypoint0 waypoint18)
              (can_traverse rover5 waypoint18 waypoint0)
              (can_traverse rover5 waypoint1 waypoint2)
              (can_traverse rover5 waypoint2 waypoint1)
              (can_traverse rover5 waypoint1 waypoint6)
              (can_traverse rover5 waypoint6 waypoint1)
              (can_traverse rover5 waypoint1 waypoint7)
              (can_traverse rover5 waypoint7 waypoint1)
              (can_traverse rover5 waypoint1 waypoint11)
              (can_traverse rover5 waypoint11 waypoint1)
              (can_traverse rover5 waypoint1 waypoint15)
              (can_traverse rover5 waypoint15 waypoint1)
              (can_traverse rover5 waypoint12 waypoint4)
              (can_traverse rover5 waypoint4 waypoint12)
              (can_traverse rover5 waypoint12 waypoint5)
              (can_traverse rover5 waypoint5 waypoint12)
              (can_traverse rover5 waypoint12 waypoint8)
              (can_traverse rover5 waypoint8 waypoint12)
              (can_traverse rover5 waypoint12 waypoint9)
              (can_traverse rover5 waypoint9 waypoint12)
              (can_traverse rover5 waypoint12 waypoint14)
              (can_traverse rover5 waypoint14 waypoint12)
              (can_traverse rover5 waypoint12 waypoint19)
              (can_traverse rover5 waypoint19 waypoint12)
              (can_traverse rover5 waypoint13 waypoint16)
              (can_traverse rover5 waypoint16 waypoint13)
              (can_traverse rover5 waypoint7 waypoint3)
              (can_traverse rover5 waypoint3 waypoint7)
              (can_traverse rover5 waypoint7 waypoint10)
              (can_traverse rover5 waypoint10 waypoint7)
              (on_board camera0 rover1)
              (calibration_target camera0 objective4)
              (supports camera0 highres)
              (on_board camera1 rover2)
              (calibration_target camera1 objective6)
              (supports camera1 colour)
              (supports camera1 lowres)
              (on_board camera2 rover4)
              (calibration_target camera2 objective0)
              (supports camera2 colour)
              (supports camera2 highres)
              (on_board camera3 rover3)
              (calibration_target camera3 objective6)
              (supports camera3 colour)
              (on_board camera4 rover3)
              (calibration_target camera4 objective4)
              (supports camera4 highres)
              (supports camera4 lowres)
              (on_board camera5 rover0)
              (calibration_target camera5 objective2)
              (supports camera5 colour)
              (on_board camera6 rover5)
              (calibration_target camera6 objective6)
              (supports camera6 highres)
              (supports camera6 lowres)
              (visible_from objective0 waypoint0)
              (visible_from objective0 waypoint1)
              (visible_from objective0 waypoint2)
              (visible_from objective0 waypoint3)
              (visible_from objective0 waypoint4)
              (visible_from objective0 waypoint5)
              (visible_from objective0 waypoint6)
              (visible_from objective0 waypoint7)
              (visible_from objective0 waypoint8)
              (visible_from objective0 waypoint9)
              (visible_from objective0 waypoint10)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective1 waypoint2)
              (visible_from objective1 waypoint3)
              (visible_from objective1 waypoint4)
              (visible_from objective1 waypoint5)
              (visible_from objective1 waypoint6)
              (visible_from objective1 waypoint7)
              (visible_from objective1 waypoint8)
              (visible_from objective1 waypoint9)
              (visible_from objective1 waypoint10)
              (visible_from objective1 waypoint11)
              (visible_from objective1 waypoint12)
              (visible_from objective2 waypoint0)
              (visible_from objective2 waypoint1)
              (visible_from objective2 waypoint2)
              (visible_from objective2 waypoint3)
              (visible_from objective2 waypoint4)
              (visible_from objective2 waypoint5)
              (visible_from objective2 waypoint6)
              (visible_from objective2 waypoint7)
              (visible_from objective2 waypoint8)
              (visible_from objective2 waypoint9)
              (visible_from objective2 waypoint10)
              (visible_from objective2 waypoint11)
              (visible_from objective2 waypoint12)
              (visible_from objective2 waypoint13)
              (visible_from objective2 waypoint14)
              (visible_from objective3 waypoint0)
              (visible_from objective3 waypoint1)
              (visible_from objective3 waypoint2)
              (visible_from objective3 waypoint3)
              (visible_from objective3 waypoint4)
              (visible_from objective3 waypoint5)
              (visible_from objective3 waypoint6)
              (visible_from objective3 waypoint7)
              (visible_from objective3 waypoint8)
              (visible_from objective3 waypoint9)
              (visible_from objective3 waypoint10)
              (visible_from objective3 waypoint11)
              (visible_from objective3 waypoint12)
              (visible_from objective3 waypoint13)
              (visible_from objective3 waypoint14)
              (visible_from objective3 waypoint15)
              (visible_from objective3 waypoint16)
              (visible_from objective3 waypoint17)
              (visible_from objective3 waypoint18)
              (visible_from objective3 waypoint19)
              (visible_from objective4 waypoint0)
              (visible_from objective4 waypoint1)
              (visible_from objective4 waypoint2)
              (visible_from objective4 waypoint3)
              (visible_from objective4 waypoint4)
              (visible_from objective4 waypoint5)
              (visible_from objective4 waypoint6)
              (visible_from objective4 waypoint7)
              (visible_from objective4 waypoint8)
              (visible_from objective4 waypoint9)
              (visible_from objective4 waypoint10)
              (visible_from objective4 waypoint11)
              (visible_from objective4 waypoint12)
              (visible_from objective4 waypoint13)
              (visible_from objective4 waypoint14)
              (visible_from objective4 waypoint15)
              (visible_from objective5 waypoint0)
              (visible_from objective5 waypoint1)
              (visible_from objective5 waypoint2)
              (visible_from objective6 waypoint0)
              (visible_from objective6 waypoint1)
              (visible_from objective6 waypoint2)
              (visible_from objective6 waypoint3)
              (visible_from objective6 waypoint4)
              (visible_from objective6 waypoint5)
              (visible_from objective6 waypoint6)
              (visible_from objective6 waypoint7)
              (visible_from objective6 waypoint8)
              (visible_from objective6 waypoint9)
              (visible_from objective6 waypoint10)
              (v11_1)
              (v11_2)
              (v11_3)
              (v11_4)
              (v12_0)
              (v12_1)
              (v12_2)
              (v12_3)
              (v12_5)
              (v13_0)
              (v13_1)
              (v13_2)
              (v13_3)
              (v13_5)
              (energy--rover5_1)
              (energy--rover5_4)
              (energy--rover5_5)
              (v14_0)
              (v14_1)
              (v14_2)
              (v14_3)
              (v14_5)
              (v15_0)
              (v15_2)
              (v15_3)
              (v15_5)
              (v16_0)
              (v16_2)
              (v16_3)
              (v16_5)
              (v17_0)
              (v17_2)
              (v17_3)
              (v17_5)
              (v18_0)
              (v18_2)
              (v18_3)
              (v18_5)
              (v19_4)
              (v19_5)
              (energy--rover0_1)
              (energy--rover0_4)
              (energy--rover0_5)
              (v20_4)
              (v20_5)
              (v21_4)
              (v21_5)
              (v22_4)
              (v22_5)
              (energy--rover3_1)
              (energy--rover3_4)
              (energy--rover3_5)
              (v23_4)
              (v23_5)
              (v24_4)
              (v24_5)
              (v25_0)
              (v25_4)
              (v25_5)
              (v26_0)
              (v26_4)
              (v26_5)
              (v27_0)
              (v27_4)
              (v27_5)
              (v28_0)
              (v28_4)
              (v28_5)
              (v29_0)
              (v29_4)
              (v29_5)
              (v30_0)
              (v30_4)
              (v30_5)
              (v31_1)
              (v31_2)
              (v31_3)
              (v31_5)
              (v32_1)
              (v32_2)
              (v32_3)
              (v32_5)
              (energy--rover1_1)
              (energy--rover1_4)
              (energy--rover1_5)
              (v33_1)
              (v33_2)
              (v33_3)
              (v33_5)
              (v34_1)
              (v34_2)
              (v34_3)
              (v34_5)
              (v35_1)
              (v35_2)
              (v35_3)
              (v35_5)
              (v36_1)
              (v36_2)
              (v36_3)
              (v36_5)
              (energy--rover4_1)
              (energy--rover4_4)
              (energy--rover4_5)
              (v0_1)
              (v0_3)
              (v0_5)
              (v37_2)
              (v37_3)
              (v37_5)
              (v1_1)
              (v1_3)
              (v1_5)
              (v38_2)
              (v38_3)
              (v38_5)
              (v2_1)
              (v2_3)
              (v2_5)
              (v39_2)
              (v39_3)
              (v39_5)
              (v3_1)
              (v3_3)
              (v3_5)
              (v40_2)
              (v40_3)
              (v40_5)
              (v4_1)
              (v4_3)
              (v4_5)
              (v41_2)
              (v41_3)
              (v41_5)
              (v5_1)
              (v5_3)
              (v5_5)
              (v42_2)
              (v42_3)
              (v42_5)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_4)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_4)
              (v8_1)
              (v8_2)
              (v8_3)
              (v8_4)
              (v9_1)
              (v9_2)
              (v9_3)
              (v9_4)
              (v10_1)
              (v10_2)
              (v10_3)
              (v10_4)
              (energy--rover2_1)
              (energy--rover2_4)
              (energy--rover2_5)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint14)
           (communicated_soil_data waypoint0)
           (communicated_rock_data waypoint4)
           (communicated_rock_data waypoint7)
           (communicated_rock_data waypoint2)
           (communicated_rock_data waypoint5)
           (communicated_rock_data waypoint6)
           (communicated_image_data objective5 colour)
           (communicated_image_data objective3 lowres)
           (communicated_image_data objective2 colour)
           (communicated_image_data objective4 highres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
