(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint0 waypoint1)
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint3)
              (visible waypoint3 waypoint0)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint3)
              (visible waypoint3 waypoint1)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint3 waypoint2)
              (visible waypoint2 waypoint3)
              (at_rock_sample waypoint0)
              (in_sun waypoint0)
              (at_rock_sample waypoint1)
              (in_sun waypoint1)
              (at_soil_sample waypoint2)
              (at_rock_sample waypoint2)
              (at_lander general waypoint0)
              (channel_free general)
              (in rover0 waypoint1)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_rock_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint1 waypoint0)
              (can_traverse rover0 waypoint0 waypoint1)
              (can_traverse rover0 waypoint1 waypoint3)
              (can_traverse rover0 waypoint3 waypoint1)
              (in rover1 waypoint3)
              (available rover1)
              (store_of rover1store rover1)
              (empty rover1store)
              (equipped_for_soil_analysis rover1)
              (equipped_for_rock_analysis rover1)
              (equipped_for_imaging rover1)
              (can_traverse rover1 waypoint3 waypoint0)
              (can_traverse rover1 waypoint0 waypoint3)
              (can_traverse rover1 waypoint3 waypoint2)
              (can_traverse rover1 waypoint2 waypoint3)
              (can_traverse rover1 waypoint0 waypoint1)
              (can_traverse rover1 waypoint1 waypoint0)
              (on_board camera0 rover0)
              (calibration_target camera0 objective1)
              (supports camera0 lowres)
              (on_board camera1 rover1)
              (calibration_target camera1 objective0)
              (supports camera1 colour)
              (supports camera1 highres)
              (supports camera1 lowres)
              (visible_from objective0 waypoint0)
              (visible_from objective0 waypoint1)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (v3_1)
              (v3_2)
              (v3_3)
              (v3_4)
              (energy--rover1_1)
              (energy--rover1_4)
              (energy--rover1_5)
              (v4_0)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_5)
              (v11_0)
              (v11_4)
              (v11_5)
              (v12_1)
              (v12_2)
              (v12_3)
              (v12_5)
              (v5_0)
              (v5_1)
              (v5_2)
              (v5_3)
              (v5_5)
              (v6_0)
              (v6_2)
              (v6_3)
              (v6_5)
              (v13_1)
              (v13_2)
              (v13_3)
              (v13_5)
              (v14_2)
              (v14_3)
              (v14_5)
              (v7_0)
              (v7_2)
              (v7_3)
              (v7_5)
              (energy--rover0_1)
              (energy--rover0_4)
              (energy--rover0_5)
              (v0_1)
              (v0_3)
              (v0_5)
              (v8_4)
              (v8_5)
              (v15_2)
              (v15_3)
              (v15_5)
              (v1_1)
              (v1_3)
              (v1_5)
              (v9_4)
              (v9_5)
              (v2_1)
              (v2_2)
              (v2_3)
              (v2_4)
              (v10_0)
              (v10_4)
              (v10_5)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint2)
           (communicated_rock_data waypoint0)
           (communicated_image_data objective0 colour)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
