(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint0 waypoint1)
              (visible waypoint1 waypoint0)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint3)
              (visible waypoint3 waypoint1)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint2 waypoint3)
              (visible waypoint3 waypoint2)
              (visible waypoint3 waypoint0)
              (visible waypoint0 waypoint3)
              (at_soil_sample waypoint0)
              (at_rock_sample waypoint0)
              (in_sun waypoint1)
              (in_sun waypoint3)
              (at_lander general waypoint1)
              (channel_free general)
              (in rover0 waypoint0)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_rock_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint0 waypoint1)
              (can_traverse rover0 waypoint1 waypoint0)
              (can_traverse rover0 waypoint0 waypoint2)
              (can_traverse rover0 waypoint2 waypoint0)
              (can_traverse rover0 waypoint0 waypoint3)
              (can_traverse rover0 waypoint3 waypoint0)
              (on_board camera0 rover0)
              (calibration_target camera0 objective0)
              (supports camera0 colour)
              (supports camera0 highres)
              (supports camera0 lowres)
              (on_board camera1 rover0)
              (calibration_target camera1 objective1)
              (supports camera1 highres)
              (visible_from objective0 waypoint0)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective1 waypoint2)
              (v3_0)
              (v3_2)
              (v3_3)
              (v3_5)
              (v4_4)
              (v4_5)
              (v5_0)
              (v5_4)
              (v5_5)
              (energy--rover0_1)
              (energy--rover0_4)
              (energy--rover0_5)
              (v0_1)
              (v0_3)
              (v0_5)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_5)
              (v1_1)
              (v1_2)
              (v1_3)
              (v1_4)
              (v7_2)
              (v7_3)
              (v7_5)
              (v2_0)
              (v2_1)
              (v2_2)
              (v2_3)
              (v2_5)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint0)
           (communicated_rock_data waypoint0)
           (communicated_image_data objective1 lowres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
