(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_dread_ham)
              (craves_sciatica_grapefruit)
              (craves_anger_wurst)
              (craves_loneliness_arugula)
              (craves_hangover_muffin)
              (craves_abrasion_scallop)
              (craves_aesthetics_shrimp)
              (craves_jealousy_bacon)
              (v4_2)
              (locale_muffin_2)
              (v5_0)
              (v5_2)
              (v6_1)
              (locale_scallop_0)
              (locale_scallop_1)
              (locale_cherry_2)
              (locale_arugula_2)
              (locale_bacon_0)
              (locale_ham_1)
              (locale_shrimp_1)
              (locale_scallion_0)
              (v7_0)
              (v7_2)
              (v8_0)
              (v9_0)
              (v10_1)
              (harmony_aesthetics_0)
              (v0_0)
              (v0_2)
              (v1_0)
              (v1_1)
              (v2_1)
              (v3_0)
              (v3_1)
 )
 (:goal (and 
           (craves_sciatica_wurst)
           (not (of))
        )
 )
)
