(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_depression_flounder)
              (craves_abrasion_pork)
              (craves_rest_pork)
              (craves_hangover_rice)
              (v2_2)
              (locale_rice_0)
              (v3_0)
              (v3_1)
              (locale_lamb_0)
              (locale_lamb_1)
              (locale_pork_0)
              (locale_pork_2)
              (locale_pear_1)
              (v4_2)
              (locale_okra_1)
              (locale_okra_2)
              (locale_flounder_2)
              (v5_0)
              (v5_2)
              (v6_0)
              (v6_1)
              (v6_2)
              (harmony_rest_0)
              (harmony_rest_1)
              (v0_1)
              (v1_1)
              (v1_2)
 )
 (:goal (and 
           (craves_abrasion_rice)
           (not (of))
        )
 )
)
