(define (domain compiledproblem-domain)
 (:requirements :strips :negative-preconditions :disjunctive-preconditions :conditional-effects)
 (:predicates 
             (c_0_-1)
             (c_0_0)
             (c_0_1)
             (c_0_2)
             (c_0_3)
             (c_0_4)
             (z_0_0)
             (z_0_1)
             (z_0_2)
             (z_0_3)
             (z_0_4)
             (c_1_-1)
             (c_1_0)
             (c_1_1)
             (c_1_2)
             (c_1_3)
             (c_1_4)
             (z_1_0)
             (z_1_1)
             (z_1_2)
             (z_1_3)
             (z_1_4)
             (c_2_-1)
             (c_2_0)
             (c_2_1)
             (c_2_2)
             (c_2_3)
             (c_2_4)
             (z_2_0)
             (z_2_1)
             (z_2_2)
             (z_2_3)
             (z_2_4)
             (c_3_-1)
             (c_3_0)
             (c_3_1)
             (c_3_2)
             (c_3_3)
             (c_3_4)
             (z_3_0)
             (z_3_1)
             (z_3_2)
             (z_3_3)
             (z_3_4)
             (c_4_-1)
             (c_4_0)
             (c_4_1)
             (c_4_2)
             (c_4_3)
             (c_4_4)
             (z_4_0)
             (z_4_1)
             (z_4_2)
             (z_4_3)
             (z_4_4)
             (c_5_-1)
             (c_5_0)
             (c_5_1)
             (c_5_2)
             (c_5_3)
             (c_5_4)
             (z_5_0)
             (z_5_1)
             (z_5_2)
             (z_5_3)
             (z_5_4)
             (c_6_-1)
             (c_6_0)
             (c_6_1)
             (c_6_2)
             (c_6_3)
             (c_6_4)
             (z_6_0)
             (z_6_1)
             (z_6_2)
             (z_6_3)
             (z_6_4)
             (c_7_-1)
             (c_7_0)
             (c_7_1)
             (c_7_2)
             (c_7_3)
             (c_7_4)
             (z_7_0)
             (z_7_1)
             (z_7_2)
             (z_7_3)
             (z_7_4)
             (c_8_-1)
             (c_8_0)
             (c_8_1)
             (c_8_2)
             (c_8_3)
             (c_8_4)
             (z_8_0)
             (z_8_1)
             (z_8_2)
             (z_8_3)
             (z_8_4)
             (c_9_-1)
             (c_9_0)
             (c_9_1)
             (c_9_2)
             (c_9_3)
             (c_9_4)
             (z_9_0)
             (z_9_1)
             (z_9_2)
             (z_9_3)
             (z_9_4)
             (c_10_-1)
             (c_10_0)
             (c_10_1)
             (c_10_2)
             (c_10_3)
             (c_10_4)
             (z_10_0)
             (z_10_1)
             (z_10_2)
             (z_10_3)
             (z_10_4)
             (c_11_-1)
             (c_11_0)
             (c_11_1)
             (c_11_2)
             (c_11_3)
             (c_11_4)
             (z_11_0)
             (z_11_1)
             (z_11_2)
             (z_11_3)
             (z_11_4)
             (false)
             (v5_0)
             (v5_1)
             (v5_2)
             (v5_3)
             (v5_4)
             (locale_wurst_0)
             (locale_wurst_1)
             (locale_wurst_2)
             (locale_wurst_3)
             (locale_wurst_4)
             (locale_lamb_0)
             (locale_lamb_1)
             (locale_lamb_2)
             (locale_lamb_3)
             (locale_lamb_4)
             (locale_shrimp_0)
             (locale_shrimp_1)
             (locale_shrimp_2)
             (locale_shrimp_3)
             (locale_shrimp_4)
             (harmony_intoxication_0)
             (harmony_intoxication_1)
             (harmony_intoxication_2)
             (harmony_intoxication_3)
             (harmony_intoxication_4)
             (v0_0)
             (v0_1)
             (v0_2)
             (v0_3)
             (v0_4)
             (v1_0)
             (v1_1)
             (v1_2)
             (v1_3)
             (v1_4)
             (locale_broccoli_0)
             (locale_broccoli_1)
             (locale_broccoli_2)
             (locale_broccoli_3)
             (locale_broccoli_4)
             (locale_muffin_0)
             (locale_muffin_1)
             (locale_muffin_2)
             (locale_muffin_3)
             (locale_muffin_4)
             (v2_0)
             (v2_1)
             (v2_2)
             (v2_3)
             (v2_4)
             (v3_0)
             (v3_1)
             (v3_2)
             (v3_3)
             (v3_4)
             (v4_0)
             (v4_1)
             (v4_2)
             (v4_3)
             (v4_4)
             (craves_angina_broccoli)
             (craves_intoxication_lamb)
             (craves_boils_muffin)
             (craves_intoxication_shrimp)
             (craves_grief_shrimp)
             (craves_angina_lamb)
             (craves_intoxication_muffin)
             (craves_intoxication_broccoli)
             (craves_grief_muffin)
             (fears_loneliness_intoxication)
             (craves_grief_broccoli)
             (craves_loneliness_shrimp)
             (fears_anxiety_intoxication)
             (craves_anxiety_wurst)
             (craves_loneliness_muffin)
             (fears_hangover_intoxication)
             (craves_hangover_wurst)
             (craves_loneliness_broccoli)
             (craves_hangover_shrimp)
             (craves_anxiety_muffin)
             (craves_anger_muffin)
             (fears_anger_intoxication)
             (craves_intoxication_wurst)
             (craves_anger_wurst)
             (craves_loneliness_lamb)
             (craves_anxiety_broccoli)
             (craves_boils_broccoli)
             (craves_hangover_muffin)
             (craves_anxiety_shrimp)
             (craves_grief_lamb)
             (craves_anger_shrimp)
             (fears_angina_intoxication)
             (craves_angina_wurst)
             (craves_angina_muffin)
             (craves_loneliness_wurst)
             (craves_anxiety_lamb)
             (craves_hangover_broccoli)
             (craves_anger_lamb)
             (craves_boils_lamb)
             (craves_angina_shrimp)
             (fears_boils_intoxication)
             (craves_boils_wurst)
             (craves_hangover_lamb)
             (craves_anger_broccoli)
             (craves_boils_shrimp)
             (fears_grief_intoxication)
             (craves_grief_wurst)
             (of)
 )
 (:derived (c_0_-1) (false))
(:derived (c_0_0) (or (v5_0) (and (c_0_-1) (not (v5_0)))))
(:derived (c_0_1) (or (v5_1) (and (c_0_0) (not (v5_1)))))
(:derived (c_0_2) (or (v5_2) (and (c_0_1) (not (v5_2)))))
(:derived (c_0_3) (or (v5_3) (and (c_0_2) (not (v5_3)))))
(:derived (c_0_4) (or (v5_4) (and (c_0_3) (not (v5_4)))))
(:derived (z_0_0) (or (and (not (v5_0)) (not (c_0_-1))) (and (c_0_-1) (v5_0))))
(:derived (z_0_1) (or (and (not (v5_1)) (not (c_0_0))) (and (c_0_0) (v5_1))))
(:derived (z_0_2) (or (and (not (v5_2)) (not (c_0_1))) (and (c_0_1) (v5_2))))
(:derived (z_0_3) (or (and (not (v5_3)) (not (c_0_2))) (and (c_0_2) (v5_3))))
(:derived (z_0_4) (or (and (not (v5_4)) (not (c_0_3))) (and (c_0_3) (v5_4))))
(:derived (c_1_-1) (false))
(:derived (c_1_0) (or (v0_0) (and (c_1_-1) (not (v0_0)))))
(:derived (c_1_1) (and (c_1_0) (v0_1)))
(:derived (c_1_2) (and (c_1_1) (v0_2)))
(:derived (c_1_3) (and (c_1_2) (v0_3)))
(:derived (c_1_4) (and (c_1_3) (v0_4)))
(:derived (z_1_0) (or (and (not (v0_0)) (not (c_1_-1))) (and (c_1_-1) (v0_0))))
(:derived (z_1_1) (or (and (v0_1) (not (c_1_0))) (and (c_1_0) (not (v0_1)))))
(:derived (z_1_2) (or (and (v0_2) (not (c_1_1))) (and (c_1_1) (not (v0_2)))))
(:derived (z_1_3) (or (and (v0_3) (not (c_1_2))) (and (c_1_2) (not (v0_3)))))
(:derived (z_1_4) (or (and (v0_4) (not (c_1_3))) (and (c_1_3) (not (v0_4)))))
(:derived (c_2_-1) (false))
(:derived (c_2_0) (or (v3_0) (and (c_2_-1) (not (v3_0)))))
(:derived (c_2_1) (or (v3_1) (and (c_2_0) (not (v3_1)))))
(:derived (c_2_2) (or (v3_2) (and (c_2_1) (not (v3_2)))))
(:derived (c_2_3) (or (v3_3) (and (c_2_2) (not (v3_3)))))
(:derived (c_2_4) (or (v3_4) (and (c_2_3) (not (v3_4)))))
(:derived (z_2_0) (or (and (not (v3_0)) (not (c_2_-1))) (and (c_2_-1) (v3_0))))
(:derived (z_2_1) (or (and (not (v3_1)) (not (c_2_0))) (and (c_2_0) (v3_1))))
(:derived (z_2_2) (or (and (not (v3_2)) (not (c_2_1))) (and (c_2_1) (v3_2))))
(:derived (z_2_3) (or (and (not (v3_3)) (not (c_2_2))) (and (c_2_2) (v3_3))))
(:derived (z_2_4) (or (and (not (v3_4)) (not (c_2_3))) (and (c_2_3) (v3_4))))
(:derived (c_3_-1) (false))
(:derived (c_3_0) (or (v1_0) (and (c_3_-1) (not (v1_0)))))
(:derived (c_3_1) (and (c_3_0) (v1_1)))
(:derived (c_3_2) (and (c_3_1) (v1_2)))
(:derived (c_3_3) (and (c_3_2) (v1_3)))
(:derived (c_3_4) (and (c_3_3) (v1_4)))
(:derived (z_3_0) (or (and (not (v1_0)) (not (c_3_-1))) (and (c_3_-1) (v1_0))))
(:derived (z_3_1) (or (and (v1_1) (not (c_3_0))) (and (c_3_0) (not (v1_1)))))
(:derived (z_3_2) (or (and (v1_2) (not (c_3_1))) (and (c_3_1) (not (v1_2)))))
(:derived (z_3_3) (or (and (v1_3) (not (c_3_2))) (and (c_3_2) (not (v1_3)))))
(:derived (z_3_4) (or (and (v1_4) (not (c_3_3))) (and (c_3_3) (not (v1_4)))))
(:derived (c_4_-1) (false))
(:derived (c_4_0) (or (v0_0) (and (c_4_-1) (not (v0_0)))))
(:derived (c_4_1) (or (v0_1) (and (c_4_0) (not (v0_1)))))
(:derived (c_4_2) (or (v0_2) (and (c_4_1) (not (v0_2)))))
(:derived (c_4_3) (or (v0_3) (and (c_4_2) (not (v0_3)))))
(:derived (c_4_4) (or (v0_4) (and (c_4_3) (not (v0_4)))))
(:derived (z_4_0) (or (and (not (v0_0)) (not (c_4_-1))) (and (c_4_-1) (v0_0))))
(:derived (z_4_1) (or (and (not (v0_1)) (not (c_4_0))) (and (c_4_0) (v0_1))))
(:derived (z_4_2) (or (and (not (v0_2)) (not (c_4_1))) (and (c_4_1) (v0_2))))
(:derived (z_4_3) (or (and (not (v0_3)) (not (c_4_2))) (and (c_4_2) (v0_3))))
(:derived (z_4_4) (or (and (not (v0_4)) (not (c_4_3))) (and (c_4_3) (v0_4))))
(:derived (c_5_-1) (false))
(:derived (c_5_0) (or (v2_0) (and (c_5_-1) (not (v2_0)))))
(:derived (c_5_1) (and (c_5_0) (v2_1)))
(:derived (c_5_2) (and (c_5_1) (v2_2)))
(:derived (c_5_3) (and (c_5_2) (v2_3)))
(:derived (c_5_4) (and (c_5_3) (v2_4)))
(:derived (z_5_0) (or (and (not (v2_0)) (not (c_5_-1))) (and (c_5_-1) (v2_0))))
(:derived (z_5_1) (or (and (v2_1) (not (c_5_0))) (and (c_5_0) (not (v2_1)))))
(:derived (z_5_2) (or (and (v2_2) (not (c_5_1))) (and (c_5_1) (not (v2_2)))))
(:derived (z_5_3) (or (and (v2_3) (not (c_5_2))) (and (c_5_2) (not (v2_3)))))
(:derived (z_5_4) (or (and (v2_4) (not (c_5_3))) (and (c_5_3) (not (v2_4)))))
(:derived (c_6_-1) (false))
(:derived (c_6_0) (or (v2_0) (and (c_6_-1) (not (v2_0)))))
(:derived (c_6_1) (or (v2_1) (and (c_6_0) (not (v2_1)))))
(:derived (c_6_2) (or (v2_2) (and (c_6_1) (not (v2_2)))))
(:derived (c_6_3) (or (v2_3) (and (c_6_2) (not (v2_3)))))
(:derived (c_6_4) (or (v2_4) (and (c_6_3) (not (v2_4)))))
(:derived (z_6_0) (or (and (not (v2_0)) (not (c_6_-1))) (and (c_6_-1) (v2_0))))
(:derived (z_6_1) (or (and (not (v2_1)) (not (c_6_0))) (and (c_6_0) (v2_1))))
(:derived (z_6_2) (or (and (not (v2_2)) (not (c_6_1))) (and (c_6_1) (v2_2))))
(:derived (z_6_3) (or (and (not (v2_3)) (not (c_6_2))) (and (c_6_2) (v2_3))))
(:derived (z_6_4) (or (and (not (v2_4)) (not (c_6_3))) (and (c_6_3) (v2_4))))
(:derived (c_7_-1) (false))
(:derived (c_7_0) (or (v1_0) (and (c_7_-1) (not (v1_0)))))
(:derived (c_7_1) (or (v1_1) (and (c_7_0) (not (v1_1)))))
(:derived (c_7_2) (or (v1_2) (and (c_7_1) (not (v1_2)))))
(:derived (c_7_3) (or (v1_3) (and (c_7_2) (not (v1_3)))))
(:derived (c_7_4) (or (v1_4) (and (c_7_3) (not (v1_4)))))
(:derived (z_7_0) (or (and (not (v1_0)) (not (c_7_-1))) (and (c_7_-1) (v1_0))))
(:derived (z_7_1) (or (and (not (v1_1)) (not (c_7_0))) (and (c_7_0) (v1_1))))
(:derived (z_7_2) (or (and (not (v1_2)) (not (c_7_1))) (and (c_7_1) (v1_2))))
(:derived (z_7_3) (or (and (not (v1_3)) (not (c_7_2))) (and (c_7_2) (v1_3))))
(:derived (z_7_4) (or (and (not (v1_4)) (not (c_7_3))) (and (c_7_3) (v1_4))))
(:derived (c_8_-1) (false))
(:derived (c_8_0) (or (v3_0) (and (c_8_-1) (not (v3_0)))))
(:derived (c_8_1) (and (c_8_0) (v3_1)))
(:derived (c_8_2) (and (c_8_1) (v3_2)))
(:derived (c_8_3) (and (c_8_2) (v3_3)))
(:derived (c_8_4) (and (c_8_3) (v3_4)))
(:derived (z_8_0) (or (and (not (v3_0)) (not (c_8_-1))) (and (c_8_-1) (v3_0))))
(:derived (z_8_1) (or (and (v3_1) (not (c_8_0))) (and (c_8_0) (not (v3_1)))))
(:derived (z_8_2) (or (and (v3_2) (not (c_8_1))) (and (c_8_1) (not (v3_2)))))
(:derived (z_8_3) (or (and (v3_3) (not (c_8_2))) (and (c_8_2) (not (v3_3)))))
(:derived (z_8_4) (or (and (v3_4) (not (c_8_3))) (and (c_8_3) (not (v3_4)))))
(:derived (c_9_-1) (false))
(:derived (c_9_0) (or (v4_0) (and (c_9_-1) (not (v4_0)))))
(:derived (c_9_1) (and (c_9_0) (v4_1)))
(:derived (c_9_2) (and (c_9_1) (v4_2)))
(:derived (c_9_3) (and (c_9_2) (v4_3)))
(:derived (c_9_4) (and (c_9_3) (v4_4)))
(:derived (z_9_0) (or (and (not (v4_0)) (not (c_9_-1))) (and (c_9_-1) (v4_0))))
(:derived (z_9_1) (or (and (v4_1) (not (c_9_0))) (and (c_9_0) (not (v4_1)))))
(:derived (z_9_2) (or (and (v4_2) (not (c_9_1))) (and (c_9_1) (not (v4_2)))))
(:derived (z_9_3) (or (and (v4_3) (not (c_9_2))) (and (c_9_2) (not (v4_3)))))
(:derived (z_9_4) (or (and (v4_4) (not (c_9_3))) (and (c_9_3) (not (v4_4)))))
(:derived (c_10_-1) (false))
(:derived (c_10_0) (or (v5_0) (and (c_10_-1) (not (v5_0)))))
(:derived (c_10_1) (and (c_10_0) (v5_1)))
(:derived (c_10_2) (and (c_10_1) (v5_2)))
(:derived (c_10_3) (and (c_10_2) (v5_3)))
(:derived (c_10_4) (and (c_10_3) (v5_4)))
(:derived (z_10_0) (or (and (not (v5_0)) (not (c_10_-1))) (and (c_10_-1) (v5_0))))
(:derived (z_10_1) (or (and (v5_1) (not (c_10_0))) (and (c_10_0) (not (v5_1)))))
(:derived (z_10_2) (or (and (v5_2) (not (c_10_1))) (and (c_10_1) (not (v5_2)))))
(:derived (z_10_3) (or (and (v5_3) (not (c_10_2))) (and (c_10_2) (not (v5_3)))))
(:derived (z_10_4) (or (and (v5_4) (not (c_10_3))) (and (c_10_3) (not (v5_4)))))
(:derived (c_11_-1) (false))
(:derived (c_11_0) (or (v4_0) (and (c_11_-1) (not (v4_0)))))
(:derived (c_11_1) (or (v4_1) (and (c_11_0) (not (v4_1)))))
(:derived (c_11_2) (or (v4_2) (and (c_11_1) (not (v4_2)))))
(:derived (c_11_3) (or (v4_3) (and (c_11_2) (not (v4_3)))))
(:derived (c_11_4) (or (v4_4) (and (c_11_3) (not (v4_4)))))
(:derived (z_11_0) (or (and (not (v4_0)) (not (c_11_-1))) (and (c_11_-1) (v4_0))))
(:derived (z_11_1) (or (and (not (v4_1)) (not (c_11_0))) (and (c_11_0) (v4_1))))
(:derived (z_11_2) (or (and (not (v4_2)) (not (c_11_1))) (and (c_11_1) (v4_2))))
(:derived (z_11_3) (or (and (not (v4_3)) (not (c_11_2))) (and (c_11_2) (v4_3))))
(:derived (z_11_4) (or (and (not (v4_4)) (not (c_11_3))) (and (c_11_3) (v4_4))))
(:action drink__wurst__lamb
  :parameters ()
  :precondition (and (not (v0_4)) (not (of)))
  :effect (and (when (z_10_0) (v5_0)) (when (not (z_10_0)) (not (v5_0))) (when (z_10_1) (v5_1)) (when (not (z_10_1)) (not (v5_1))) (when (z_10_2) (v5_2)) (when (not (z_10_2)) (not (v5_2))) (when (z_10_3) (v5_3)) (when (not (z_10_3)) (not (v5_3))) (when (z_10_4) (v5_4)) (when (not (z_10_4)) (not (v5_4))) (when (and (not (v5_4)) (z_10_4)) (of)) (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of))))
 (:action drink__wurst__shrimp
  :parameters ()
  :precondition (and (not (v0_4)) (not (of)))
  :effect (and (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of)) (when (z_5_0) (v2_0)) (when (not (z_5_0)) (not (v2_0))) (when (z_5_1) (v2_1)) (when (not (z_5_1)) (not (v2_1))) (when (z_5_2) (v2_2)) (when (not (z_5_2)) (not (v2_2))) (when (z_5_3) (v2_3)) (when (not (z_5_3)) (not (v2_3))) (when (z_5_4) (v2_4)) (when (not (z_5_4)) (not (v2_4))) (when (and (not (v2_4)) (z_5_4)) (of))))
 (:action overcome__loneliness__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (craves_loneliness_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_loneliness_wurst)) (fears_loneliness_intoxication)))
 (:action drink__wurst__broccoli
  :parameters ()
  :precondition (and (not (v0_4)) (not (of)))
  :effect (and (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of)) (when (z_9_0) (v4_0)) (when (not (z_9_0)) (not (v4_0))) (when (z_9_1) (v4_1)) (when (not (z_9_1)) (not (v4_1))) (when (z_9_2) (v4_2)) (when (not (z_9_2)) (not (v4_2))) (when (z_9_3) (v4_3)) (when (not (z_9_3)) (not (v4_3))) (when (z_9_4) (v4_4)) (when (not (z_9_4)) (not (v4_4))) (when (and (not (v4_4)) (z_9_4)) (of))))
 (:action drink__wurst__muffin
  :parameters ()
  :precondition (and (not (v0_4)) (not (of)))
  :effect (and (when (z_8_0) (v3_0)) (when (not (z_8_0)) (not (v3_0))) (when (z_8_1) (v3_1)) (when (not (z_8_1)) (not (v3_1))) (when (z_8_2) (v3_2)) (when (not (z_8_2)) (not (v3_2))) (when (z_8_3) (v3_3)) (when (not (z_8_3)) (not (v3_3))) (when (z_8_4) (v3_4)) (when (not (z_8_4)) (not (v3_4))) (when (and (not (v3_4)) (z_8_4)) (of)) (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of))))
 (:action drink__shrimp__muffin
  :parameters ()
  :precondition (and (not (v2_4)) (not (of)))
  :effect (and (when (z_8_0) (v3_0)) (when (not (z_8_0)) (not (v3_0))) (when (z_8_1) (v3_1)) (when (not (z_8_1)) (not (v3_1))) (when (z_8_2) (v3_2)) (when (not (z_8_2)) (not (v3_2))) (when (z_8_3) (v3_3)) (when (not (z_8_3)) (not (v3_3))) (when (z_8_4) (v3_4)) (when (not (z_8_4)) (not (v3_4))) (when (and (not (v3_4)) (z_8_4)) (of)) (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of))))
 (:action drink__shrimp__lamb
  :parameters ()
  :precondition (and (not (v2_4)) (not (of)))
  :effect (and (when (z_10_0) (v5_0)) (when (not (z_10_0)) (not (v5_0))) (when (z_10_1) (v5_1)) (when (not (z_10_1)) (not (v5_1))) (when (z_10_2) (v5_2)) (when (not (z_10_2)) (not (v5_2))) (when (z_10_3) (v5_3)) (when (not (z_10_3)) (not (v5_3))) (when (z_10_4) (v5_4)) (when (not (z_10_4)) (not (v5_4))) (when (and (not (v5_4)) (z_10_4)) (of)) (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of))))
 (:action drink__shrimp__broccoli
  :parameters ()
  :precondition (and (not (v2_4)) (not (of)))
  :effect (and (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of)) (when (z_9_0) (v4_0)) (when (not (z_9_0)) (not (v4_0))) (when (z_9_1) (v4_1)) (when (not (z_9_1)) (not (v4_1))) (when (z_9_2) (v4_2)) (when (not (z_9_2)) (not (v4_2))) (when (z_9_3) (v4_3)) (when (not (z_9_3)) (not (v4_3))) (when (z_9_4) (v4_4)) (when (not (z_9_4)) (not (v4_4))) (when (and (not (v4_4)) (z_9_4)) (of))))
 (:action drink__shrimp__wurst
  :parameters ()
  :precondition (and (not (v2_4)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (and (not (v0_4)) (z_1_4)) (of)) (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of))))
 (:action drink__muffin__broccoli
  :parameters ()
  :precondition (and (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (when (z_9_0) (v4_0)) (when (not (z_9_0)) (not (v4_0))) (when (z_9_1) (v4_1)) (when (not (z_9_1)) (not (v4_1))) (when (z_9_2) (v4_2)) (when (not (z_9_2)) (not (v4_2))) (when (z_9_3) (v4_3)) (when (not (z_9_3)) (not (v4_3))) (when (z_9_4) (v4_4)) (when (not (z_9_4)) (not (v4_4))) (when (and (not (v4_4)) (z_9_4)) (of))))
 (:action drink__muffin__lamb
  :parameters ()
  :precondition (and (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (when (z_10_0) (v5_0)) (when (not (z_10_0)) (not (v5_0))) (when (z_10_1) (v5_1)) (when (not (z_10_1)) (not (v5_1))) (when (z_10_2) (v5_2)) (when (not (z_10_2)) (not (v5_2))) (when (z_10_3) (v5_3)) (when (not (z_10_3)) (not (v5_3))) (when (z_10_4) (v5_4)) (when (not (z_10_4)) (not (v5_4))) (when (and (not (v5_4)) (z_10_4)) (of))))
 (:action drink__muffin__shrimp
  :parameters ()
  :precondition (and (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (when (z_5_0) (v2_0)) (when (not (z_5_0)) (not (v2_0))) (when (z_5_1) (v2_1)) (when (not (z_5_1)) (not (v2_1))) (when (z_5_2) (v2_2)) (when (not (z_5_2)) (not (v2_2))) (when (z_5_3) (v2_3)) (when (not (z_5_3)) (not (v2_3))) (when (z_5_4) (v2_4)) (when (not (z_5_4)) (not (v2_4))) (when (and (not (v2_4)) (z_5_4)) (of))))
 (:action drink__muffin__wurst
  :parameters ()
  :precondition (and (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (and (not (v0_4)) (z_1_4)) (of))))
 (:action drink__broccoli__lamb
  :parameters ()
  :precondition (and (not (v4_4)) (not (of)))
  :effect (and (when (z_10_0) (v5_0)) (when (not (z_10_0)) (not (v5_0))) (when (z_10_1) (v5_1)) (when (not (z_10_1)) (not (v5_1))) (when (z_10_2) (v5_2)) (when (not (z_10_2)) (not (v5_2))) (when (z_10_3) (v5_3)) (when (not (z_10_3)) (not (v5_3))) (when (z_10_4) (v5_4)) (when (not (z_10_4)) (not (v5_4))) (when (and (not (v5_4)) (z_10_4)) (of)) (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of))))
 (:action drink__broccoli__wurst
  :parameters ()
  :precondition (and (not (v4_4)) (not (of)))
  :effect (and (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (and (not (v0_4)) (z_1_4)) (of)) (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of))))
 (:action drink__broccoli__muffin
  :parameters ()
  :precondition (and (not (v4_4)) (not (of)))
  :effect (and (when (z_8_0) (v3_0)) (when (not (z_8_0)) (not (v3_0))) (when (z_8_1) (v3_1)) (when (not (z_8_1)) (not (v3_1))) (when (z_8_2) (v3_2)) (when (not (z_8_2)) (not (v3_2))) (when (z_8_3) (v3_3)) (when (not (z_8_3)) (not (v3_3))) (when (z_8_4) (v3_4)) (when (not (z_8_4)) (not (v3_4))) (when (and (not (v3_4)) (z_8_4)) (of)) (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of))))
 (:action drink__broccoli__shrimp
  :parameters ()
  :precondition (and (not (v4_4)) (not (of)))
  :effect (and (when (z_5_0) (v2_0)) (when (not (z_5_0)) (not (v2_0))) (when (z_5_1) (v2_1)) (when (not (z_5_1)) (not (v2_1))) (when (z_5_2) (v2_2)) (when (not (z_5_2)) (not (v2_2))) (when (z_5_3) (v2_3)) (when (not (z_5_3)) (not (v2_3))) (when (z_5_4) (v2_4)) (when (not (z_5_4)) (not (v2_4))) (when (and (not (v2_4)) (z_5_4)) (of)) (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of))))
 (:action drink__lamb__shrimp
  :parameters ()
  :precondition (and (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (when (z_5_0) (v2_0)) (when (not (z_5_0)) (not (v2_0))) (when (z_5_1) (v2_1)) (when (not (z_5_1)) (not (v2_1))) (when (z_5_2) (v2_2)) (when (not (z_5_2)) (not (v2_2))) (when (z_5_3) (v2_3)) (when (not (z_5_3)) (not (v2_3))) (when (z_5_4) (v2_4)) (when (not (z_5_4)) (not (v2_4))) (when (and (not (v2_4)) (z_5_4)) (of))))
 (:action drink__lamb__wurst
  :parameters ()
  :precondition (and (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (when (z_1_0) (v0_0)) (when (not (z_1_0)) (not (v0_0))) (when (z_1_1) (v0_1)) (when (not (z_1_1)) (not (v0_1))) (when (z_1_2) (v0_2)) (when (not (z_1_2)) (not (v0_2))) (when (z_1_3) (v0_3)) (when (not (z_1_3)) (not (v0_3))) (when (z_1_4) (v0_4)) (when (not (z_1_4)) (not (v0_4))) (when (and (not (v0_4)) (z_1_4)) (of))))
 (:action drink__lamb__broccoli
  :parameters ()
  :precondition (and (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (when (z_9_0) (v4_0)) (when (not (z_9_0)) (not (v4_0))) (when (z_9_1) (v4_1)) (when (not (z_9_1)) (not (v4_1))) (when (z_9_2) (v4_2)) (when (not (z_9_2)) (not (v4_2))) (when (z_9_3) (v4_3)) (when (not (z_9_3)) (not (v4_3))) (when (z_9_4) (v4_4)) (when (not (z_9_4)) (not (v4_4))) (when (and (not (v4_4)) (z_9_4)) (of))))
 (:action drink__lamb__muffin
  :parameters ()
  :precondition (and (not (v5_4)) (not (of)))
  :effect (and (when (z_8_0) (v3_0)) (when (not (z_8_0)) (not (v3_0))) (when (z_8_1) (v3_1)) (when (not (z_8_1)) (not (v3_1))) (when (z_8_2) (v3_2)) (when (not (z_8_2)) (not (v3_2))) (when (z_8_3) (v3_3)) (when (not (z_8_3)) (not (v3_3))) (when (z_8_4) (v3_4)) (when (not (z_8_4)) (not (v3_4))) (when (and (not (v3_4)) (z_8_4)) (of)) (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of))))
 (:action feast__intoxication__wurst__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (not (v0_4)) (not (of)))
  :effect (and (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of)) (not (craves_intoxication_wurst)) (craves_intoxication_shrimp)))
 (:action feast__intoxication__wurst__lamb
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (not (v0_4)) (not (of)))
  :effect (and (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of)) (not (craves_intoxication_wurst)) (craves_intoxication_lamb)))
 (:action feast__intoxication__wurst__muffin
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (not (v0_4)) (not (of)))
  :effect (and (when (z_4_0) (v0_0)) (when (not (z_4_0)) (not (v0_0))) (when (z_4_1) (v0_1)) (when (not (z_4_1)) (not (v0_1))) (when (z_4_2) (v0_2)) (when (not (z_4_2)) (not (v0_2))) (when (z_4_3) (v0_3)) (when (not (z_4_3)) (not (v0_3))) (when (z_4_4) (v0_4)) (when (not (z_4_4)) (not (v0_4))) (when (and (v0_4) (not (z_4_4))) (of)) (not (craves_intoxication_wurst)) (craves_intoxication_muffin)))
 (:action overcome__angina__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (craves_angina_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_angina_muffin)) (fears_angina_intoxication)))
 (:action feast__intoxication__lamb__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (craves_intoxication_shrimp) (not (craves_intoxication_lamb))))
 (:action feast__intoxication__lamb__wurst
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (craves_intoxication_wurst) (not (craves_intoxication_lamb))))
 (:action feast__intoxication__lamb__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (not (v5_4)) (not (of)))
  :effect (and (when (z_0_0) (v5_0)) (when (not (z_0_0)) (not (v5_0))) (when (z_0_1) (v5_1)) (when (not (z_0_1)) (not (v5_1))) (when (z_0_2) (v5_2)) (when (not (z_0_2)) (not (v5_2))) (when (z_0_3) (v5_3)) (when (not (z_0_3)) (not (v5_3))) (when (z_0_4) (v5_4)) (when (not (z_0_4)) (not (v5_4))) (when (and (v5_4) (not (z_0_4))) (of)) (craves_intoxication_broccoli) (not (craves_intoxication_lamb))))
 (:action overcome__anger__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (craves_anger_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_anger_muffin)) (fears_anger_intoxication)))
 (:action feast__intoxication__shrimp__wurst
  :parameters ()
  :precondition (and (not (v2_4)) (craves_intoxication_shrimp) (not (of)))
  :effect (and (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of)) (craves_intoxication_wurst) (not (craves_intoxication_shrimp))))
 (:action succumb__loneliness__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_loneliness_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_loneliness_wurst) (not (fears_loneliness_intoxication))))
 (:action feast__intoxication__shrimp__lamb
  :parameters ()
  :precondition (and (not (v2_4)) (craves_intoxication_shrimp) (not (of)))
  :effect (and (when (z_6_0) (v2_0)) (when (not (z_6_0)) (not (v2_0))) (when (z_6_1) (v2_1)) (when (not (z_6_1)) (not (v2_1))) (when (z_6_2) (v2_2)) (when (not (z_6_2)) (not (v2_2))) (when (z_6_3) (v2_3)) (when (not (z_6_3)) (not (v2_3))) (when (z_6_4) (v2_4)) (when (not (z_6_4)) (not (v2_4))) (when (and (v2_4) (not (z_6_4))) (of)) (craves_intoxication_lamb) (not (craves_intoxication_shrimp))))
 (:action succumb__loneliness__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (fears_loneliness_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_loneliness_shrimp) (not (fears_loneliness_intoxication))))
 (:action succumb__loneliness__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (fears_loneliness_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_loneliness_muffin) (not (fears_loneliness_intoxication))))
 (:action succumb__loneliness__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_loneliness_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_loneliness_intoxication)) (craves_loneliness_lamb)))
 (:action overcome__grief__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (craves_grief_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_grief_lamb)) (fears_grief_intoxication)))
 (:action overcome__hangover__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (craves_hangover_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_hangover_shrimp)) (fears_hangover_intoxication)))
 (:action overcome__anxiety__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (craves_anxiety_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_anxiety_intoxication) (not (craves_anxiety_shrimp))))
 (:action feast__intoxication__muffin__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (not (craves_intoxication_muffin)) (craves_intoxication_broccoli)))
 (:action feast__intoxication__muffin__wurst
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (not (v3_4)) (not (of)))
  :effect (and (when (z_2_0) (v3_0)) (when (not (z_2_0)) (not (v3_0))) (when (z_2_1) (v3_1)) (when (not (z_2_1)) (not (v3_1))) (when (z_2_2) (v3_2)) (when (not (z_2_2)) (not (v3_2))) (when (z_2_3) (v3_3)) (when (not (z_2_3)) (not (v3_3))) (when (z_2_4) (v3_4)) (when (not (z_2_4)) (not (v3_4))) (when (and (v3_4) (not (z_2_4))) (of)) (not (craves_intoxication_muffin)) (craves_intoxication_wurst)))
 (:action succumb__grief__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (fears_grief_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_grief_intoxication)) (craves_grief_muffin)))
 (:action succumb__grief__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (fears_grief_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_grief_intoxication)) (craves_grief_shrimp)))
 (:action succumb__grief__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_grief_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_grief_lamb) (not (fears_grief_intoxication))))
 (:action succumb__grief__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (fears_grief_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_grief_broccoli) (not (fears_grief_intoxication))))
 (:action succumb__hangover__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_hangover_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_hangover_wurst) (not (fears_hangover_intoxication))))
 (:action succumb__hangover__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (fears_hangover_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_hangover_shrimp) (not (fears_hangover_intoxication))))
 (:action succumb__hangover__intoxication__muffin
  :parameters ()
  :precondition (and (fears_hangover_intoxication) (craves_intoxication_muffin) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_hangover_muffin) (not (fears_hangover_intoxication))))
 (:action succumb__hangover__intoxication__broccoli
  :parameters ()
  :precondition (and (fears_hangover_intoxication) (craves_intoxication_broccoli) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_hangover_intoxication)) (craves_hangover_broccoli)))
 (:action succumb__grief__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_grief_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_grief_wurst) (not (fears_grief_intoxication))))
 (:action succumb__hangover__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_hangover_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_hangover_lamb) (not (fears_hangover_intoxication))))
 (:action overcome__loneliness__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (not (v1_4)) (craves_loneliness_shrimp) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_loneliness_shrimp)) (fears_loneliness_intoxication)))
 (:action overcome__loneliness__intoxication__muffin
  :parameters ()
  :precondition (and (craves_loneliness_muffin) (craves_intoxication_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_loneliness_intoxication) (not (craves_loneliness_muffin))))
 (:action overcome__loneliness__intoxication__lamb
  :parameters ()
  :precondition (and (craves_loneliness_lamb) (craves_intoxication_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_loneliness_lamb)) (fears_loneliness_intoxication)))
 (:action succumb__anger__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_anger_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anger_intoxication)) (craves_anger_lamb)))
 (:action succumb__anger__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_anger_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anger_intoxication)) (craves_anger_wurst)))
 (:action succumb__anger__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (fears_anger_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anger_intoxication)) (craves_anger_shrimp)))
 (:action succumb__anger__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (fears_anger_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anger_intoxication)) (craves_anger_muffin)))
 (:action succumb__anger__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (fears_anger_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anger_intoxication)) (craves_anger_broccoli)))
 (:action succumb__angina__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (fears_angina_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_angina_broccoli) (not (fears_angina_intoxication))))
 (:action succumb__angina__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_angina_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_angina_intoxication)) (craves_angina_lamb)))
 (:action succumb__loneliness__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (fears_loneliness_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_loneliness_broccoli) (not (fears_loneliness_intoxication))))
 (:action succumb__angina__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_angina_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_angina_intoxication)) (craves_angina_wurst)))
 (:action succumb__angina__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (fears_angina_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_angina_shrimp) (not (fears_angina_intoxication))))
 (:action succumb__angina__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (fears_angina_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_angina_muffin) (not (fears_angina_intoxication))))
 (:action feast__intoxication__broccoli__lamb
  :parameters ()
  :precondition (and (not (v4_4)) (craves_intoxication_broccoli) (not (of)))
  :effect (and (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of)) (not (craves_intoxication_broccoli)) (craves_intoxication_lamb)))
 (:action feast__intoxication__broccoli__muffin
  :parameters ()
  :precondition (and (not (v4_4)) (craves_intoxication_broccoli) (not (of)))
  :effect (and (when (z_11_0) (v4_0)) (when (not (z_11_0)) (not (v4_0))) (when (z_11_1) (v4_1)) (when (not (z_11_1)) (not (v4_1))) (when (z_11_2) (v4_2)) (when (not (z_11_2)) (not (v4_2))) (when (z_11_3) (v4_3)) (when (not (z_11_3)) (not (v4_3))) (when (z_11_4) (v4_4)) (when (not (z_11_4)) (not (v4_4))) (when (and (v4_4) (not (z_11_4))) (of)) (not (craves_intoxication_broccoli)) (craves_intoxication_muffin)))
 (:action succumb__anxiety__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_anxiety_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anxiety_intoxication)) (craves_anxiety_wurst)))
 (:action succumb__anxiety__intoxication__shrimp
  :parameters ()
  :precondition (and (fears_anxiety_intoxication) (craves_intoxication_shrimp) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anxiety_intoxication)) (craves_anxiety_shrimp)))
 (:action succumb__anxiety__intoxication__muffin
  :parameters ()
  :precondition (and (fears_anxiety_intoxication) (craves_intoxication_muffin) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (craves_anxiety_muffin) (not (fears_anxiety_intoxication))))
 (:action succumb__anxiety__intoxication__broccoli
  :parameters ()
  :precondition (and (fears_anxiety_intoxication) (craves_intoxication_broccoli) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anxiety_intoxication)) (craves_anxiety_broccoli)))
 (:action succumb__anxiety__intoxication__lamb
  :parameters ()
  :precondition (and (fears_anxiety_intoxication) (craves_intoxication_lamb) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_anxiety_intoxication)) (craves_anxiety_lamb)))
 (:action overcome__boils__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_boils_broccoli) (craves_intoxication_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_boils_broccoli)) (fears_boils_intoxication)))
 (:action overcome__angina__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_angina_broccoli) (craves_intoxication_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_angina_intoxication) (not (craves_angina_broccoli))))
 (:action overcome__angina__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (craves_angina_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_angina_intoxication) (not (craves_angina_lamb))))
 (:action overcome__loneliness__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (craves_loneliness_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_loneliness_intoxication) (not (craves_loneliness_broccoli))))
 (:action overcome__angina__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (craves_angina_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_angina_wurst)) (fears_angina_intoxication)))
 (:action overcome__angina__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_angina_shrimp) (craves_intoxication_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_angina_intoxication) (not (craves_angina_shrimp))))
 (:action overcome__anger__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (not (v1_4)) (craves_anger_lamb) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_anger_lamb)) (fears_anger_intoxication)))
 (:action overcome__anger__intoxication__wurst
  :parameters ()
  :precondition (and (craves_anger_wurst) (craves_intoxication_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_anger_wurst)) (fears_anger_intoxication)))
 (:action overcome__anger__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (craves_anger_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_anger_shrimp)) (fears_anger_intoxication)))
 (:action overcome__anger__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_anger_broccoli) (craves_intoxication_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_anger_broccoli)) (fears_anger_intoxication)))
 (:action overcome__grief__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (craves_grief_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_grief_intoxication) (not (craves_grief_shrimp))))
 (:action overcome__grief__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (craves_grief_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_grief_intoxication) (not (craves_grief_muffin))))
 (:action overcome__grief__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (craves_grief_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_grief_broccoli)) (fears_grief_intoxication)))
 (:action overcome__hangover__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (craves_hangover_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_hangover_wurst)) (fears_hangover_intoxication)))
 (:action overcome__hangover__intoxication__muffin
  :parameters ()
  :precondition (and (craves_hangover_muffin) (craves_intoxication_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_hangover_intoxication) (not (craves_hangover_muffin))))
 (:action overcome__hangover__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_intoxication_broccoli) (not (v1_4)) (craves_hangover_broccoli) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_hangover_broccoli)) (fears_hangover_intoxication)))
 (:action overcome__hangover__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (craves_hangover_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_hangover_lamb)) (fears_hangover_intoxication)))
 (:action overcome__grief__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (not (v1_4)) (craves_grief_wurst) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_grief_wurst)) (fears_grief_intoxication)))
 (:action succumb__boils__intoxication__broccoli
  :parameters ()
  :precondition (and (fears_boils_intoxication) (craves_intoxication_broccoli) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_boils_intoxication)) (craves_boils_broccoli)))
 (:action succumb__boils__intoxication__muffin
  :parameters ()
  :precondition (and (fears_boils_intoxication) (craves_intoxication_muffin) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_boils_intoxication)) (craves_boils_muffin)))
 (:action succumb__boils__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (fears_boils_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_boils_intoxication)) (craves_boils_lamb)))
 (:action succumb__boils__intoxication__shrimp
  :parameters ()
  :precondition (and (fears_boils_intoxication) (craves_intoxication_shrimp) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_boils_intoxication)) (craves_boils_shrimp)))
 (:action succumb__boils__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (fears_boils_intoxication) (not (of)))
  :effect (and (when (z_3_0) (v1_0)) (when (not (z_3_0)) (not (v1_0))) (when (z_3_1) (v1_1)) (when (not (z_3_1)) (not (v1_1))) (when (z_3_2) (v1_2)) (when (not (z_3_2)) (not (v1_2))) (when (z_3_3) (v1_3)) (when (not (z_3_3)) (not (v1_3))) (when (z_3_4) (v1_4)) (when (not (z_3_4)) (not (v1_4))) (when (and (not (v1_4)) (z_3_4)) (of)) (not (fears_boils_intoxication)) (craves_boils_wurst)))
 (:action overcome__anxiety__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (craves_anxiety_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_anxiety_intoxication) (not (craves_anxiety_wurst))))
 (:action overcome__anxiety__intoxication__muffin
  :parameters ()
  :precondition (and (craves_intoxication_muffin) (craves_anxiety_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_anxiety_intoxication) (not (craves_anxiety_muffin))))
 (:action overcome__anxiety__intoxication__broccoli
  :parameters ()
  :precondition (and (craves_anxiety_broccoli) (craves_intoxication_broccoli) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_anxiety_intoxication) (not (craves_anxiety_broccoli))))
 (:action overcome__anxiety__intoxication__lamb
  :parameters ()
  :precondition (and (craves_intoxication_lamb) (craves_anxiety_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (fears_anxiety_intoxication) (not (craves_anxiety_lamb))))
 (:action overcome__boils__intoxication__muffin
  :parameters ()
  :precondition (and (craves_boils_muffin) (craves_intoxication_muffin) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_boils_muffin)) (fears_boils_intoxication)))
 (:action overcome__boils__intoxication__lamb
  :parameters ()
  :precondition (and (craves_boils_lamb) (craves_intoxication_lamb) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_boils_lamb)) (fears_boils_intoxication)))
 (:action overcome__boils__intoxication__wurst
  :parameters ()
  :precondition (and (craves_intoxication_wurst) (craves_boils_wurst) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_boils_wurst)) (fears_boils_intoxication)))
 (:action overcome__boils__intoxication__shrimp
  :parameters ()
  :precondition (and (craves_intoxication_shrimp) (craves_boils_shrimp) (not (v1_4)) (not (of)))
  :effect (and (when (z_7_0) (v1_0)) (when (not (z_7_0)) (not (v1_0))) (when (z_7_1) (v1_1)) (when (not (z_7_1)) (not (v1_1))) (when (z_7_2) (v1_2)) (when (not (z_7_2)) (not (v1_2))) (when (z_7_3) (v1_3)) (when (not (z_7_3)) (not (v1_3))) (when (z_7_4) (v1_4)) (when (not (z_7_4)) (not (v1_4))) (when (and (v1_4) (not (z_7_4))) (of)) (not (craves_boils_shrimp)) (fears_boils_intoxication)))
)
