(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_hangover_shrimp)
              (craves_anger_muffin)
              (craves_intoxication_wurst)
              (craves_boils_broccoli)
              (craves_anxiety_shrimp)
              (craves_grief_lamb)
              (craves_angina_muffin)
              (craves_loneliness_wurst)
              (v5_3)
              (locale_wurst_0)
              (locale_lamb_0)
              (locale_lamb_1)
              (locale_lamb_2)
              (locale_shrimp_1)
              (locale_shrimp_2)
              (harmony_intoxication_1)
              (v0_1)
              (v1_0)
              (v1_1)
              (locale_broccoli_0)
              (locale_broccoli_1)
              (locale_broccoli_2)
              (locale_muffin_1)
              (v2_0)
              (v2_1)
              (v2_2)
              (v3_0)
              (v3_1)
              (v4_3)
 )
 (:goal (and 
           (craves_boils_lamb)
           (craves_anger_lamb)
           (not (of))
        )
 )
)
