(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_angina_chicken)
              (craves_rest_pistachio)
              (craves_expectation_tuna)
              (craves_depression_wurst)
              (v0_0)
              (v0_1)
              (harmony_rest_0)
              (harmony_rest_1)
              (locale_wurst_1)
              (v1_0)
              (v1_1)
              (locale_tuna_1)
              (locale_chicken_1)
              (harmony_expectation_0)
              (locale_pistachio_0)
              (locale_pistachio_2)
              (v2_1)
              (v2_2)
              (v3_0)
              (v3_1)
              (v4_2)
              (v5_1)
 )
 (:goal (and 
           (craves_depression_chicken)
           (not (of))
        )
 )
)
