(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   c0 c1 c2 c3 - counter
 )
 (:init
              (level_v4__0)
              (geq_v4)
              (level_max_int__8)
              (geq_max_int)
              (level_v5__2)
              (geq_v5)
              (level_v6__6)
              (geq_v6)
              (level_v7__0)
              (geq_v7)
              (level_value--c0__1)
              (geq_value--c0)
              (level_value--c1__3)
              (geq_value--c1)
              (level_v8__1)
              (geq_v8)
              (level_value--c2__7)
              (geq_value--c2)
              (level_v0__6)
              (geq_v0)
              (level_value--c3__1)
              (geq_value--c3)
              (level_v1__4)
              (geq_v1)
              (level_v9__3)
              (geq_v9)
              (level_v10__-7)
              (level_v2__0)
              (geq_v2)
              (level_v3__6)
              (geq_v3)
 )
 (:goal (and 
           (geq_v8)
           (geq_v9)
           (geq_v10)
           (not (of))
        )
 )
)
