(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   c0 c1 c2 c3 - counter
 )
 (:init
              (level_v5__-1)
              (level_max_int__8)
              (geq_max_int)
              (level_v6__-1)
              (level_v7__-1)
              (level_value--c0__0)
              (geq_value--c0)
              (level_v8__-1)
              (level_value--c1__0)
              (geq_value--c1)
              (level_v0__7)
              (geq_v0)
              (level_value--c2__0)
              (geq_value--c2)
              (level_v9__-1)
              (level_value--c3__0)
              (geq_value--c3)
              (level_v1__7)
              (geq_v1)
              (level_v10__-1)
              (level_v2__7)
              (geq_v2)
              (level_v3__7)
              (geq_v3)
              (level_v4__-1)
 )
 (:goal (and 
           (geq_v8)
           (geq_v9)
           (geq_v10)
           (not (of))
        )
 )
)
