(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   farm0 farm1 farm2 farm3 - farm
 )
 (:init
              (adj farm0 farm1)
              (adj farm0 farm2)
              (adj farm1 farm0)
              (adj farm1 farm3)
              (adj farm2 farm0)
              (adj farm2 farm3)
              (adj farm3 farm1)
              (adj farm3 farm2)
              (v1_0)
              (v1_2)
              (v1_3)
              (v1_4)
              (v1_5)
              (v1_6)
              (v1_7)
              (v1_8)
              (v1_9)
              (v1_10)
              (v1_11)
              (v1_12)
              (v1_13)
              (v1_14)
              (v8_0)
              (v8_4)
              (v8_7)
              (v8_8)
              (v8_9)
              (v8_12)
              (v8_13)
              (v8_14)
              (v2_2)
              (v2_3)
              (v2_4)
              (v2_5)
              (v2_6)
              (v2_7)
              (v2_8)
              (v2_9)
              (v2_10)
              (v2_11)
              (v2_12)
              (v2_13)
              (v2_14)
              (v3_2)
              (v3_3)
              (v3_4)
              (v3_5)
              (v3_6)
              (v3_7)
              (v3_8)
              (v3_9)
              (v3_10)
              (v3_11)
              (v3_12)
              (v3_13)
              (v3_14)
              (v4_0)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_4)
              (v4_8)
              (v4_9)
              (v0_2)
              (v0_3)
              (v0_4)
              (v0_8)
              (v0_9)
              (v6_0)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_4)
              (v6_5)
              (v6_6)
              (v6_7)
              (v6_8)
              (v6_9)
              (v6_10)
              (v6_11)
              (v6_12)
              (v6_13)
              (v6_14)
              (x--farm0_5)
              (x--farm0_8)
              (x--farm0_9)
              (v7_0)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_4)
              (v7_5)
              (v7_6)
              (v7_7)
              (v7_8)
              (v7_9)
              (v7_10)
              (v7_11)
              (v7_12)
              (v7_13)
              (v7_14)
              (x--farm1_0)
 )
 (:goal (and 
           (not (v4_14))
           (not (v5_14))
           (not (v6_14))
           (not (v7_14))
           (not (v8_14))
           (not (of))
        )
 )
)
