(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint0 waypoint3)
              (visible waypoint3 waypoint0)
              (visible waypoint0 waypoint5)
              (visible waypoint5 waypoint0)
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint1)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint5)
              (visible waypoint5 waypoint2)
              (visible waypoint3 waypoint2)
              (visible waypoint2 waypoint3)
              (visible waypoint4 waypoint0)
              (visible waypoint0 waypoint4)
              (visible waypoint4 waypoint3)
              (visible waypoint3 waypoint4)
              (visible waypoint5 waypoint1)
              (visible waypoint1 waypoint5)
              (visible waypoint5 waypoint4)
              (visible waypoint4 waypoint5)
              (at_soil_sample waypoint1)
              (at_rock_sample waypoint2)
              (in_sun waypoint2)
              (at_rock_sample waypoint3)
              (at_soil_sample waypoint4)
              (at_rock_sample waypoint4)
              (at_rock_sample waypoint5)
              (at_lander general waypoint3)
              (channel_free general)
              (in rover0 waypoint2)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_rock_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint2 waypoint0)
              (can_traverse rover0 waypoint0 waypoint2)
              (can_traverse rover0 waypoint2 waypoint1)
              (can_traverse rover0 waypoint1 waypoint2)
              (can_traverse rover0 waypoint2 waypoint3)
              (can_traverse rover0 waypoint3 waypoint2)
              (can_traverse rover0 waypoint2 waypoint5)
              (can_traverse rover0 waypoint5 waypoint2)
              (can_traverse rover0 waypoint0 waypoint4)
              (can_traverse rover0 waypoint4 waypoint0)
              (in rover1 waypoint3)
              (available rover1)
              (store_of rover1store rover1)
              (empty rover1store)
              (equipped_for_rock_analysis rover1)
              (can_traverse rover1 waypoint3 waypoint0)
              (can_traverse rover1 waypoint0 waypoint3)
              (can_traverse rover1 waypoint3 waypoint2)
              (can_traverse rover1 waypoint2 waypoint3)
              (can_traverse rover1 waypoint3 waypoint4)
              (can_traverse rover1 waypoint4 waypoint3)
              (can_traverse rover1 waypoint0 waypoint1)
              (can_traverse rover1 waypoint1 waypoint0)
              (can_traverse rover1 waypoint0 waypoint5)
              (can_traverse rover1 waypoint5 waypoint0)
              (in rover2 waypoint4)
              (available rover2)
              (store_of rover2store rover2)
              (empty rover2store)
              (equipped_for_soil_analysis rover2)
              (equipped_for_rock_analysis rover2)
              (equipped_for_imaging rover2)
              (can_traverse rover2 waypoint4 waypoint0)
              (can_traverse rover2 waypoint0 waypoint4)
              (can_traverse rover2 waypoint4 waypoint5)
              (can_traverse rover2 waypoint5 waypoint4)
              (can_traverse rover2 waypoint0 waypoint1)
              (can_traverse rover2 waypoint1 waypoint0)
              (can_traverse rover2 waypoint0 waypoint3)
              (can_traverse rover2 waypoint3 waypoint0)
              (can_traverse rover2 waypoint5 waypoint2)
              (can_traverse rover2 waypoint2 waypoint5)
              (on_board camera0 rover0)
              (calibration_target camera0 objective0)
              (supports camera0 colour)
              (supports camera0 highres)
              (on_board camera1 rover2)
              (calibration_target camera1 objective1)
              (supports camera1 highres)
              (visible_from objective0 waypoint0)
              (visible_from objective0 waypoint1)
              (visible_from objective0 waypoint2)
              (visible_from objective0 waypoint3)
              (visible_from objective0 waypoint4)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective1 waypoint2)
              (visible_from objective1 waypoint3)
              (energy--rover0_1)
              (energy--rover0_4)
              (energy--rover0_5)
              (v12_4)
              (v12_5)
              (v13_0)
              (v13_4)
              (v13_5)
              (v14_0)
              (v14_4)
              (v14_5)
              (v15_1)
              (v15_2)
              (v15_3)
              (v15_5)
              (v16_1)
              (v16_2)
              (v16_3)
              (v16_5)
              (energy--rover1_1)
              (energy--rover1_4)
              (energy--rover1_5)
              (v17_1)
              (v17_2)
              (v17_3)
              (v17_5)
              (v18_2)
              (v18_3)
              (v18_5)
              (v19_2)
              (v19_3)
              (v19_5)
              (v20_2)
              (v20_3)
              (v20_5)
              (energy--rover2_1)
              (energy--rover2_4)
              (energy--rover2_5)
              (v0_1)
              (v0_3)
              (v0_5)
              (v1_1)
              (v1_3)
              (v1_5)
              (v2_1)
              (v2_3)
              (v2_5)
              (v3_1)
              (v3_2)
              (v3_3)
              (v3_4)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_4)
              (v5_1)
              (v5_2)
              (v5_3)
              (v5_4)
              (v6_0)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_5)
              (v7_0)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_5)
              (v8_0)
              (v8_2)
              (v8_3)
              (v8_5)
              (v9_0)
              (v9_2)
              (v9_3)
              (v9_5)
              (v10_0)
              (v10_2)
              (v10_3)
              (v10_5)
              (v11_4)
              (v11_5)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint4)
           (communicated_soil_data waypoint1)
           (communicated_rock_data waypoint3)
           (communicated_rock_data waypoint2)
           (communicated_rock_data waypoint4)
           (communicated_image_data objective0 highres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
