(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   general - lander
 )
 (:init
              (visible waypoint0 waypoint1)
              (visible waypoint1 waypoint0)
              (visible waypoint0 waypoint3)
              (visible waypoint3 waypoint0)
              (visible waypoint0 waypoint5)
              (visible waypoint5 waypoint0)
              (visible waypoint0 waypoint6)
              (visible waypoint6 waypoint0)
              (visible waypoint1 waypoint2)
              (visible waypoint2 waypoint1)
              (visible waypoint1 waypoint3)
              (visible waypoint3 waypoint1)
              (visible waypoint1 waypoint4)
              (visible waypoint4 waypoint1)
              (visible waypoint1 waypoint5)
              (visible waypoint5 waypoint1)
              (visible waypoint1 waypoint7)
              (visible waypoint7 waypoint1)
              (visible waypoint1 waypoint8)
              (visible waypoint8 waypoint1)
              (visible waypoint2 waypoint0)
              (visible waypoint0 waypoint2)
              (visible waypoint2 waypoint4)
              (visible waypoint4 waypoint2)
              (visible waypoint2 waypoint6)
              (visible waypoint6 waypoint2)
              (visible waypoint3 waypoint4)
              (visible waypoint4 waypoint3)
              (visible waypoint3 waypoint7)
              (visible waypoint7 waypoint3)
              (visible waypoint4 waypoint0)
              (visible waypoint0 waypoint4)
              (visible waypoint5 waypoint2)
              (visible waypoint2 waypoint5)
              (visible waypoint5 waypoint3)
              (visible waypoint3 waypoint5)
              (visible waypoint7 waypoint0)
              (visible waypoint0 waypoint7)
              (visible waypoint7 waypoint2)
              (visible waypoint2 waypoint7)
              (visible waypoint7 waypoint6)
              (visible waypoint6 waypoint7)
              (visible waypoint8 waypoint2)
              (visible waypoint2 waypoint8)
              (visible waypoint8 waypoint3)
              (visible waypoint3 waypoint8)
              (visible waypoint8 waypoint4)
              (visible waypoint4 waypoint8)
              (visible waypoint8 waypoint7)
              (visible waypoint7 waypoint8)
              (at_rock_sample waypoint0)
              (at_rock_sample waypoint1)
              (at_soil_sample waypoint2)
              (at_rock_sample waypoint2)
              (in_sun waypoint3)
              (at_soil_sample waypoint4)
              (at_rock_sample waypoint4)
              (at_soil_sample waypoint5)
              (at_rock_sample waypoint6)
              (at_soil_sample waypoint7)
              (at_rock_sample waypoint7)
              (in_sun waypoint7)
              (at_rock_sample waypoint8)
              (at_lander general waypoint2)
              (channel_free general)
              (in rover0 waypoint7)
              (available rover0)
              (store_of rover0store rover0)
              (empty rover0store)
              (equipped_for_soil_analysis rover0)
              (equipped_for_imaging rover0)
              (can_traverse rover0 waypoint7 waypoint0)
              (can_traverse rover0 waypoint0 waypoint7)
              (can_traverse rover0 waypoint7 waypoint1)
              (can_traverse rover0 waypoint1 waypoint7)
              (can_traverse rover0 waypoint7 waypoint2)
              (can_traverse rover0 waypoint2 waypoint7)
              (can_traverse rover0 waypoint7 waypoint8)
              (can_traverse rover0 waypoint8 waypoint7)
              (can_traverse rover0 waypoint0 waypoint6)
              (can_traverse rover0 waypoint6 waypoint0)
              (can_traverse rover0 waypoint1 waypoint3)
              (can_traverse rover0 waypoint3 waypoint1)
              (can_traverse rover0 waypoint1 waypoint5)
              (can_traverse rover0 waypoint5 waypoint1)
              (can_traverse rover0 waypoint2 waypoint4)
              (can_traverse rover0 waypoint4 waypoint2)
              (in rover1 waypoint6)
              (available rover1)
              (store_of rover1store rover1)
              (empty rover1store)
              (equipped_for_soil_analysis rover1)
              (equipped_for_imaging rover1)
              (can_traverse rover1 waypoint6 waypoint0)
              (can_traverse rover1 waypoint0 waypoint6)
              (can_traverse rover1 waypoint0 waypoint2)
              (can_traverse rover1 waypoint2 waypoint0)
              (can_traverse rover1 waypoint0 waypoint3)
              (can_traverse rover1 waypoint3 waypoint0)
              (can_traverse rover1 waypoint0 waypoint7)
              (can_traverse rover1 waypoint7 waypoint0)
              (can_traverse rover1 waypoint2 waypoint4)
              (can_traverse rover1 waypoint4 waypoint2)
              (can_traverse rover1 waypoint2 waypoint8)
              (can_traverse rover1 waypoint8 waypoint2)
              (can_traverse rover1 waypoint3 waypoint1)
              (can_traverse rover1 waypoint1 waypoint3)
              (in rover2 waypoint6)
              (available rover2)
              (store_of rover2store rover2)
              (empty rover2store)
              (equipped_for_soil_analysis rover2)
              (equipped_for_rock_analysis rover2)
              (equipped_for_imaging rover2)
              (can_traverse rover2 waypoint6 waypoint0)
              (can_traverse rover2 waypoint0 waypoint6)
              (can_traverse rover2 waypoint6 waypoint2)
              (can_traverse rover2 waypoint2 waypoint6)
              (can_traverse rover2 waypoint6 waypoint7)
              (can_traverse rover2 waypoint7 waypoint6)
              (can_traverse rover2 waypoint0 waypoint1)
              (can_traverse rover2 waypoint1 waypoint0)
              (can_traverse rover2 waypoint0 waypoint3)
              (can_traverse rover2 waypoint3 waypoint0)
              (can_traverse rover2 waypoint0 waypoint4)
              (can_traverse rover2 waypoint4 waypoint0)
              (can_traverse rover2 waypoint0 waypoint5)
              (can_traverse rover2 waypoint5 waypoint0)
              (can_traverse rover2 waypoint2 waypoint8)
              (can_traverse rover2 waypoint8 waypoint2)
              (in rover3 waypoint3)
              (available rover3)
              (store_of rover3store rover3)
              (empty rover3store)
              (equipped_for_soil_analysis rover3)
              (equipped_for_rock_analysis rover3)
              (equipped_for_imaging rover3)
              (can_traverse rover3 waypoint3 waypoint0)
              (can_traverse rover3 waypoint0 waypoint3)
              (can_traverse rover3 waypoint3 waypoint1)
              (can_traverse rover3 waypoint1 waypoint3)
              (can_traverse rover3 waypoint3 waypoint5)
              (can_traverse rover3 waypoint5 waypoint3)
              (can_traverse rover3 waypoint3 waypoint7)
              (can_traverse rover3 waypoint7 waypoint3)
              (can_traverse rover3 waypoint3 waypoint8)
              (can_traverse rover3 waypoint8 waypoint3)
              (can_traverse rover3 waypoint0 waypoint4)
              (can_traverse rover3 waypoint4 waypoint0)
              (can_traverse rover3 waypoint0 waypoint6)
              (can_traverse rover3 waypoint6 waypoint0)
              (can_traverse rover3 waypoint1 waypoint2)
              (can_traverse rover3 waypoint2 waypoint1)
              (on_board camera0 rover2)
              (calibration_target camera0 objective1)
              (supports camera0 colour)
              (supports camera0 highres)
              (on_board camera1 rover2)
              (calibration_target camera1 objective1)
              (supports camera1 colour)
              (supports camera1 lowres)
              (on_board camera2 rover3)
              (calibration_target camera2 objective1)
              (supports camera2 highres)
              (on_board camera3 rover1)
              (calibration_target camera3 objective2)
              (supports camera3 colour)
              (supports camera3 lowres)
              (on_board camera4 rover0)
              (calibration_target camera4 objective1)
              (supports camera4 highres)
              (supports camera4 lowres)
              (visible_from objective0 waypoint0)
              (visible_from objective1 waypoint0)
              (visible_from objective1 waypoint1)
              (visible_from objective1 waypoint2)
              (visible_from objective1 waypoint3)
              (visible_from objective1 waypoint4)
              (visible_from objective1 waypoint5)
              (visible_from objective1 waypoint6)
              (visible_from objective1 waypoint7)
              (visible_from objective2 waypoint0)
              (visible_from objective2 waypoint1)
              (visible_from objective2 waypoint2)
              (visible_from objective2 waypoint3)
              (visible_from objective2 waypoint4)
              (visible_from objective2 waypoint5)
              (visible_from objective3 waypoint0)
              (visible_from objective3 waypoint1)
              (visible_from objective3 waypoint2)
              (visible_from objective3 waypoint3)
              (visible_from objective3 waypoint4)
              (visible_from objective3 waypoint5)
              (visible_from objective3 waypoint6)
              (visible_from objective3 waypoint7)
              (v16_4)
              (v16_5)
              (v17_4)
              (v17_5)
              (v18_0)
              (v18_4)
              (v18_5)
              (v19_0)
              (v19_4)
              (v19_5)
              (v20_0)
              (v20_4)
              (v20_5)
              (v21_0)
              (v21_4)
              (v21_5)
              (v22_1)
              (v22_2)
              (v22_3)
              (v22_5)
              (v23_1)
              (v23_2)
              (v23_3)
              (v23_5)
              (v24_1)
              (v24_2)
              (v24_3)
              (v24_5)
              (v25_1)
              (v25_2)
              (v25_3)
              (v25_5)
              (energy--rover0_1)
              (energy--rover0_4)
              (energy--rover0_5)
              (v26_2)
              (v26_3)
              (v26_5)
              (v27_2)
              (v27_3)
              (v27_5)
              (v28_2)
              (v28_3)
              (v28_5)
              (v29_2)
              (v29_3)
              (v29_5)
              (energy--rover1_1)
              (energy--rover1_4)
              (energy--rover1_5)
              (v0_1)
              (v0_3)
              (v0_5)
              (v1_1)
              (v1_3)
              (v1_5)
              (v2_1)
              (v2_3)
              (v2_5)
              (v3_1)
              (v3_3)
              (v3_5)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_4)
              (energy--rover2_1)
              (energy--rover2_4)
              (energy--rover2_5)
              (v5_1)
              (v5_2)
              (v5_3)
              (v5_4)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_4)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_4)
              (v8_0)
              (v8_1)
              (v8_2)
              (v8_3)
              (v8_5)
              (v9_0)
              (v9_1)
              (v9_2)
              (v9_3)
              (v9_5)
              (v10_0)
              (v10_1)
              (v10_2)
              (v10_3)
              (v10_5)
              (v11_0)
              (v11_1)
              (v11_2)
              (v11_3)
              (v11_5)
              (energy--rover3_1)
              (energy--rover3_4)
              (energy--rover3_5)
              (v12_0)
              (v12_2)
              (v12_3)
              (v12_5)
              (v13_0)
              (v13_2)
              (v13_3)
              (v13_5)
              (v14_4)
              (v14_5)
              (v15_4)
              (v15_5)
              (= (total-cost) 0)
 )
 (:goal (and 
           (communicated_soil_data waypoint7)
           (communicated_soil_data waypoint5)
           (communicated_soil_data waypoint2)
           (communicated_soil_data waypoint4)
           (communicated_rock_data waypoint4)
           (communicated_rock_data waypoint6)
           (communicated_rock_data waypoint7)
           (communicated_rock_data waypoint8)
           (communicated_rock_data waypoint1)
           (communicated_image_data objective3 highres)
           (communicated_image_data objective1 highres)
           (communicated_image_data objective2 highres)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
