(define (problem mprimex24) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_anger9_wurst)
 (craves_curiosity_muffin)
 (craves_abrasion27_melon)
 (craves_laceration7_shrimp)
 (craves_satiety_bacon)
 (craves_hangover_chicken)
 (craves_anger_muffin)
 (craves_depression30_melon)
 (craves_abrasion_chicken)
 (craves_boils_lettuce)
 (craves_jealousy8_pepper)
 (craves_grief_turkey)
 (craves_dread_lettuce)
 (craves_sciatica11_apple)
 (craves_achievement_cherry)
 (craves_depression_cherry)
 (craves_dread28_melon)
 (craves_jealousy_lettuce)
 (craves_boils5_shrimp)
 (craves_anxiety_lettuce)
 (craves_anxiety4_pepper)
 (craves_angina_turkey)
 (craves_anger12_apple)
 (craves_laceration_chicken)
 (craves_hangover10_wurst)
 (craves_grief15_orange)
 (craves_loneliness_tofu)
 (craves_loneliness31_potato)
 (craves_sciatica29_melon)
 (craves_prostatitis3_pepper)
 (craves_hangover13_orange)
 (craves_abrasion2_chocolate)
 (craves_sciatica_tofu)
 (craves_depression14_orange)
 (craves_dread6_shrimp)
 (craves_angina32_wurst)
 (craves_angina16_shrimp)
 (craves_anxiety26_melon)
 (craves_prostatitis_chicken)
 (craves_loneliness1_pepper)
(= (locale_bacon) 5.000000 )
(= (locale_turkey) 2.000000 )
(= (locale_pepper) 9.000000 )
(= (locale_cherry) 0.000000 )
(= (harmony_satiety) 2.000000 )
(= (locale_shrimp) 1.000000 )
(= (locale_tofu) 0.000000 )
(= (harmony_curiosity) 3.000000 )
(= (locale_lettuce) 4.000000 )
(= (harmony_achievement) 2.000000 )
(= (locale_chocolate) 4.000000 )
(= (locale_chicken) 2.000000 )
(= (locale_apple) 0.000000 )
(= (locale_muffin) 3.000000 )
(= (locale_wurst) 1.000000 )
(= (locale_potato) 9.000000 )
(= (locale_orange) 3.000000 )
(= (locale_melon) 9.000000 )
)
(:goal (and  (craves_anger12_cherry) (craves_anxiety4_pepper) (craves_jealousy8_pepper)) )

 )