(define (problem mprimex21) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_prostatitis7_snickers)
 (craves_sciatica_wurst)
 (craves_hangover_lemon)
 (craves_anger_flounder)
 (craves_hangover3_okra)
 (craves_angina_flounder)
 (craves_anger4_okra)
 (craves_boils12_popover)
 (craves_laceration10_popover)
 (craves_boils_apple)
 (craves_angina1_okra)
 (craves_jealousy_muffin)
 (craves_loneliness32_hamburger)
 (craves_expectation_okra)
 (craves_triumph_apple)
 (craves_rest_guava)
 (craves_depression8_okra)
 (craves_prostatitis_muffin)
 (craves_anxiety13_popover)
 (craves_depression_lemon)
 (craves_satisfaction_muffin)
 (craves_laceration_apple)
 (craves_dread14_popover)
 (craves_laceration5_marzipan)
 (craves_abrasion_muffin)
 (craves_loneliness_wurst)
 (craves_loneliness15_marzipan)
 (craves_grief31_hamburger)
 (craves_love_flounder)
 (craves_abrasion6_onion)
 (craves_jealousy11_popover)
 (craves_learning_lemon)
 (craves_grief_muffin)
 (craves_boils30_hamburger)
 (craves_dread_muffin)
 (craves_anxiety_apple)
 (craves_hangover9_hamburger)
 (craves_sciatica16_marzipan)
 (craves_grief2_wurst)
 (craves_abrasion29_guava)
(= (locale_guava) 1.000000 )
(= (locale_okra) 2.000000 )
(= (locale_flounder) 1.000000 )
(= (locale_lemon) 1.000000 )
(= (locale_apple) 0.000000 )
(= (harmony_love) 2.000000 )
(= (harmony_expectation) 2.000000 )
(= (harmony_rest) 1.000000 )
(= (locale_snickers) 2.000000 )
(= (harmony_learning) 3.000000 )
(= (locale_muffin) 0.000000 )
(= (locale_marzipan) 1.000000 )
(= (harmony_triumph) 2.000000 )
(= (locale_hamburger) 1.000000 )
(= (locale_onion) 0.000000 )
(= (locale_popover) 2.000000 )
(= (harmony_satisfaction) 3.000000 )
(= (locale_wurst) 0.000000 )
)
(:goal (and  (craves_sciatica_apple)) )

 )