(define (problem mprimex2) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_laceration_tuna)
 (craves_dread_onion)
 (craves_prostatitis_beef)
 (craves_boils4_ham)
 (craves_entertainment_ham)
 (craves_satiety_onion)
 (craves_stimulation_flounder)
 (craves_curiosity_cherry)
 (craves_jealousy_flounder)
 (craves_loneliness_onion)
 (craves_anxiety_flounder)
 (craves_sciatica_tuna)
 (craves_grief_beef)
 (craves_grief7_ham)
 (craves_jealousy2_cherry)
 (craves_angina_onion)
 (craves_depression1_muffin)
 (craves_anger_beef)
 (craves_abrasion_beef)
 (craves_hangover_tuna)
 (craves_boils_tuna)
 (craves_prostatitis3_ham)
 (craves_dread8_ham)
 (craves_depression_beef)
(= (locale_beef) 4.000000 )
(= (locale_onion) 3.000000 )
(= (locale_tuna) 2.000000 )
(= (locale_ham) 4.000000 )
(= (harmony_satiety) 1.000000 )
(= (locale_flounder) 2.000000 )
(= (harmony_entertainment) 3.000000 )
(= (harmony_stimulation) 2.000000 )
(= (locale_muffin) 2.000000 )
(= (harmony_curiosity) 2.000000 )
(= (locale_cherry) 4.000000 )
)
(:goal (and  (craves_grief7_beef) (craves_depression1_beef)) )

 )