(define (problem mprimex9) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_hangover_haroset)
 (craves_loneliness_haroset)
 (craves_laceration_wurst)
 (craves_anxiety_wurst)
 (craves_anger_haroset)
 (craves_curiosity_hotdog)
 (craves_dread_flounder)
 (craves_intoxication_haroset)
 (craves_angina_guava)
 (craves_excitement_guava)
 (craves_jealousy_guava)
 (craves_sciatica_flounder)
 (craves_grief_guava)
 (craves_boils_guava)
 (craves_entertainment_flounder)
 (craves_prostatitis_haroset)
 (craves_abrasion_haroset)
(= (locale_hotdog) 1.000000 )
(= (locale_wurst) 1.000000 )
(= (harmony_intoxication) 1.000000 )
(= (locale_hamburger) 0.000000 )
(= (harmony_excitement) 1.000000 )
(= (harmony_entertainment) 3.000000 )
(= (locale_haroset) 2.000000 )
(= (harmony_curiosity) 1.000000 )
(= (locale_flounder) 2.000000 )
(= (locale_guava) 4.000000 )
(= (locale_apple) 2.000000 )
)
(:goal (and  (craves_sciatica_hamburger) (craves_jealousy_wurst)) )

 )