(define (problem mprimex5) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_satisfaction_broccoli)
 (craves_jealousy_shrimp)
 (craves_grief_broccoli)
 (craves_intoxication_tuna)
 (craves_hangover_scallop)
 (craves_excitement_turkey)
 (craves_loneliness_scallop)
 (craves_depression_turkey)
 (craves_lubricity_sweetroll)
 (craves_dread_scallop)
 (craves_grief2_scallop)
 (craves_angina_shrimp)
 (craves_laceration_shrimp)
 (craves_anxiety_broccoli)
 (craves_prostatitis_turkey)
 (craves_boils_broccoli)
 (craves_abrasion_turkey)
 (craves_anger_cherry)
 (craves_sciatica_broccoli)
(= (harmony_excitement) 3.000000 )
(= (locale_tuna) 3.000000 )
(= (harmony_lubricity) 2.000000 )
(= (locale_cherry) 1.000000 )
(= (harmony_satisfaction) 2.000000 )
(= (locale_scallop) 0.000000 )
(= (locale_shrimp) 1.000000 )
(= (locale_turkey) 1.000000 )
(= (locale_broccoli) 3.000000 )
(= (locale_chocolate) 2.000000 )
(= (harmony_intoxication) 2.000000 )
(= (locale_sweetroll) 0.000000 )
)
(:goal (and  (craves_loneliness_shrimp) (craves_grief_shrimp)) )

 )