(define (problem mprimex28) (:domain mysteryprimetyped) 
(:objects )
(:init  (craves_hangover_shrimp)
 (craves_anger_muffin)
 (craves_intoxication_wurst)
 (craves_boils_broccoli)
 (craves_anxiety_shrimp)
 (craves_grief_lamb)
 (craves_angina_muffin)
 (craves_loneliness_wurst)
(= (locale_shrimp) 6.000000 )
(= (locale_lamb) 7.000000 )
(= (locale_broccoli) 7.000000 )
(= (harmony_intoxication) 2.000000 )
(= (locale_wurst) 1.000000 )
(= (locale_muffin) 2.000000 )
)
(:goal (and  (craves_boils_lamb) (craves_anger_lamb)) )

 )