(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at s0 wa0)
              (isnext wa0 wa1)
              (isnext wa1 wa2)
              (isnext wa2 wa3)
              (isnext wa3 wa4)
              (isnext wa4 wa5)
              (at s1 wa0)
              (v2_0)
              (v2_1)
              (v2_2)
              (v2_5)
              (v2_6)
              (v2_7)
              (v2_8)
              (v2_9)
              (v3_0)
              (v3_2)
              (v3_3)
              (v3_4)
              (v3_5)
              (v3_6)
              (v3_7)
              (v3_8)
              (v3_9)
              (v3_10)
              (v4_0)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_4)
              (v4_5)
              (v4_6)
              (v4_7)
              (v4_8)
              (v4_9)
              (v4_10)
              (v5_0)
              (v5_1)
              (v5_2)
              (v5_3)
              (v5_4)
              (v5_5)
              (v5_6)
              (v5_7)
              (v5_8)
              (v5_9)
              (v5_10)
              (v6_0)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_4)
              (v6_5)
              (v6_6)
              (v6_7)
              (v6_8)
              (v6_9)
              (v6_10)
              (sledcapacity--s0_2)
              (sledsupplies--s0_0)
              (v7_0)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_4)
              (v7_5)
              (v7_6)
              (v7_7)
              (v7_8)
              (v7_9)
              (v7_10)
              (waypointsupplies--wa0_3)
              (waypointsupplies--wa0_5)
              (waypointsupplies--wa0_6)
              (waypointsupplies--wa0_7)
              (waypointsupplies--wa0_8)
              (waypointsupplies--wa0_9)
              (v8_0)
              (v8_1)
              (v8_2)
              (v8_3)
              (v8_4)
              (v8_5)
              (v8_6)
              (v8_7)
              (v8_8)
              (v8_9)
              (v8_10)
              (v9_0)
              (v9_2)
              (v9_3)
              (v9_4)
              (v9_5)
              (v9_6)
              (v9_7)
              (v9_8)
              (v9_9)
              (v9_10)
              (sledcapacity--s1_2)
              (sledsupplies--s1_0)
 )
 (:goal (and 
           (at s0 wa5)
           (at s1 wa5)
           (not (of))
        )
 )
)
