(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door rooma roomc)
              (door roomc rooma)
              (weight--item12_1)
              (weight--item11_1)
              (weight--item10_0)
              (weight--item9_0)
              (weight--item8_0)
              (weight--item7_0)
              (weight--item6_1)
              (weight--item5_1)
              (weight--item4_0)
              (weight--item3_0)
              (weight--item2_0)
              (weight--item1_0)
              (load_limit--bot1_2)
              (load_limit--bot2_2)
              (v0_1)
              (v1_1)
              (v2_0)
              (v2_1)
              (v3_0)
              (v3_1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item12 roomb)
           (at item11 roomb)
           (at item10 roomb)
           (at item9 roomb)
           (at item8 roomb)
           (at item7 roomb)
           (at item6 roomc)
           (at item5 roomc)
           (at item4 roomc)
           (at item3 roomc)
           (at item2 roomc)
           (at item1 roomc)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
