(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door roomd roomb)
              (door roomb roomd)
              (door rooma roomc)
              (door roomc rooma)
              (weight--item10_1)
              (weight--item9_1)
              (weight--item8_0)
              (v0_1)
              (weight--item7_0)
              (v1_1)
              (weight--item6_0)
              (weight--item5_0)
              (weight--item4_0)
              (v2_0)
              (v2_1)
              (weight--item3_0)
              (v3_0)
              (v3_1)
              (weight--item2_0)
              (weight--item1_0)
              (load_limit--bot1_2)
              (load_limit--bot2_2)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item10 roomb)
           (at item9 roomb)
           (at item8 roomd)
           (at item7 roomd)
           (at item6 roomd)
           (at item5 roomd)
           (at item4 roomc)
           (at item3 roomc)
           (at item2 roomc)
           (at item1 roomc)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
