(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item18 rooma)
              (at item17 rooma)
              (at item16 rooma)
              (at item15 rooma)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door rooma roomc)
              (door roomc rooma)
              (door roomd roomb)
              (door roomb roomd)
              (door roomd roomc)
              (door roomc roomd)
              (v0_0)
              (v0_2)
              (v1_0)
              (v1_2)
              (weight--item18_0)
              (weight--item17_0)
              (weight--item16_0)
              (weight--item15_0)
              (weight--item14_0)
              (weight--item13_0)
              (weight--item12_0)
              (weight--item11_0)
              (weight--item10_0)
              (weight--item9_0)
              (weight--item8_0)
              (weight--item7_0)
              (weight--item6_0)
              (weight--item5_0)
              (weight--item4_0)
              (weight--item3_0)
              (weight--item2_0)
              (weight--item1_0)
              (load_limit--bot1_1)
              (load_limit--bot1_2)
              (load_limit--bot2_1)
              (load_limit--bot2_2)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item18 roomd)
           (at item17 roomd)
           (at item16 roomd)
           (at item15 roomd)
           (at item14 roomd)
           (at item13 roomd)
           (at item12 roomc)
           (at item11 roomc)
           (at item10 roomc)
           (at item9 roomc)
           (at item8 roomc)
           (at item7 roomc)
           (at item6 roomb)
           (at item5 roomb)
           (at item4 roomb)
           (at item3 roomb)
           (at item2 roomb)
           (at item1 roomb)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
