(define (problem marketcount2-problem)
 (:domain marketcount2-domain)
 (:objects
   camel0 - camel
   food expensiverugs coffee cattle water cars gummybears computers laminatefloor copper footballs kittens minerals gold platinum dvds turingmachines - goods
   palanga oslo - market
 )
 (:init (= (price food palanga) 76) (= (on_sale food palanga) 6) (= (price expensiverugs palanga) 80) (= (on_sale expensiverugs palanga) 10) (= (price coffee palanga) 260) (= (on_sale coffee palanga) 2) (= (price cattle palanga) 160) (= (on_sale cattle palanga) 0) (= (price water palanga) 332) (= (on_sale water palanga) 0) (= (price cars palanga) 783) (= (on_sale cars palanga) 54) (= (price gummybears palanga) 940) (= (on_sale gummybears palanga) 8) (= (price computers palanga) 616) (= (on_sale computers palanga) 56) (= (price laminatefloor palanga) 468) (= (on_sale laminatefloor palanga) 40) (= (price copper palanga) 312) (= (on_sale copper palanga) 17) (= (price footballs palanga) 496) (= (on_sale footballs palanga) 29) (= (price kittens palanga) 703) (= (on_sale kittens palanga) 0) (= (price minerals palanga) 128) (= (on_sale minerals palanga) 53) (= (price gold palanga) 388) (= (on_sale gold palanga) 2) (= (price platinum palanga) 683) (= (on_sale platinum palanga) 55) (= (price dvds palanga) 180) (= (on_sale dvds palanga) 0) (= (price turingmachines palanga) 212) (= (on_sale turingmachines palanga) 0) (= (price food oslo) 43) (= (on_sale food oslo) 14) (= (price expensiverugs oslo) 63) (= (on_sale expensiverugs oslo) 14) (= (price coffee oslo) 212) (= (on_sale coffee oslo) 14) (= (price cattle oslo) 80) (= (on_sale cattle oslo) 0) (= (price water oslo) 252) (= (on_sale water oslo) 15) (= (price cars oslo) 912) (= (on_sale cars oslo) 22) (= (price gummybears oslo) 380) (= (on_sale gummybears oslo) 0) (= (price computers oslo) 840) (= (on_sale computers oslo) 0) (= (price laminatefloor oslo) 563) (= (on_sale laminatefloor oslo) 16) (= (price copper oslo) 328) (= (on_sale copper oslo) 13) (= (price footballs oslo) 703) (= (on_sale footballs oslo) 0) (= (price kittens oslo) 560) (= (on_sale kittens oslo) 0) (= (price minerals oslo) 112) (= (on_sale minerals oslo) 57) (= (price gold oslo) 372) (= (on_sale gold oslo) 6) (= (price platinum oslo) 652) (= (on_sale platinum oslo) 63) (= (price dvds oslo) 163) (= (on_sale dvds oslo) 0) (= (price turingmachines oslo) 452) (= (on_sale turingmachines oslo) 0) (= (bought food) 0) (= (bought expensiverugs) 0) (= (bought coffee) 0) (= (bought cattle) 0) (= (bought water) 0) (= (bought cars) 0) (= (bought gummybears) 0) (= (bought computers) 0) (= (bought laminatefloor) 0) (= (bought copper) 0) (= (bought footballs) 0) (= (bought kittens) 0) (= (bought minerals) 0) (= (bought gold) 0) (= (bought platinum) 0) (= (bought dvds) 0) (= (bought turingmachines) 0) (= (drive_cost palanga oslo) 40) (= (drive_cost oslo palanga) 40) (can_drive palanga oslo) (can_drive oslo palanga) (at_ camel0 oslo) (= (cash) 1000) (= (capacity) 20) (= (drive_cost palanga palanga) 0) (= (drive_cost oslo oslo) 0))
 (:goal (and (<= 10000 (cash))))
)
