(define (problem marketcount2-problem)
 (:domain marketcount2-domain)
 (:objects
   camel0 - camel
   food expensiverugs coffee cattle water cars gummybears computers laminatefloor copper footballs kittens minerals gold platinum dvds turingmachines - goods
   moscow obeliai - market
 )
 (:init (= (price food moscow) 52) (= (on_sale food moscow) 12) (= (price expensiverugs moscow) 68) (= (on_sale expensiverugs moscow) 13) (= (price coffee moscow) 223) (= (on_sale coffee moscow) 11) (= (price cattle moscow) 100) (= (on_sale cattle moscow) 0) (= (price water moscow) 272) (= (on_sale water moscow) 10) (= (price cars moscow) 880) (= (on_sale cars moscow) 30) (= (price gummybears moscow) 263) (= (on_sale gummybears moscow) 0) (= (price computers moscow) 783) (= (on_sale computers moscow) 14) (= (price laminatefloor moscow) 540) (= (on_sale laminatefloor moscow) 22) (= (price copper moscow) 323) (= (on_sale copper moscow) 14) (= (price footballs moscow) 652) (= (on_sale footballs moscow) 0) (= (price kittens moscow) 596) (= (on_sale kittens moscow) 0) (= (price minerals moscow) 116) (= (on_sale minerals moscow) 56) (= (price gold moscow) 376) (= (on_sale gold moscow) 5) (= (price platinum moscow) 660) (= (on_sale platinum moscow) 61) (= (price dvds moscow) 168) (= (on_sale dvds moscow) 0) (= (price turingmachines moscow) 392) (= (on_sale turingmachines moscow) 0) (= (price food obeliai) 28) (= (on_sale food obeliai) 18) (= (price expensiverugs obeliai) 56) (= (on_sale expensiverugs obeliai) 16) (= (price coffee obeliai) 188) (= (on_sale coffee obeliai) 20) (= (price cattle obeliai) 40) (= (on_sale cattle obeliai) 0) (= (price water obeliai) 212) (= (on_sale water obeliai) 25) (= (price cars obeliai) 976) (= (on_sale cars obeliai) 6) (= (price gummybears obeliai) 612) (= (on_sale gummybears obeliai) 26) (= (price computers obeliai) 952) (= (on_sale computers obeliai) 0) (= (price laminatefloor obeliai) 612) (= (on_sale laminatefloor obeliai) 4) (= (price copper obeliai) 336) (= (on_sale copper obeliai) 11) (= (price footballs obeliai) 808) (= (on_sale footballs obeliai) 0) (= (price kittens obeliai) 488) (= (on_sale kittens obeliai) 18) (= (price minerals obeliai) 103) (= (on_sale minerals obeliai) 59) (= (price gold obeliai) 363) (= (on_sale gold obeliai) 8) (= (price platinum obeliai) 636) (= (on_sale platinum obeliai) 3) (= (price dvds obeliai) 156) (= (on_sale dvds obeliai) 0) (= (price turingmachines obeliai) 572) (= (on_sale turingmachines obeliai) 0) (= (bought food) 0) (= (bought expensiverugs) 0) (= (bought coffee) 0) (= (bought cattle) 0) (= (bought water) 0) (= (bought cars) 0) (= (bought gummybears) 0) (= (bought computers) 0) (= (bought laminatefloor) 0) (= (bought copper) 0) (= (bought footballs) 0) (= (bought kittens) 0) (= (bought minerals) 0) (= (bought gold) 0) (= (bought platinum) 0) (= (bought dvds) 0) (= (bought turingmachines) 0) (= (drive_cost moscow obeliai) 26) (= (drive_cost obeliai moscow) 26) (can_drive moscow obeliai) (can_drive obeliai moscow) (at_ camel0 obeliai) (= (cash) 1000) (= (capacity) 20) (= (drive_cost moscow moscow) 0) (= (drive_cost obeliai obeliai) 0))
 (:goal (and (<= 10000 (cash))))
)
