(define (problem marketcount2-problem)
 (:domain marketcount2-domain)
 (:objects
   camel0 - camel
   food expensiverugs coffee cattle water cars gummybears computers laminatefloor copper footballs kittens minerals gold platinum dvds turingmachines - goods
   lisbon berlin - market
 )
 (:init (= (price food lisbon) 76) (= (on_sale food lisbon) 6) (= (price expensiverugs lisbon) 80) (= (on_sale expensiverugs lisbon) 10) (= (price coffee lisbon) 260) (= (on_sale coffee lisbon) 2) (= (price cattle lisbon) 160) (= (on_sale cattle lisbon) 0) (= (price water lisbon) 332) (= (on_sale water lisbon) 0) (= (price cars lisbon) 783) (= (on_sale cars lisbon) 54) (= (price gummybears lisbon) 940) (= (on_sale gummybears lisbon) 8) (= (price computers lisbon) 616) (= (on_sale computers lisbon) 56) (= (price laminatefloor lisbon) 468) (= (on_sale laminatefloor lisbon) 40) (= (price copper lisbon) 312) (= (on_sale copper lisbon) 17) (= (price footballs lisbon) 496) (= (on_sale footballs lisbon) 29) (= (price kittens lisbon) 703) (= (on_sale kittens lisbon) 0) (= (price minerals lisbon) 128) (= (on_sale minerals lisbon) 53) (= (price gold lisbon) 388) (= (on_sale gold lisbon) 2) (= (price platinum lisbon) 683) (= (on_sale platinum lisbon) 55) (= (price dvds lisbon) 180) (= (on_sale dvds lisbon) 0) (= (price turingmachines lisbon) 212) (= (on_sale turingmachines lisbon) 0) (= (price food berlin) 36) (= (on_sale food berlin) 16) (= (price expensiverugs berlin) 60) (= (on_sale expensiverugs berlin) 15) (= (price coffee berlin) 200) (= (on_sale coffee berlin) 17) (= (price cattle berlin) 60) (= (on_sale cattle berlin) 0) (= (price water berlin) 232) (= (on_sale water berlin) 20) (= (price cars berlin) 943) (= (on_sale cars berlin) 14) (= (price gummybears berlin) 496) (= (on_sale gummybears berlin) 55) (= (price computers berlin) 896) (= (on_sale computers berlin) 0) (= (price laminatefloor berlin) 588) (= (on_sale laminatefloor berlin) 10) (= (price copper berlin) 332) (= (on_sale copper berlin) 12) (= (price footballs berlin) 756) (= (on_sale footballs berlin) 0) (= (price kittens berlin) 523) (= (on_sale kittens berlin) 9) (= (price minerals berlin) 108) (= (on_sale minerals berlin) 58) (= (price gold berlin) 368) (= (on_sale gold berlin) 7) (= (price platinum berlin) 643) (= (on_sale platinum berlin) 1) (= (price dvds berlin) 160) (= (on_sale dvds berlin) 0) (= (price turingmachines berlin) 512) (= (on_sale turingmachines berlin) 0) (= (bought food) 0) (= (bought expensiverugs) 0) (= (bought coffee) 0) (= (bought cattle) 0) (= (bought water) 0) (= (bought cars) 0) (= (bought gummybears) 0) (= (bought computers) 0) (= (bought laminatefloor) 0) (= (bought copper) 0) (= (bought footballs) 0) (= (bought kittens) 0) (= (bought minerals) 0) (= (bought gold) 0) (= (bought platinum) 0) (= (bought dvds) 0) (= (bought turingmachines) 0) (= (drive_cost lisbon berlin) 43) (= (drive_cost berlin lisbon) 43) (can_drive lisbon berlin) (can_drive berlin lisbon) (at_ camel0 berlin) (= (cash) 1000) (= (capacity) 20) (= (drive_cost lisbon lisbon) 0) (= (drive_cost berlin berlin) 0))
 (:goal (and (<= 10000 (cash))))
)
