(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   c0 c1 c2 c3 - counter
 )
 (:init
              (v5_0)
              (v5_1)
              (v5_2)
              (v5_3)
              (v5_4)
              (v5_5)
              (v5_6)
              (v5_7)
              (max_int_3)
              (v6_0)
              (v6_1)
              (v6_2)
              (v6_3)
              (v6_4)
              (v6_5)
              (v6_6)
              (v6_7)
              (v7_0)
              (v7_1)
              (v7_2)
              (v7_3)
              (v7_4)
              (v7_5)
              (v7_6)
              (v7_7)
              (v8_0)
              (v8_1)
              (v8_2)
              (v8_3)
              (v8_4)
              (v8_5)
              (v8_6)
              (v8_7)
              (v0_0)
              (v0_1)
              (v0_2)
              (v9_0)
              (v9_1)
              (v9_2)
              (v9_3)
              (v9_4)
              (v9_5)
              (v9_6)
              (v9_7)
              (v1_0)
              (v1_1)
              (v1_2)
              (v10_0)
              (v10_1)
              (v10_2)
              (v10_3)
              (v10_4)
              (v10_5)
              (v10_6)
              (v10_7)
              (v2_0)
              (v2_1)
              (v2_2)
              (v3_0)
              (v3_1)
              (v3_2)
              (v4_0)
              (v4_1)
              (v4_2)
              (v4_3)
              (v4_4)
              (v4_5)
              (v4_6)
              (v4_7)
 )
 (:goal (and 
           (not (v8_7))
           (not (v9_7))
           (not (v10_7))
           (not (of))
        )
 )
)
