(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_hangover_shrimp)
              (craves_anger_muffin)
              (craves_intoxication_wurst)
              (craves_boils_broccoli)
              (craves_anxiety_shrimp)
              (craves_grief_lamb)
              (craves_angina_muffin)
              (craves_loneliness_wurst)
              (level_v5__8)
              (geq_v5)
              (level_locale_wurst__1)
              (geq_locale_wurst)
              (level_locale_lamb__7)
              (geq_locale_lamb)
              (level_locale_shrimp__6)
              (geq_locale_shrimp)
              (level_harmony_intoxication__2)
              (geq_harmony_intoxication)
              (level_v0__2)
              (geq_v0)
              (level_v1__3)
              (geq_v1)
              (level_locale_broccoli__7)
              (geq_locale_broccoli)
              (level_locale_muffin__2)
              (geq_locale_muffin)
              (level_v2__7)
              (geq_v2)
              (level_v3__3)
              (geq_v3)
              (level_v4__8)
              (geq_v4)
 )
 (:goal (and 
           (craves_boils_lamb)
           (craves_anger_lamb)
           (not (of))
        )
 )
)
