(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_angina_chicken)
              (craves_rest_pistachio)
              (craves_expectation_tuna)
              (craves_depression_wurst)
              (level_v0__3)
              (geq_v0)
              (level_harmony_rest__3)
              (geq_harmony_rest)
              (level_locale_wurst__2)
              (geq_locale_wurst)
              (level_v1__3)
              (geq_v1)
              (level_locale_tuna__2)
              (geq_locale_tuna)
              (level_locale_chicken__2)
              (geq_locale_chicken)
              (level_harmony_expectation__1)
              (geq_harmony_expectation)
              (level_locale_pistachio__5)
              (geq_locale_pistachio)
              (level_v2__6)
              (geq_v2)
              (level_v3__3)
              (geq_v3)
              (level_v4__4)
              (geq_v4)
              (level_v5__2)
              (geq_v5)
 )
 (:goal (and 
           (craves_depression_chicken)
           (not (of))
        )
 )
)
