(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:init
              (craves_depression_flounder)
              (craves_abrasion_pork)
              (craves_rest_pork)
              (craves_hangover_rice)
              (level_v2__4)
              (geq_v2)
              (level_locale_rice__1)
              (geq_locale_rice)
              (level_v3__3)
              (geq_v3)
              (level_locale_lamb__3)
              (geq_locale_lamb)
              (level_locale_pork__5)
              (geq_locale_pork)
              (level_locale_pear__2)
              (geq_locale_pear)
              (level_v4__4)
              (geq_v4)
              (level_locale_okra__6)
              (geq_locale_okra)
              (level_locale_flounder__4)
              (geq_locale_flounder)
              (level_v5__5)
              (geq_v5)
              (level_v6__7)
              (geq_v6)
              (level_harmony_rest__3)
              (geq_harmony_rest)
              (level_v0__2)
              (geq_v0)
              (level_v1__6)
              (geq_v1)
 )
 (:goal (and 
           (craves_abrasion_rice)
           (not (of))
        )
 )
)
