(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   c0 c1 c2 c3 - counter
 )
 (:init
              (max_int_3)
              (v5_1)
              (v6_1)
              (v6_2)
              (value--c0_0)
              (value--c1_0)
              (value--c1_1)
              (v8_0)
              (value--c2_0)
              (value--c2_1)
              (value--c2_2)
              (v0_1)
              (v0_2)
              (value--c3_0)
              (v1_2)
              (v9_0)
              (v9_1)
              (v10_0)
              (v10_3)
              (v10_4)
              (v10_5)
              (v10_6)
              (v10_7)
              (v3_1)
              (v3_2)
 )
 (:goal (and 
           (not (v8_7))
           (not (v9_7))
           (not (v10_7))
           (not (of))
        )
 )
)
