(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item30 rooma)
              (at item29 rooma)
              (at item28 rooma)
              (at item27 rooma)
              (at item26 rooma)
              (at item25 rooma)
              (at item24 rooma)
              (at item23 rooma)
              (at item22 roomb)
              (at item21 roomb)
              (at item20 roomb)
              (at item19 roomb)
              (at item18 roomb)
              (at item17 roomb)
              (at item16 roomb)
              (at item15 roomb)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (at-bot bot3 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (free left3)
              (free right3)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (mount left3 bot3)
              (mount right3 bot3)
              (door rooma roomb)
              (door roomb roomc)
              (door roomc roomd)
              (door roomd roome)
              (door roome rooma)
              (door rooma roomf)
              (door roomf roomd)
              (level_current_load--bot1__0)
              (geq_current_load--bot1)
              (level_weight--item30__3)
              (geq_weight--item30)
              (level_load_limit--bot1__6)
              (geq_load_limit--bot1)
              (level_weight--item29__3)
              (geq_weight--item29)
              (level_current_load--bot2__0)
              (geq_current_load--bot2)
              (level_weight--item28__3)
              (geq_weight--item28)
              (level_load_limit--bot2__6)
              (geq_load_limit--bot2)
              (level_weight--item27__3)
              (geq_weight--item27)
              (level_current_load--bot3__0)
              (geq_current_load--bot3)
              (level_weight--item26__2)
              (geq_weight--item26)
              (level_load_limit--bot3__6)
              (geq_load_limit--bot3)
              (level_weight--item25__2)
              (geq_weight--item25)
              (level_weight--item24__2)
              (geq_weight--item24)
              (level_weight--item23__2)
              (geq_weight--item23)
              (level_weight--item22__1)
              (geq_weight--item22)
              (level_weight--item21__1)
              (geq_weight--item21)
              (level_weight--item20__1)
              (geq_weight--item20)
              (level_weight--item19__1)
              (geq_weight--item19)
              (level_weight--item18__1)
              (geq_weight--item18)
              (level_weight--item17__1)
              (geq_weight--item17)
              (level_weight--item16__1)
              (geq_weight--item16)
              (level_weight--item15__1)
              (geq_weight--item15)
              (level_weight--item14__1)
              (geq_weight--item14)
              (level_weight--item13__1)
              (geq_weight--item13)
              (level_weight--item12__1)
              (geq_weight--item12)
              (level_weight--item11__1)
              (geq_weight--item11)
              (level_weight--item10__1)
              (geq_weight--item10)
              (level_weight--item9__1)
              (geq_weight--item9)
              (level_weight--item8__1)
              (geq_weight--item8)
              (level_weight--item7__1)
              (geq_weight--item7)
              (level_weight--item6__1)
              (geq_weight--item6)
              (level_v0__3)
              (geq_v0)
              (level_weight--item5__1)
              (geq_weight--item5)
              (level_v1__3)
              (geq_v1)
              (level_weight--item4__1)
              (geq_weight--item4)
              (level_weight--item3__1)
              (geq_weight--item3)
              (level_v2__3)
              (geq_v2)
              (level_weight--item2__1)
              (geq_weight--item2)
              (level_weight--item1__1)
              (geq_weight--item1)
              (level_v3__4)
              (geq_v3)
              (level_v4__4)
              (geq_v4)
              (level_v5__4)
              (geq_v5)
              (level_v6__5)
              (geq_v6)
              (level_v7__5)
              (geq_v7)
              (level_v8__5)
              (geq_v8)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item30 roome)
           (at item29 roome)
           (at item28 roome)
           (at item27 roome)
           (at item26 roome)
           (at item25 roome)
           (at item24 roome)
           (at item23 roome)
           (at item22 roomb)
           (at item21 roomb)
           (at item20 roomb)
           (at item19 roomb)
           (at item18 roomb)
           (at item17 roomb)
           (at item16 roomb)
           (at item15 roomb)
           (at item14 roomc)
           (at item13 roomc)
           (at item12 roomc)
           (at item11 roomc)
           (at item10 roomc)
           (at item9 roomc)
           (at item8 roomf)
           (at item7 roomf)
           (at item6 roomf)
           (at item5 roomf)
           (at item4 roomf)
           (at item3 roomf)
           (at item2 roomf)
           (at item1 roomf)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
