(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item24 rooma)
              (at item23 rooma)
              (at item22 rooma)
              (at item21 rooma)
              (at item20 rooma)
              (at item19 rooma)
              (at item18 rooma)
              (at item17 rooma)
              (at item16 rooma)
              (at item15 rooma)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot octopus rooma)
              (free t1)
              (free t2)
              (free t3)
              (free t4)
              (free t5)
              (free t6)
              (free t7)
              (free t8)
              (mount t1 octopus)
              (mount t2 octopus)
              (mount t3 octopus)
              (mount t4 octopus)
              (mount t5 octopus)
              (mount t6 octopus)
              (mount t7 octopus)
              (mount t8 octopus)
              (door rooma roomb)
              (door roomb rooma)
              (level_current_load--octopus__0)
              (geq_current_load--octopus)
              (level_load_limit--octopus__8)
              (geq_load_limit--octopus)
              (level_v0__7)
              (geq_v0)
              (level_weight--item24__1)
              (geq_weight--item24)
              (level_weight--item23__1)
              (geq_weight--item23)
              (level_weight--item22__1)
              (geq_weight--item22)
              (level_weight--item21__1)
              (geq_weight--item21)
              (level_weight--item20__1)
              (geq_weight--item20)
              (level_weight--item19__1)
              (geq_weight--item19)
              (level_weight--item18__1)
              (geq_weight--item18)
              (level_weight--item17__1)
              (geq_weight--item17)
              (level_weight--item16__1)
              (geq_weight--item16)
              (level_weight--item15__1)
              (geq_weight--item15)
              (level_weight--item14__1)
              (geq_weight--item14)
              (level_weight--item13__1)
              (geq_weight--item13)
              (level_weight--item12__1)
              (geq_weight--item12)
              (level_weight--item11__1)
              (geq_weight--item11)
              (level_weight--item10__1)
              (geq_weight--item10)
              (level_weight--item9__1)
              (geq_weight--item9)
              (level_weight--item8__1)
              (geq_weight--item8)
              (level_weight--item7__1)
              (geq_weight--item7)
              (level_weight--item6__1)
              (geq_weight--item6)
              (level_weight--item5__1)
              (geq_weight--item5)
              (level_weight--item4__1)
              (geq_weight--item4)
              (level_weight--item3__1)
              (geq_weight--item3)
              (level_weight--item2__1)
              (geq_weight--item2)
              (level_weight--item1__1)
              (geq_weight--item1)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item24 roomb)
           (at item23 roomb)
           (at item22 roomb)
           (at item21 roomb)
           (at item20 roomb)
           (at item19 roomb)
           (at item18 roomb)
           (at item17 roomb)
           (at item16 roomb)
           (at item15 roomb)
           (at item14 roomb)
           (at item13 roomb)
           (at item12 roomb)
           (at item11 roomb)
           (at item10 roomb)
           (at item9 roomb)
           (at item8 roomb)
           (at item7 roomb)
           (at item6 roomb)
           (at item5 roomb)
           (at item4 roomb)
           (at item3 roomb)
           (at item2 roomb)
           (at item1 roomb)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
