(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door rooma roomc)
              (door roomc rooma)
              (level_weight--item8__2)
              (geq_weight--item8)
              (level_v1__2)
              (geq_v1)
              (level_weight--item7__2)
              (geq_weight--item7)
              (level_weight--item6__1)
              (geq_weight--item6)
              (level_weight--item5__1)
              (geq_weight--item5)
              (level_v2__3)
              (geq_v2)
              (level_weight--item4__2)
              (geq_weight--item4)
              (level_v3__3)
              (geq_v3)
              (level_weight--item3__2)
              (geq_weight--item3)
              (level_weight--item2__1)
              (geq_weight--item2)
              (level_weight--item1__1)
              (geq_weight--item1)
              (level_current_load--bot1__0)
              (geq_current_load--bot1)
              (level_load_limit--bot1__4)
              (geq_load_limit--bot1)
              (level_current_load--bot2__0)
              (geq_current_load--bot2)
              (level_load_limit--bot2__4)
              (geq_load_limit--bot2)
              (level_v0__2)
              (geq_v0)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item8 roomb)
           (at item7 roomb)
           (at item6 roomb)
           (at item5 roomb)
           (at item4 roomc)
           (at item3 roomc)
           (at item2 roomc)
           (at item1 roomc)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
