(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
 )
 (:init
              (at item20 rooma)
              (at item19 rooma)
              (at item18 rooma)
              (at item17 rooma)
              (at item16 rooma)
              (at item15 rooma)
              (at item14 rooma)
              (at item13 rooma)
              (at item12 rooma)
              (at item11 rooma)
              (at item10 rooma)
              (at item9 rooma)
              (at item8 rooma)
              (at item7 rooma)
              (at item6 rooma)
              (at item5 rooma)
              (at item4 rooma)
              (at item3 rooma)
              (at item2 rooma)
              (at item1 rooma)
              (at-bot bot1 rooma)
              (at-bot bot2 rooma)
              (free left1)
              (free right1)
              (free left2)
              (free right2)
              (mount left1 bot1)
              (mount right1 bot1)
              (mount left2 bot2)
              (mount right2 bot2)
              (door rooma roomb)
              (door roomb rooma)
              (door rooma roomc)
              (door roomc rooma)
              (door roomd roomb)
              (door roomb roomd)
              (door roomd roomc)
              (door roomc roomd)
              (door roomd roome)
              (door roome roomd)
              (level_weight--item20__2)
              (geq_weight--item20)
              (level_weight--item19__2)
              (geq_weight--item19)
              (level_weight--item18__2)
              (geq_weight--item18)
              (level_weight--item17__2)
              (geq_weight--item17)
              (level_weight--item16__1)
              (geq_weight--item16)
              (level_weight--item15__1)
              (geq_weight--item15)
              (level_weight--item14__1)
              (geq_weight--item14)
              (level_weight--item13__1)
              (geq_weight--item13)
              (level_weight--item12__1)
              (geq_weight--item12)
              (level_weight--item11__1)
              (geq_weight--item11)
              (level_weight--item10__1)
              (geq_weight--item10)
              (level_weight--item9__1)
              (geq_weight--item9)
              (level_weight--item8__1)
              (geq_weight--item8)
              (level_weight--item7__1)
              (geq_weight--item7)
              (level_weight--item6__1)
              (geq_weight--item6)
              (level_weight--item5__1)
              (geq_weight--item5)
              (level_weight--item4__1)
              (geq_weight--item4)
              (level_weight--item3__1)
              (geq_weight--item3)
              (level_weight--item2__1)
              (geq_weight--item2)
              (level_weight--item1__1)
              (geq_weight--item1)
              (level_v0__6)
              (geq_v0)
              (level_v1__6)
              (geq_v1)
              (level_v2__7)
              (geq_v2)
              (level_v3__7)
              (geq_v3)
              (level_current_load--bot1__0)
              (geq_current_load--bot1)
              (level_load_limit--bot1__8)
              (geq_load_limit--bot1)
              (level_current_load--bot2__0)
              (geq_current_load--bot2)
              (level_load_limit--bot2__8)
              (geq_load_limit--bot2)
              (= (total-cost) 0)
 )
 (:goal (and 
           (at item20 roome)
           (at item19 roome)
           (at item18 roome)
           (at item17 roome)
           (at item16 roome)
           (at item15 roome)
           (at item14 roome)
           (at item13 roome)
           (at item12 roome)
           (at item11 roome)
           (at item10 roome)
           (at item9 roome)
           (at item8 roome)
           (at item7 roome)
           (at item6 roome)
           (at item5 roome)
           (at item4 roome)
           (at item3 roome)
           (at item2 roome)
           (at item1 roome)
           (not (of))
        )
 )
 (:metric minimize (total-cost))
)
