(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   ore iron stone wood timber coal - resource
 )
 (:init
              (mountain location0)
              (woodland location0)
              (metalliferous location0)
              (woodland location1)
              (mountain location2)
              (woodland location2)
              (by-coast location2)
              (woodland location3)
              (by-coast location3)
              (woodland location4)
              (mountain location5)
              (woodland location5)
              (by-coast location5)
              (woodland location6)
              (woodland location7)
              (by-coast location7)
              (connected-by-land location0 location4)
              (connected-by-land location4 location0)
              (connected-by-land location1 location0)
              (connected-by-land location0 location1)
              (connected-by-land location2 location3)
              (connected-by-land location3 location2)
              (connected-by-land location2 location4)
              (connected-by-land location4 location2)
              (connected-by-land location2 location5)
              (connected-by-land location5 location2)
              (connected-by-land location2 location7)
              (connected-by-land location7 location2)
              (connected-by-land location3 location1)
              (connected-by-land location1 location3)
              (connected-by-land location3 location7)
              (connected-by-land location7 location3)
              (connected-by-land location4 location1)
              (connected-by-land location1 location4)
              (connected-by-land location4 location3)
              (connected-by-land location3 location4)
              (connected-by-land location4 location6)
              (connected-by-land location6 location4)
              (connected-by-land location5 location3)
              (connected-by-land location3 location5)
              (connected-by-land location5 location4)
              (connected-by-land location4 location5)
              (connected-by-land location6 location2)
              (connected-by-land location2 location6)
              (connected-by-land location6 location3)
              (connected-by-land location3 location6)
              (connected-by-land location6 location5)
              (connected-by-land location5 location6)
              (connected-by-land location7 location1)
              (connected-by-land location1 location7)
              (connected-by-land location7 location5)
              (connected-by-land location5 location7)
              (connected-by-land location7 location6)
              (connected-by-land location6 location7)
              (connected-by-sea location3 location5)
              (connected-by-sea location5 location3)
              (potential vehicle0)
              (potential vehicle1)
              (potential vehicle2)
              (potential vehicle3)
              (potential vehicle4)
              (potential vehicle5)
              (potential vehicle6)
              (level_v28__-1)
              (level_v29__-1)
              (level_v30__-1)
              (level_v90__-1)
              (level_v31__-1)
              (level_v32__-1)
              (level_labour__0)
              (geq_labour)
              (level_v33__-1)
              (level_v34__-1)
              (level_v35__-1)
              (level_v91__-1)
              (level_v36__-1)
              (level_v37__-1)
              (level_v38__-1)
              (level_pollution__0)
              (geq_pollution)
              (level_v39__-1)
              (level_v40__-1)
              (level_v98__-2)
              (level_v41__-1)
              (level_v42__-1)
              (level_v43__-1)
              (level_v44__-1)
              (level_v45__-1)
              (level_v46__-1)
              (level_v93__-1)
              (level_v47__-1)
              (level_v48__-1)
              (level_v49__-1)
              (level_v50__-1)
              (level_v51__-1)
              (level_v52__-1)
              (level_v53__-1)
              (level_v54__-1)
              (level_v55__-1)
              (level_resource-use__0)
              (geq_resource-use)
              (level_v56__-1)
              (level_v95__-1)
              (level_v57__-1)
              (level_v58__-1)
              (level_v59__-1)
              (level_v60__-1)
              (level_housing--location0__0)
              (geq_housing--location0)
              (level_available--wood--location0__0)
              (geq_available--wood--location0)
              (level_available--timber--location0__0)
              (geq_available--timber--location0)
              (level_available--ore--location0__0)
              (geq_available--ore--location0)
              (level_available--stone--location0__0)
              (geq_available--stone--location0)
              (level_available--iron--location0__0)
              (geq_available--iron--location0)
              (level_available--coal--location0__0)
              (geq_available--coal--location0)
              (level_v61__-1)
              (level_v62__-1)
              (level_housing--location1__0)
              (geq_housing--location1)
              (level_available--wood--location1__0)
              (geq_available--wood--location1)
              (level_available--timber--location1__0)
              (geq_available--timber--location1)
              (level_available--ore--location1__0)
              (geq_available--ore--location1)
              (level_available--stone--location1__0)
              (geq_available--stone--location1)
              (level_available--iron--location1__0)
              (geq_available--iron--location1)
              (level_available--coal--location1__0)
              (geq_available--coal--location1)
              (level_v63__-1)
              (level_v64__-1)
              (level_v65__-1)
              (level_v66__-1)
              (level_housing--location2__0)
              (geq_housing--location2)
              (level_available--wood--location2__0)
              (geq_available--wood--location2)
              (level_available--timber--location2__0)
              (geq_available--timber--location2)
              (level_available--ore--location2__0)
              (geq_available--ore--location2)
              (level_available--stone--location2__0)
              (geq_available--stone--location2)
              (level_available--iron--location2__0)
              (geq_available--iron--location2)
              (level_available--coal--location2__0)
              (geq_available--coal--location2)
              (level_v67__-1)
              (level_v68__-1)
              (level_v69__-1)
              (level_housing--location3__0)
              (geq_housing--location3)
              (level_available--wood--location3__0)
              (geq_available--wood--location3)
              (level_available--timber--location3__0)
              (geq_available--timber--location3)
              (level_available--ore--location3__0)
              (geq_available--ore--location3)
              (level_available--stone--location3__0)
              (geq_available--stone--location3)
              (level_available--iron--location3__0)
              (geq_available--iron--location3)
              (level_available--coal--location3__0)
              (geq_available--coal--location3)
              (level_v70__-1)
              (level_v71__-1)
              (level_housing--location4__0)
              (geq_housing--location4)
              (level_available--wood--location4__0)
              (geq_available--wood--location4)
              (level_available--timber--location4__0)
              (geq_available--timber--location4)
              (level_available--ore--location4__0)
              (geq_available--ore--location4)
              (level_available--stone--location4__0)
              (geq_available--stone--location4)
              (level_available--iron--location4__0)
              (geq_available--iron--location4)
              (level_available--coal--location4__0)
              (geq_available--coal--location4)
              (level_v73__-1)
              (level_v74__-1)
              (level_v75__-1)
              (level_v76__-1)
              (level_housing--location5__0)
              (geq_housing--location5)
              (level_available--wood--location5__0)
              (geq_available--wood--location5)
              (level_available--timber--location5__0)
              (geq_available--timber--location5)
              (level_available--ore--location5__0)
              (geq_available--ore--location5)
              (level_available--stone--location5__0)
              (geq_available--stone--location5)
              (level_available--iron--location5__0)
              (geq_available--iron--location5)
              (level_available--coal--location5__0)
              (geq_available--coal--location5)
              (level_v77__-1)
              (level_v78__-1)
              (level_housing--location6__0)
              (geq_housing--location6)
              (level_available--wood--location6__0)
              (geq_available--wood--location6)
              (level_available--timber--location6__0)
              (geq_available--timber--location6)
              (level_available--ore--location6__0)
              (geq_available--ore--location6)
              (level_available--stone--location6__0)
              (geq_available--stone--location6)
              (level_available--iron--location6__0)
              (geq_available--iron--location6)
              (level_available--coal--location6__0)
              (geq_available--coal--location6)
              (level_v80__-1)
              (level_v81__-1)
              (level_v82__-1)
              (level_housing--location7__0)
              (geq_housing--location7)
              (level_available--wood--location7__0)
              (geq_available--wood--location7)
              (level_available--timber--location7__0)
              (geq_available--timber--location7)
              (level_available--ore--location7__0)
              (geq_available--ore--location7)
              (level_available--stone--location7__0)
              (geq_available--stone--location7)
              (level_available--iron--location7__0)
              (geq_available--iron--location7)
              (level_available--coal--location7__0)
              (geq_available--coal--location7)
              (level_v83__-1)
              (level_v84__-1)
              (level_space-in--vehicle0__0)
              (geq_space-in--vehicle0)
              (level_available--timber--vehicle0__0)
              (geq_available--timber--vehicle0)
              (level_available--wood--vehicle0__0)
              (geq_available--wood--vehicle0)
              (level_available--coal--vehicle0__0)
              (geq_available--coal--vehicle0)
              (level_available--stone--vehicle0__0)
              (geq_available--stone--vehicle0)
              (level_available--iron--vehicle0__0)
              (geq_available--iron--vehicle0)
              (level_available--ore--vehicle0__0)
              (geq_available--ore--vehicle0)
              (level_v86__-1)
              (level_space-in--vehicle1__0)
              (geq_space-in--vehicle1)
              (level_available--timber--vehicle1__0)
              (geq_available--timber--vehicle1)
              (level_available--wood--vehicle1__0)
              (geq_available--wood--vehicle1)
              (level_available--coal--vehicle1__0)
              (geq_available--coal--vehicle1)
              (level_available--stone--vehicle1__0)
              (geq_available--stone--vehicle1)
              (level_available--iron--vehicle1__0)
              (geq_available--iron--vehicle1)
              (level_available--ore--vehicle1__0)
              (geq_available--ore--vehicle1)
              (level_v89__-1)
              (level_space-in--vehicle2__0)
              (geq_space-in--vehicle2)
              (level_available--timber--vehicle2__0)
              (geq_available--timber--vehicle2)
              (level_available--wood--vehicle2__0)
              (geq_available--wood--vehicle2)
              (level_available--coal--vehicle2__0)
              (geq_available--coal--vehicle2)
              (level_available--stone--vehicle2__0)
              (geq_available--stone--vehicle2)
              (level_available--iron--vehicle2__0)
              (geq_available--iron--vehicle2)
              (level_available--ore--vehicle2__0)
              (geq_available--ore--vehicle2)
              (level_v92__-1)
              (level_space-in--vehicle3__0)
              (geq_space-in--vehicle3)
              (level_available--timber--vehicle3__0)
              (geq_available--timber--vehicle3)
              (level_available--wood--vehicle3__0)
              (geq_available--wood--vehicle3)
              (level_available--coal--vehicle3__0)
              (geq_available--coal--vehicle3)
              (level_available--stone--vehicle3__0)
              (geq_available--stone--vehicle3)
              (level_available--iron--vehicle3__0)
              (geq_available--iron--vehicle3)
              (level_available--ore--vehicle3__0)
              (geq_available--ore--vehicle3)
              (level_v94__-1)
              (level_space-in--vehicle4__0)
              (geq_space-in--vehicle4)
              (level_available--timber--vehicle4__0)
              (geq_available--timber--vehicle4)
              (level_available--wood--vehicle4__0)
              (geq_available--wood--vehicle4)
              (level_available--coal--vehicle4__0)
              (geq_available--coal--vehicle4)
              (level_available--stone--vehicle4__0)
              (geq_available--stone--vehicle4)
              (level_available--iron--vehicle4__0)
              (geq_available--iron--vehicle4)
              (level_available--ore--vehicle4__0)
              (geq_available--ore--vehicle4)
              (level_v97__-2)
              (level_space-in--vehicle5__0)
              (geq_space-in--vehicle5)
              (level_available--timber--vehicle5__0)
              (geq_available--timber--vehicle5)
              (level_available--wood--vehicle5__0)
              (geq_available--wood--vehicle5)
              (level_available--coal--vehicle5__0)
              (geq_available--coal--vehicle5)
              (level_available--stone--vehicle5__0)
              (geq_available--stone--vehicle5)
              (level_available--iron--vehicle5__0)
              (geq_available--iron--vehicle5)
              (level_available--ore--vehicle5__0)
              (geq_available--ore--vehicle5)
              (level_v99__-2)
              (level_space-in--vehicle6__0)
              (geq_space-in--vehicle6)
              (level_available--timber--vehicle6__0)
              (geq_available--timber--vehicle6)
              (level_available--wood--vehicle6__0)
              (geq_available--wood--vehicle6)
              (level_available--coal--vehicle6__0)
              (geq_available--coal--vehicle6)
              (level_available--stone--vehicle6__0)
              (geq_available--stone--vehicle6)
              (level_available--iron--vehicle6__0)
              (geq_available--iron--vehicle6)
              (level_available--ore--vehicle6__0)
              (geq_available--ore--vehicle6)
              (level_v101__-2)
              (level_v102__-2)
              (level_v103__-2)
              (level_v104__-2)
              (level_v105__-2)
              (level_v106__-2)
              (level_v107__-2)
              (level_v108__-2)
              (level_v109__-2)
              (level_v72__-1)
              (level_v110__-2)
              (level_v111__-2)
              (level_v112__-2)
              (level_v113__-2)
              (level_v114__-2)
              (level_v115__-2)
              (level_v116__-2)
              (level_v117__-2)
              (level_v118__-2)
              (level_v119__-2)
              (level_v120__-2)
              (level_v121__-2)
              (level_v122__-2)
              (level_v123__-2)
              (level_v124__-2)
              (level_v125__-2)
              (level_v126__-2)
              (level_v127__-2)
              (level_v128__-2)
              (level_v129__-2)
              (level_v130__-2)
              (level_v131__-2)
              (level_v132__-2)
              (level_v133__-2)
              (level_v134__-2)
              (level_v135__-2)
              (level_v136__-4)
              (level_v137__-4)
              (level_v138__-4)
              (level_v139__-4)
              (level_v140__-4)
              (level_v141__-4)
              (level_v142__-4)
              (level_v143__-4)
              (level_v79__-1)
              (level_v144__-2)
              (level_v145__-2)
              (level_v146__-2)
              (level_v100__-2)
              (level_v147__-2)
              (level_v148__-2)
              (level_v149__-2)
              (level_v150__-2)
              (level_v151__-2)
              (level_v152__-1)
              (level_v153__-1)
              (level_v154__-1)
              (level_v0__-1)
              (level_v1__-1)
              (level_v2__-1)
              (level_v3__-1)
              (level_v4__-1)
              (level_v5__-1)
              (level_v85__-1)
              (level_v6__-1)
              (level_v7__-1)
              (level_v8__-1)
              (level_v9__-1)
              (level_v10__-1)
              (level_v11__-1)
              (level_v12__-1)
              (level_v13__-1)
              (level_v14__-1)
              (level_v15__-1)
              (level_v87__-1)
              (level_v16__-1)
              (level_v17__-1)
              (level_v18__-1)
              (level_v19__-1)
              (level_v20__-1)
              (level_v88__-1)
              (level_v21__-1)
              (level_v22__-1)
              (level_v23__-1)
              (level_v96__-1)
              (level_v24__-1)
              (level_v25__-1)
              (level_v26__-1)
              (level_v27__-1)
 )
 (:goal (and 
           (geq_v152)
           (geq_v153)
           (has-coal-stack location2)
           (connected-by-rail location3 location7)
           (connected-by-rail location7 location5)
           (connected-by-rail location5 location3)
           (connected-by-rail location6 location3)
           (geq_v154)
           (has-sawmill location2)
           (has-coal-stack location1)
           (connected-by-rail location2 location3)
           (not (of))
        )
 )
)
