(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   ore iron stone wood timber coal - resource
 )
 (:init
              (mountain location0)
              (woodland location0)
              (by-coast location0)
              (woodland location1)
              (by-coast location1)
              (metalliferous location1)
              (woodland location2)
              (by-coast location2)
              (woodland location3)
              (metalliferous location3)
              (mountain location4)
              (woodland location4)
              (by-coast location4)
              (connected-by-land location1 location2)
              (connected-by-land location2 location1)
              (connected-by-land location1 location3)
              (connected-by-land location3 location1)
              (connected-by-land location2 location0)
              (connected-by-land location0 location2)
              (connected-by-land location3 location0)
              (connected-by-land location0 location3)
              (connected-by-land location3 location2)
              (connected-by-land location2 location3)
              (connected-by-land location4 location1)
              (connected-by-land location1 location4)
              (connected-by-land location4 location3)
              (connected-by-land location3 location4)
              (connected-by-sea location0 location4)
              (connected-by-sea location4 location0)
              (potential vehicle0)
              (potential vehicle1)
              (potential vehicle2)
              (potential vehicle3)
              (potential vehicle4)
              (level_v47__-1)
              (level_v48__-1)
              (level_v49__-1)
              (level_v50__-1)
              (level_v51__-1)
              (level_labour__0)
              (geq_labour)
              (level_v52__-1)
              (level_v53__-1)
              (level_v54__-1)
              (level_v55__-1)
              (level_v56__-1)
              (level_v57__-1)
              (level_pollution__0)
              (geq_pollution)
              (level_v58__-1)
              (level_v59__-1)
              (level_v60__-1)
              (level_v61__-1)
              (level_v62__-1)
              (level_v63__-1)
              (level_v64__-1)
              (level_v65__-2)
              (level_v66__-2)
              (level_v67__-2)
              (level_v68__-2)
              (level_v69__-2)
              (level_v70__-2)
              (level_v71__-2)
              (level_v72__-2)
              (level_v73__-2)
              (level_resource-use__0)
              (geq_resource-use)
              (level_v74__-2)
              (level_v75__-2)
              (level_v76__-2)
              (level_v77__-2)
              (level_v78__-2)
              (level_housing--location0__0)
              (geq_housing--location0)
              (level_available--wood--location0__0)
              (geq_available--wood--location0)
              (level_available--timber--location0__0)
              (geq_available--timber--location0)
              (level_available--ore--location0__0)
              (geq_available--ore--location0)
              (level_available--stone--location0__0)
              (geq_available--stone--location0)
              (level_available--iron--location0__0)
              (geq_available--iron--location0)
              (level_available--coal--location0__0)
              (geq_available--coal--location0)
              (level_v79__-2)
              (level_v80__-2)
              (level_v81__-2)
              (level_housing--location1__0)
              (geq_housing--location1)
              (level_available--wood--location1__0)
              (geq_available--wood--location1)
              (level_available--timber--location1__0)
              (geq_available--timber--location1)
              (level_available--ore--location1__0)
              (geq_available--ore--location1)
              (level_available--stone--location1__0)
              (geq_available--stone--location1)
              (level_available--iron--location1__0)
              (geq_available--iron--location1)
              (level_available--coal--location1__0)
              (geq_available--coal--location1)
              (level_v82__-2)
              (level_v83__-2)
              (level_v84__-2)
              (level_housing--location2__0)
              (geq_housing--location2)
              (level_available--wood--location2__0)
              (geq_available--wood--location2)
              (level_available--timber--location2__0)
              (geq_available--timber--location2)
              (level_available--ore--location2__0)
              (geq_available--ore--location2)
              (level_available--stone--location2__0)
              (geq_available--stone--location2)
              (level_available--iron--location2__0)
              (geq_available--iron--location2)
              (level_available--coal--location2__0)
              (geq_available--coal--location2)
              (level_v85__-2)
              (level_v86__-2)
              (level_v87__-2)
              (level_housing--location3__0)
              (geq_housing--location3)
              (level_available--wood--location3__0)
              (geq_available--wood--location3)
              (level_available--timber--location3__0)
              (geq_available--timber--location3)
              (level_available--ore--location3__0)
              (geq_available--ore--location3)
              (level_available--stone--location3__0)
              (geq_available--stone--location3)
              (level_available--iron--location3__0)
              (geq_available--iron--location3)
              (level_available--coal--location3__0)
              (geq_available--coal--location3)
              (level_v88__-2)
              (level_v89__-2)
              (level_v90__-4)
              (level_v91__-4)
              (level_housing--location4__0)
              (geq_housing--location4)
              (level_available--wood--location4__0)
              (geq_available--wood--location4)
              (level_available--timber--location4__0)
              (geq_available--timber--location4)
              (level_available--ore--location4__0)
              (geq_available--ore--location4)
              (level_available--stone--location4__0)
              (geq_available--stone--location4)
              (level_available--iron--location4__0)
              (geq_available--iron--location4)
              (level_available--coal--location4__0)
              (geq_available--coal--location4)
              (level_v92__-4)
              (level_v93__-4)
              (level_space-in--vehicle0__0)
              (geq_space-in--vehicle0)
              (level_available--timber--vehicle0__0)
              (geq_available--timber--vehicle0)
              (level_available--wood--vehicle0__0)
              (geq_available--wood--vehicle0)
              (level_available--coal--vehicle0__0)
              (geq_available--coal--vehicle0)
              (level_available--stone--vehicle0__0)
              (geq_available--stone--vehicle0)
              (level_available--iron--vehicle0__0)
              (geq_available--iron--vehicle0)
              (level_available--ore--vehicle0__0)
              (geq_available--ore--vehicle0)
              (level_v94__-4)
              (level_space-in--vehicle1__0)
              (geq_space-in--vehicle1)
              (level_available--timber--vehicle1__0)
              (geq_available--timber--vehicle1)
              (level_available--wood--vehicle1__0)
              (geq_available--wood--vehicle1)
              (level_available--coal--vehicle1__0)
              (geq_available--coal--vehicle1)
              (level_available--stone--vehicle1__0)
              (geq_available--stone--vehicle1)
              (level_available--iron--vehicle1__0)
              (geq_available--iron--vehicle1)
              (level_available--ore--vehicle1__0)
              (geq_available--ore--vehicle1)
              (level_v97__-2)
              (level_space-in--vehicle2__0)
              (geq_space-in--vehicle2)
              (level_available--timber--vehicle2__0)
              (geq_available--timber--vehicle2)
              (level_available--wood--vehicle2__0)
              (geq_available--wood--vehicle2)
              (level_available--coal--vehicle2__0)
              (geq_available--coal--vehicle2)
              (level_available--stone--vehicle2__0)
              (geq_available--stone--vehicle2)
              (level_available--iron--vehicle2__0)
              (geq_available--iron--vehicle2)
              (level_available--ore--vehicle2__0)
              (geq_available--ore--vehicle2)
              (level_v99__-2)
              (level_space-in--vehicle3__0)
              (geq_space-in--vehicle3)
              (level_available--timber--vehicle3__0)
              (geq_available--timber--vehicle3)
              (level_available--wood--vehicle3__0)
              (geq_available--wood--vehicle3)
              (level_available--coal--vehicle3__0)
              (geq_available--coal--vehicle3)
              (level_available--stone--vehicle3__0)
              (geq_available--stone--vehicle3)
              (level_available--iron--vehicle3__0)
              (geq_available--iron--vehicle3)
              (level_available--ore--vehicle3__0)
              (geq_available--ore--vehicle3)
              (level_space-in--vehicle4__0)
              (geq_space-in--vehicle4)
              (level_available--timber--vehicle4__0)
              (geq_available--timber--vehicle4)
              (level_available--wood--vehicle4__0)
              (geq_available--wood--vehicle4)
              (level_available--coal--vehicle4__0)
              (geq_available--coal--vehicle4)
              (level_available--stone--vehicle4__0)
              (geq_available--stone--vehicle4)
              (level_available--iron--vehicle4__0)
              (geq_available--iron--vehicle4)
              (level_available--ore--vehicle4__0)
              (geq_available--ore--vehicle4)
              (level_v95__-2)
              (level_v96__-2)
              (level_v98__-2)
              (level_v0__-1)
              (level_v100__-2)
              (level_v1__-1)
              (level_v2__-1)
              (level_v3__-1)
              (level_v4__-1)
              (level_v5__-1)
              (level_v6__-1)
              (level_v7__-1)
              (level_v8__-1)
              (level_v9__-1)
              (level_v10__-1)
              (level_v11__-1)
              (level_v12__-1)
              (level_v13__-1)
              (level_v14__-1)
              (level_v15__-1)
              (level_v16__-1)
              (level_v17__-1)
              (level_v18__-1)
              (level_v19__-1)
              (level_v20__-1)
              (level_v21__-1)
              (level_v22__-1)
              (level_v23__-1)
              (level_v24__-1)
              (level_v25__-1)
              (level_v26__-1)
              (level_v27__-1)
              (level_v28__-1)
              (level_v29__-1)
              (level_v30__-1)
              (level_v31__-1)
              (level_v32__-1)
              (level_v33__-1)
              (level_v34__-1)
              (level_v35__-1)
              (level_v36__-1)
              (level_v37__-1)
              (level_v38__-1)
              (level_v39__-1)
              (level_v40__-1)
              (level_v41__-1)
              (level_v42__-1)
              (level_v43__-1)
              (level_v44__-1)
              (level_v45__-1)
              (level_v46__-1)
 )
 (:goal (and 
           (geq_v100)
           (has-coal-stack location0)
           (connected-by-rail location1 location2)
           (not (of))
        )
 )
)
