(define (problem compiledproblem-problem)
 (:domain compiledproblem-domain)
 (:objects
   farm0 farm1 - farm
 )
 (:init
              (adj farm0 farm1)
              (adj farm1 farm0)
              (v4_0)
              (v4_5)
              (v4_8)
              (v4_10)
              (v4_12)
              (v4_13)
              (v4_14)
              (v0_3)
              (v0_4)
              (v0_5)
              (v0_7)
              (v0_9)
              (v1_0)
              (v1_2)
              (v1_3)
              (v1_4)
              (v1_5)
              (v1_6)
              (v1_7)
              (v1_8)
              (v1_9)
              (v1_10)
              (v1_11)
              (v1_12)
              (v1_13)
              (v1_14)
              (v2_0)
              (v2_1)
              (v2_3)
              (v2_4)
              (v2_5)
              (v2_7)
              (v2_9)
              (x--farm0_2)
              (x--farm0_3)
              (x--farm0_4)
              (x--farm0_5)
              (x--farm0_7)
              (x--farm0_9)
              (x--farm1_0)
 )
 (:goal (and 
           (not (v2_14))
           (not (v3_14))
           (not (v4_14))
           (not (of))
        )
 )
)
